#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for 摄影.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="摄影"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 产出不可重来（婚礼、活动、一次性纪实） → 则 在拍摄端、存储端、交付端三处都留冗余，把单点故障降到零。案例：双卡同步写入 + 双机身、当天 3-2-1 备份、交付保留
  • 如果 项目涉及真实性承诺（新闻/纪实/投稿评奖） → 则 守纪实零增删红线、保留并随时可交 RAW；商业/艺术可重度后期但对客户与受众透明。案例：World Press Phot

相关心智模型:
  • 先问光，再问相机（光是主语，器材是宾语）: 摄影的第一性是「看光、控光、塑光」——画面好坏由光的方向/质感/光比决定，相机机身只是记录介质；资深人拿到任何场景先读光，外行先问「该买哪台相机」。
  • 成像前就决定成像（previsualization / 决定性瞬间）: 好照片在按快门之前就已在脑中成形——Adams 的「预想」(previsualization) 与 Cartier-Bresson 的「决定性瞬间」是同一直觉的两极：前者构建式预想最终影调，后者抓取式

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "产出不可重来（婚礼、活动、一次性纪实）"
  "项目涉及真实性承诺（新闻/纪实/投稿评奖）"
)
declare -a RULE_ACTIONS=(
  "在拍摄端、存储端、交付端三处都留冗余，把单点故障降到零。案例：双卡同步写入 + 双机身、当天 3-2-1 备份、交付保留可改稿的分层母版；婚礼摄影师丢卡/单机故障是不可原谅的职业事故，冗余是底线不是选项。(evidence: [T03-S002, T03-S012])"
  "守纪实零增删红线、保留并随时可交 RAW；商业/艺术可重度后期但对客户与受众透明。案例：World Press Photo 全类别禁生成式 AI、只允许去噪与基础调整，投稿要交原始文件；把商业合成手法用到新闻图上会被取消资格并身败名裂。(evidence: [T06-S013, T01-S043])"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
