#!/usr/bin/env bash
# ai-stem-driven-cross-cutting-12-.sh — AI / stem-driven 重混 + 起点生成（cross-cutting，近 12 月的真正新 workflow） SOP walkthrough for 音乐制作 / 混音.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="音乐制作 / 混音"
WORKFLOW="AI / stem-driven 重混 + 起点生成（cross-cutting，近 12 月的真正新 workflow）"

usage() {
  cat <<EOF
ai-stem-driven-cross-cutting-12-.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./ai-stem-driven-cross-cutting-12-.sh             # interactive
  ./ai-stem-driven-cross-cutting-12-.sh --dry-run
  ./ai-stem-driven-cross-cutting-12-.sh --json
  ./ai-stem-driven-cross-cutting-12-.sh --explain
  ./ai-stem-driven-cross-cutting-12-.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "AI / stem-driven 重混 + 起点生成（cross-cutting，近 12 月的真正新 workflow）" 工作流。

一句话: 没有原始多轨时（老歌/采样/已混音成品），用 AI stem 分离拆出 vocal/drums/bass/other，再做重混/采样/修复；或用 AI mix/master assistant 生成一个起点供人工接管 —— 这是近 12 个月**真正新增**的 workflow，横切混音/编辑/母带。(evidence: [T03-S016, T03-S020, T03-S017])

入门 SOP 共 5 步, 失败模式自检 3 项。

相关心智模型:
  • 服务歌优先于服务技术 (serve the song): 技术、音色、个人风格全都服从于"这首歌要表达什么"——好不好的最终裁判是情绪与歌本身，不是参数表（"if it sounds good, it is good"）。
  • 减法优先 / 每个处理都要能说出理由 (less but knowing why): 默认不处理；做得太多而非太少是这一行最常见的病——加任何东西（轨/EQ/压缩/响度）之前，先确认能不能减、不加，且每一次处理都要能讲出"我为什么这么做"。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**选引擎拆 stem**: 用 Logic Stem Splitter（本地）/ RipX / Moises / Lalal / RX Rebalance 从立体声拆出分轨。跳过（即\"有多轨却仍用分离\"）→ 引入不必要伪影（有多轨永远用多轨）。(evidence: [T03-S016])"
  "**伪影 QC（关键）**: 单听每个 stem，找水声/相位/频段残留伪影，决定能不能用。跳过 → 伪影进下游被放大，尤其进母带链。(evidence: [T03-S016])"
  "**（可选）AI mix/master assistant 起点**: 用 mix assistant / Ozone Master Assistant / LANDR 出一版起点。跳过 → 没问题，本就是可选加速步。(evidence: [T03-S020, T03-S017])"
  "**人工接管精修**: 在 AI 起点上按真实混音/母带流程（workflow 4/5）reference A/B + 用耳朵改。跳过 → 把 AI 输出当成品（最常见错误）。(evidence: [T03-S020])"
  "**null / A-B 验证**: 对照原始、A/B（响度匹配），确认 AI 处理真的更好而非\"听起来不一样\"。跳过 → 被\"变化=改进\"错觉骗。(evidence: [T03-S017], null test T06)"
)
declare -a FAILURE_MODES=(
  "**有多轨却用 stem 分离**: 触发原因 = 图快/忘了有原始素材。**CLI 化暗示**: 检查项「你有原始多轨吗？有就别用分离 —— 分离永远有伪影，原始多轨永远更干净」。"
  "**不做伪影 QC 直接用 stem**: 触发原因 = 假设拆出来就干净。**CLI 化暗示**: 检查项「每个拆出的 stem 单独听过吗？有没有水声/相位/残留伪影？这些 stem 适合进母带链吗（通常不）？」。"
  "**把 AI mix/master 输出当成品**: 触发原因 = 省事 + 信营销。**CLI 化暗示**: 检查项「AI 起点是否经过 reference A/B（响度匹配）+ 人工用耳朵接管？还是直接发了？」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "ai-stem-driven-cross-cutting-12--walkthrough"
fi
