#!/usr/bin/env bash
# arrangement-production-idea.sh — Arrangement / Production（把 idea 做到编曲定型） SOP walkthrough for 音乐制作 / 混音.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="音乐制作 / 混音"
WORKFLOW="Arrangement / Production（把 idea 做到编曲定型）"

usage() {
  cat <<EOF
arrangement-production-idea.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./arrangement-production-idea.sh             # interactive
  ./arrangement-production-idea.sh --dry-run
  ./arrangement-production-idea.sh --json
  ./arrangement-production-idea.sh --explain
  ./arrangement-production-idea.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Arrangement / Production（把 idea 做到编曲定型）" 工作流。

一句话: 把一个 idea / topline / beat 从"脑子里"做到"编曲结构与情绪都定型的 session"，决定这首歌要表达什么、用什么乐器/音色、各段落如何起承转合 —— 这是后续所有阶段服务的"歌"本身。(evidence: [T03-S009, T03-S010])

入门 SOP 共 5 步, 失败模式自检 3 项。

相关心智模型:
  • 服务歌优先于服务技术 (serve the song): 技术、音色、个人风格全都服从于"这首歌要表达什么"——好不好的最终裁判是情绪与歌本身，不是参数表（"if it sounds good, it is good"）。
  • 减法优先 / 每个处理都要能说出理由 (less but knowing why): 默认不处理；做得太多而非太少是这一行最常见的病——加任何东西（轨/EQ/压缩/响度）之前，先确认能不能减、不加，且每一次处理都要能讲出"我为什么这么做"。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定结构 + 参考曲**: 选 1-2 首同 genre 商业 reference，定 BPM/调/段落骨架（serve-the-song 第一性，先想\"这歌要什么\"）。跳过 → 编曲漫无目的、各段落不连贯、后期推倒重来。(evidence: [T03-S001, T03-S009])"
  "**铺核心元素**: 鼓/节奏 + 低频(bass) + 和声(chords) + 主旋律/topline 四大件先到位，建立 groove。跳过 → 没有骨架就堆音色，得到\"满但空\"的编曲。(evidence: [T03-S010])"
  "**编曲填充与动态**: 加 ear-candy/transition/层次，做段落间的能量起伏（add/drop element）。跳过 → 全程一个能量，听众 30 秒就走神（Owsinski \"interest\" 第六要素）。"
  "**scratch 人声/参考人声**: 录或放占位人声，确认编曲给人声留了空间（negative space）。跳过 → 编曲塞满，进 tracking 才发现人声无处安放。(evidence: [T03-S009])"
  "**arrangement 定稿 + 清理**: 删掉不服务歌的元素（减法），命名/着色，导出参考 mix 给后续阶段。跳过 → 带着冗余进 tracking，浪费录音/编辑时间。"
)
declare -a FAILURE_MODES=(
  "**过度编曲（over-arranging）**: 触发原因 = 怕\"太空\"而不停加层。**CLI 化暗示**: 检查项「这首歌每个段落是否都有可删的轨？删掉后歌是否更强？如果舍不得删，先静音 30% 的轨听一遍」。"
  "**频段拥堵种在编曲里**: 触发原因 = 多件乐器同占 200-500Hz / 2-5kHz，到混音才发现 mud/harsh 无解。**CLI 化暗示**: 检查项「核心四大件是否各占不同频域？bass 和 kick 是否分工（一个占 sub、一个占 punch）？」。"
  "**没给人声留空间**: 触发原因 = 器乐编曲塞满，topline 进来无处落位。**CLI 化暗示**: 检查项「放 scratch 人声进编曲，人声是否清晰浮在上面？还是被器乐淹没？」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "arrangement-production-idea-walkthrough"
fi
