#!/usr/bin/env bash
# delivery-ddp-streaming-spec-stem.sh — Delivery（DDP / streaming spec / stems / Atmos —— 交付到分发/压盘） SOP walkthrough for 音乐制作 / 混音.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="音乐制作 / 混音"
WORKFLOW="Delivery（DDP / streaming spec / stems / Atmos —— 交付到分发/压盘）"

usage() {
  cat <<EOF
delivery-ddp-streaming-spec-stem.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./delivery-ddp-streaming-spec-stem.sh             # interactive
  ./delivery-ddp-streaming-spec-stem.sh --dry-run
  ./delivery-ddp-streaming-spec-stem.sh --json
  ./delivery-ddp-streaming-spec-stem.sh --explain
  ./delivery-ddp-streaming-spec-stem.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Delivery（DDP / streaming spec / stems / Atmos —— 交付到分发/压盘）" 工作流。

一句话: 把母带定稿打包成各分发渠道要求的格式与元数据 —— streaming 上架的 WAV + 响度/dBTP 合规、压盘的 DDP image、客户/影视要的 stems、以及（近年新增的）Dolby Atmos ADM BWF 沉浸式交付。(evidence: [T03-S014, T03-S004, T03-S018])

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 服务歌优先于服务技术 (serve the song): 技术、音色、个人风格全都服从于"这首歌要表达什么"——好不好的最终裁判是情绪与歌本身，不是参数表（"if it sounds good, it is good"）。
  • 减法优先 / 每个处理都要能说出理由 (less but knowing why): 默认不处理；做得太多而非太少是这一行最常见的病——加任何东西（轨/EQ/压缩/响度）之前，先确认能不能减、不加，且每一次处理都要能讲出"我为什么这么做"。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**确认目标渠道与规格**: 弄清要交给谁、什么格式（采样率/位深/响度/peak/文件类型）。跳过 → 交错格式被打回，或上架后响度/削波出问题。(evidence: [T03-S004])"
  "**导出主交付文件 + 响度/peak 合规复检**: 按规格导出（如 streaming 高解析 WAV、true-peak ≤ -1 dBTP），复检响度 target。跳过 → 转码削波 / 响度被平台拉低或惩罚。(evidence: [T03-S004])"
  "**嵌入元数据（ISRC / 曲目信息）**: 嵌 ISRC（每条录音唯一码）、曲目名/艺人等。跳过 → 版税追踪断链、分发系统报错（每个录音/版本需独立 ISRC）。(evidence: [T03-S014], ISRC T06)"
  "**按渠道生成专属包**: 压盘 → DDP image + checksum + subcode（track index/ISRC/CD-Text）；客户/sync → stems（分组子混，非逐轨）；streaming → 平台规格 WAV。跳过 → 压盘厂无法接收（不是发一堆 WAV）/ stems 给成了 multitracks。(evidence: [T03-S014], stems/DDP T06)"
  "**交付前最终校验**: checksum 核对、试听整张、确认文件命名/版本。跳过 → 交了错版本/损坏文件，返工 + 信誉受损。"
)
declare -a FAILURE_MODES=(
  "**不留 dBTP 余量 → 转码削波**: 触发原因 = 交付文件 true-peak 太高。**CLI 化暗示**: 检查项「交付文件 true-peak 是否 ≤ -1 dBTP？streaming 转码会不会削波？」。"
  "**stems 给成 multitracks（或反之）**: 触发原因 = 不分清分组子混 vs 逐轨。**CLI 化暗示**: 检查项「客户要的是 stems（分组：鼓/人声/乐器子混）还是 multitracks（逐轨）？给对了吗？」。"
  "**压盘只发 WAV，没 DDP**: 触发原因 = 不懂压盘要 DDP image + checksum。**CLI 化暗示**: 检查项「压盘交付是否生成了 DDP image + checksum + subcode（含 ISRC）？」。"
  "**交 Atmos 不附立体声 / 没设 binaural metadata**: 触发原因 = 只导 ADM BWF。**CLI 化暗示**: 检查项「ADM BWF 是否附带了一条立体声 master 兜底？binaural metadata（Near/Mid/Far）是否有意设置过？」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "delivery-ddp-streaming-spec-stem-walkthrough"
fi
