#!/usr/bin/env bash
# mastering-loudness-eq-limiting-d.sh — Mastering（loudness / EQ / limiting / dither / sequencing —— 做成可发行母带） SOP walkthrough for 音乐制作 / 混音.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="音乐制作 / 混音"
WORKFLOW="Mastering（loudness / EQ / limiting / dither / sequencing —— 做成可发行母带）"

usage() {
  cat <<EOF
mastering-loudness-eq-limiting-d.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./mastering-loudness-eq-limiting-d.sh             # interactive
  ./mastering-loudness-eq-limiting-d.sh --dry-run
  ./mastering-loudness-eq-limiting-d.sh --json
  ./mastering-loudness-eq-limiting-d.sh --explain
  ./mastering-loudness-eq-limiting-d.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Mastering（loudness / EQ / limiting / dither / sequencing —— 做成可发行母带）" 工作流。

一句话: 把混音定稿做成可发行母带 —— 全局 EQ/动态微调、命中平台响度 target（不再冲最响）、限制器控峰、降位深时一次 dither、专辑排序与曲间间隔。streaming normalization 时代这一步的**目标假设已被改写**。(evidence: [T03-S004, T03-S006])

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 服务歌优先于服务技术 (serve the song): 技术、音色、个人风格全都服从于"这首歌要表达什么"——好不好的最终裁判是情绪与歌本身，不是参数表（"if it sounds good, it is good"）。
  • 减法优先 / 每个处理都要能说出理由 (less but knowing why): 默认不处理；做得太多而非太少是这一行最常见的病——加任何东西（轨/EQ/压缩/响度）之前，先确认能不能减、不加，且每一次处理都要能讲出"我为什么这么做"。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**校准监听 + reference 母带 A/B**: 在校准监听上放商业 reference 母带，响度匹配后对照。跳过 → 在没校准的系统上母带，结果在别处听垮（Katz：校准监听是母带必需不是可选）。(evidence: [T03-S004], K-System T04)"
  "**全局 EQ + 动态微调**: 对整曲做温和宽带 EQ（修整体音色平衡）+ 多段/M-S 微调，问题应尽量回混音解决而非母带补。跳过 → 整张专辑音色不统一/某频段整体过冲。(evidence: [T03-S004])"
  "**限制器命中响度 target（保动态优先）**: 用 Pro-L 2 / Ozone Maximizer 把响度推到平台 target（≈ -14 LUFS streaming / -1 dBTP），**到 target 即止，不为更响过压**。跳过 → 要么太轻被平台拉低、要么过压牺牲动态换不来响度（normalization 会回拉）。(evidence: [T03-S004, T03-S006], LUFS T06)"
  "**true-peak 余量**: 留 true-peak ≤ -1 dBTP，防 inter-sample peak 在转码时削波。跳过 → 上架/转码后出现削波失真（sample peak 设到 0 测不到 ISP）。(evidence: [T03-S004], dBTP T06)"
  "**dither（降位深时一次）**: 若降到 16-bit（如 CD），最后一次降位深时加一次 dither。跳过 → 量化失真/低电平细节丢失；**或误在浮点链路多次加 dither**（也是错）。(evidence: [T03-S013], dither T06)"
  "**排序 + 曲间间隔 + 母带级聆听**: 专辑曲序、曲间间隔/淡入淡出、整张连续听确认流畅。跳过 → 单曲都好但专辑听感断裂/响度跳变。"
)
declare -a FAILURE_MODES=(
  "**为更响过压（响度战争遗毒）**: 触发原因 = 觉得\"更响=更好/更专业\"。**CLI 化暗示**: 检查项「你的母带 LUFS 是否已经超过平台 target？超过部分会被 normalization 拉低、只赔了动态 —— 是否该回退限制器、保动态？」。"
  "**true-peak 设到 0 → 转码削波**: 触发原因 = 只看 sample peak。**CLI 化暗示**: 检查项「true-peak 表是否 ≤ -1 dBTP？（不是 sample peak）」。"
  "**dither 用错（多次/浮点链乱加/降位深漏加）**: 触发原因 = 不懂 apply-once 规则。**CLI 化暗示**: 检查项「是否只在最后一次降位深（如 24→16bit）加了一次 dither？中间链路有没有误加？」。"
  "**拿 AI 母带输出直接当成品发**: 触发原因 = 图省事不校。**CLI 化暗示**: 检查项「AI 母带（Ozone Assistant/LANDR）输出是否 A/B 过原始？有没有偏 harsh/digital？是否用耳朵校过？」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "mastering-loudness-eq-limiting-d-walkthrough"
fi
