#!/usr/bin/env bash
# mixing-gain-staging-balance-eq-c.sh — Mixing（gain staging → balance → EQ → compression → space → automation → bus/mix-bus） SOP walkthrough for 音乐制作 / 混音.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="音乐制作 / 混音"
WORKFLOW="Mixing（gain staging → balance → EQ → compression → space → automation → bus/mix-bus）"

usage() {
  cat <<EOF
mixing-gain-staging-balance-eq-c.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./mixing-gain-staging-balance-eq-c.sh             # interactive
  ./mixing-gain-staging-balance-eq-c.sh --dry-run
  ./mixing-gain-staging-balance-eq-c.sh --json
  ./mixing-gain-staging-balance-eq-c.sh --explain
  ./mixing-gain-staging-balance-eq-c.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Mixing（gain staging → balance → EQ → compression → space → automation → bus/mix-bus）" 工作流。

一句话: 把编辑定稿的多轨平衡、塑形、布空间，做成一版有冲击力又服务歌的成品混音 —— 行业最核心、语料最厚、最易蒸 + CLI 化的 workflow。核心顺序：先 gain staging 与平衡，后逐元素塑形（EQ/压缩/空间），再自动化与总线胶水。(evidence: [T03-S001, T03-S003, T03-S007])

入门 SOP 共 7 步, 失败模式自检 4 项。

相关心智模型:
  • 服务歌优先于服务技术 (serve the song): 技术、音色、个人风格全都服从于"这首歌要表达什么"——好不好的最终裁判是情绪与歌本身，不是参数表（"if it sounds good, it is good"）。
  • 减法优先 / 每个处理都要能说出理由 (less but knowing why): 默认不处理；做得太多而非太少是这一行最常见的病——加任何东西（轨/EQ/压缩/响度）之前，先确认能不能减、不加，且每一次处理都要能讲出"我为什么这么做"。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**gain staging + 路由 + 静态平衡（balance）**: 整理增益结构、建分组 bus（鼓/人声/乐器/FX aux）、用推子做静态平衡，先让\"歌\"在没有任何处理下就基本成立。跳过 → 一上来狂加插件，却连基本响度关系都不对，越修越乱（Senior：balance 是混音第一性）。(evidence: [T03-S001])"
  "**reference track A/B（响度匹配）**: 选商业 reference，**响度匹配后** A/B，校准自己的房间与耳朵。跳过 → 被房间谎言/耳疲劳骗，混出在别处听垮的 mix。(evidence: [T03-S001], reference T04 core-concept)"
  "**EQ（减法优先）**: 先减问题频段（mud 200-500/harsh 2-5k/boxy 300-600），清出空间，再按需小幅加色；用动态 EQ/soothe 压共振。跳过 → 频段打架、糊/刺耳，靠音量推也推不清。(evidence: [T03-S001], subtractive T04)"
  "**compression（动态）+ 并行压缩**: 用 1176/LA-2A/Pro-C 控动态，需要\"加厚不压瞬态\"时上**并行压缩**（NY compression：干声 + 重压副本并行）。跳过 → 动态失控（人声忽大忽小）或一压就糊、瞬态没了。(evidence: [T03-S003], 并行 T02-S019)"
  "**space（reverb/delay）**: 用混响/延时建立深度与前后景（Valhalla 等），近的干、远的湿。跳过 → 混音平、贴脸、没有空间纵深（Gibson 3D：混响=深度）。(evidence: [T03-S001], 空间 T02-S011)"
  "**automation（自动化）**: 写音量/效果随时间变化（副歌推人声、桥段开混响），让混音\"活\"且全程清晰。跳过 → 静态混音里人声在某些句子被淹、能量起伏丢失。"
  "**bus / mix-bus 处理（glue）**: 总线轻压（SSL bus comp \"胶水\"）+ 可选总线 EQ/饱和，让全混抱团；print 成品。跳过 → 各元素\"各唱各的\"，缺整体凝聚感（glue）。(evidence: [T03-S003])"
)
declare -a FAILURE_MODES=(
  "**跳过平衡直接堆处理**: 触发原因 = 急着 \"make it sound pro\" 狂加插件。**CLI 化暗示**: 检查项「在加任何 EQ/压缩前，光用推子的静态平衡能不能让歌成立？如果不能，先调平衡」。"
  "**没响度匹配就 A/B reference**: 触发原因 = 直接切 reference，更响的总显得更好 → 误判。**CLI 化暗示**: 检查项「A/B reference 时是否已经把两者响度匹配（gain-match）？」。"
  "**到处加 EQ 不做减法**: 触发原因 = 哪里不够就 boost，越加越糊/刺耳。**CLI 化暗示**: 检查项「这次 EQ 是在减问题，还是在加色？能不能先减出空间再说？」。"
  "**只在大监听大声听，不查 mono/小系统/低音量**: 触发原因 = 单一聆听环境 + 大声 = 自我欺骗。**CLI 化暗示**: 检查项「折成 mono 还成立吗？过手机/车载/耳机听过吗？降到对话音量平衡还对吗？」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "mixing-gain-staging-balance-eq-c-walkthrough"
fi
