#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for DevOps 与 SRE.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="DevOps 与 SRE"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 可靠性目标与错误预算现状
  9.2 部署/交付管线成熟度 (DORA 四指标)
  9.3 可观测性覆盖与告警可用性
  9.4 事件/on-call 健康度与复盘文化
  9.5 基础设施与变更安全 (IaC / state / 回滚)
  9.6 平台/认知负荷与团队拓扑
  9.7 成本/容量与供应链安全

背后的心智模型:
  • 错误预算思维 — 可靠性是产品决策, 不是技术债; 100% 是错误的目标: 可靠性不是越高越好 — `error budget = 1 - SLO` 是一笔可花的预算, 它把"该发功能还是修可靠性"从情绪/道德争论变成 dev/SRE/产品三方共享的数字决策; 盲目追 100
  • 小批量高频部署 > 少发布 (反直觉) — 速度与稳定不是 trade-off: 直觉是"少发布就少出事", 但 DORA 用 23,000+ 受访者的统计学证明这是错的 — 低部署频率 = 大批量变更 = 更高 change failure rate + 更难定位; elite 
  • 无指责复盘 — 没有单一 root cause, 只有贡献因素; blameless ≠ 无问责: 复杂系统的故障从不是单一根因 + 单个人犯错, 而是多个本身不足以致灾的贡献因素叠加; 复盘的目的是从系统里榨出最大学习, 不是找人背锅 — 因为指责个人 = 工程师下次隐藏真相 = 下次故障更严重;

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "可靠性目标与错误预算现状"
  "部署/交付管线成熟度 (DORA 四指标)"
  "可观测性覆盖与告警可用性"
  "事件/on-call 健康度与复盘文化"
  "基础设施与变更安全 (IaC / state / 回滚)"
  "平台/认知负荷与团队拓扑"
  "成本/容量与供应链安全"
)
declare -a DIM_QUESTIONS=(
  "核心服务是否有 user-facing SLI + SLO + error budget policy; SLI 是 symptom (成功率/p99) 还是 cause (CPU); SLA (对客户合同) 与内部 SLO 的关系; 是否有\"烧光怎么办\"的强制动作; 是否在追 100% / 拍脑袋 99.999%; budget 是否真驱动 dev/SRE 决策还是装饰。"
  "部署频率 / 变更前置时间 / 变更失败率 / 恢复时间 (MTTR) 四指标现状; 是 trunk-based 小批量还是长命分支大合并; 制品是否不可变 (非 latest); 有无自动化测试金字塔门禁 + 渐进式发布 (canary/blue-green) + 自动回滚 + feature flag (deploy ≠ release); 四指标是否被当个人 KPI (Goodhart)。"
  "是 monitoring (预设 dashboard) 还是有 observability (能查 unknown-unknowns); RED/USE 方法是否落地; metrics+logs+traces 三信号是否齐 + 结构化日志 + trace 串联; instrument 是否绑死厂商 SDK (vs OTel 中立); 仪表盘是围绕 user journey 还是堆主机指标; 告警是 symptom/SLO burn 还是 cause; 告警是否 actionable (有无 alert fatigue / 长期静音); telemetry 成本 (custom metrics 基数爆炸?)。"
  "有无 IC 制 + SEV 定级 + runbook + status page; on-call 轮值是否可持续 (follow-the-sun? 告警量? 周末被毁?); 战时是否\"先止血不 fix-and-learn\"; 复盘是否 blameless (找贡献因素还是背锅? action 带 owner 闭环?); blameless 是否被误读为\"没人负责\"; 是否从事件学习 (LFI) 还是只算 MTTR。"
  "基础设施是 IaC 声明式还是 ClickOps 手改; state 是否远程加锁加密 (vs 本地/进 git/明文密钥); apply 前是否 plan review (尤其 destroy); 有无 policy-as-code 门禁 + drift 检测; 是 GitOps (pull reconcile) 还是 CIOps (push); 部署是否不可变 + 可回滚 + 有 kill switch。"
  "有无孤立\"DevOps 团队\"/\"DevOps 工程师\"夹在中间制造筒仓; 平台是否当产品做 (golden path / paved road / 自助 IDP) 还是强制管控; 产品团队是否 you-build-it-you-run-it; 团队认知负荷是否超载 (职责无限扩); 是否 resume-driven (小团队套大厂 K8s+mesh+multi-cloud); 工具/平台是否匹配团队规模与能力。"
  "云成本可见性 + 单位经济学 + rightsizing (vs 长期超配); 可观测性账单是否失控 (Datadog custom metrics); 容量规划是否有 headroom (vs 等 OOM 才扩); 有无负载管理 (load shedding/限流/熔断/优雅降级); 供应链安全 (SBOM/SLSA/签名/依赖扫描); 备份是否验证恢复 (RTO/RPO); 密钥管理 (Vault vs 明文)。"
)
declare -a DIM_SOURCES=(
  "现有 SLO dashboard (Grafana/Datadog) + error budget policy 文档 + SLA 合同条款 + 询问\"上次 budget 烧光发生了什么\"; 对照 Google SRE Book Ch3-4 + Implementing SLOs (Hidalgo) + Art of SLOs workshop。"
  "CI/CD 配置 (GitHub Actions/GitLab CI/Argo) + 部署日志/制品库 + 询问\"上次回滚怎么做的、多久\" + DORA 自评 (dora.dev) + 对照 Accelerate / Continuous Delivery。"
  "Prometheus/Grafana/Datadog/Honeycomb 配置 + 告警规则库 + 询问\"上次半夜被 page 是为什么、能做什么\" + 账单 (Datadog custom metrics 占比) + 对照 Observability Engineering + RED/USE 原文。"
  "PagerDuty/Opsgenie 排班 + 历史 postmortem 文档 + incident channel 记录 + 询问\"上次 SEV 谁是 IC、复盘怎么开的、action 闭环了吗\" + on-call 工程师访谈 (burnout 信号) + 对照 PagerDuty Incident Response + How Complex Systems Fail。"
  "Terraform/OpenTofu/Pulumi 代码 + state backend 配置 + CI 的 plan/apply 流程 + GitOps 工具 (Argo CD/Flux) + 询问\"上次误改/误删基础设施怎么恢复的\" + 对照 Terraform Up & Running + IaC 变更 SOP。"
  "组织架构图 + 团队职责文档 + IDP/Backstage 有无 + 询问\"发布是谁负责、平台团队提供什么自助能力\" + 工具栈复杂度 vs 团队规模 + 对照 Team Topologies。"
  "云账单 + FinOps 工具 (OpenCost/Cost Explorer) + 容量 dashboard + CI 安全扫描 (Trivy/Dependabot) + 备份恢复演练记录 + 询问\"上次验证备份恢复是什么时候\" + 对照 AWS Builders' Library + SLSA 框架。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "SLO 覆盖清单 (哪些服务有/无) + SLI 质量评估 (symptom vs cause) + error budget policy 有效性 (有强制动作? 真执行?) + 100%-追求 / vanity-SLI 红旗清单 + 第一份/改进 SLO 建议。"
  "DORA 四指标当前估值 + performer 分层 (elite/high/medium/low) + 管线 gap (无门禁?无 canary?无自动回滚?latest tag?) + \"想少发布\"的反模式红旗 + 小批量化改进路径。"
  "可观测性成熟度 (monitoring vs observability) + 三信号覆盖 gap + 告警 actionable 率评估 + alert fatigue 红旗 + 厂商锁定风险 (instrument SDK 绑定?) + telemetry 成本异常 + OTel 迁移建议。"
  "事件流程成熟度 (IC/SEV/runbook 有无) + on-call 可持续性评估 (轮值/告警量/补偿) + 复盘文化评级 (blameless? action 闭环率?) + alert fatigue + burnout 红旗 + 伦理风险 (on-call 当个人韧性问题?) + 改进建议。"
  "IaC 覆盖率 (vs ClickOps) + state 安全评估 (远程?加密?加锁?进 git?) + plan-review 门禁有无 + GitOps vs CIOps 判定 + 危险操作面红旗 (tfstate 明文密钥/无 plan review/手改控制台) + state 安全纵深建议。"
  "团队拓扑诊断 (有无 DevOps 筒仓反模式) + 平台成熟度 (产品化? golden path?) + 认知负荷评估 (超载?) + resume-driven / 过度工程红旗 (\"真的需要 K8s 吗\") + 团队拓扑重构建议。"
  "成本健康度 (账单异常? observability tax?) + 容量规划评估 (headroom? rightsizing?) + 负载管理 gap (无限流/熔断?) + 供应链成熟度 (SBOM/SLSA 等级) + 备份恢复红旗 (验证过吗?GitLab 2017 教训) + 韧性模式建议。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
