#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for 青少年心理健康教育.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="青少年心理健康教育"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 6 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 6 条规则:
  • 如果 学生出现自伤/自杀信号 → 则 : 立即启用 C-SSRS 标准化评估 + 通知家长 + 联系 988 生命线,绝不独自判断风险等级。案例: 2023 
  • 如果 要选择 SEL 课程 → 则 : 先查 CASEL Program Guide 循证评级,拒绝没有 RCT 支持的商业课程。案例: Second St
  • 如果 筛查发现高风险学生 → 则 : 筛查≠诊断,必须由临床专业人员(非学校辅导员)确认。案例: Panorama Education 平台的筛查报告明确
  • 如果 教师反映某班级情绪问题集中 → 则 : 先排查环境因素(校园欺凌/教师关系/课业负担),再考虑个体因素。案例: PBIS 框架强调先改环境再改行为(T06-
  • 如果 发现学生遭受虐待/忽视 → 则 : 启动强制报告义务(mandatory reporting),保密权不覆盖此项,记录保留供执法/儿保部门调取。案例: 
  • 如果 需要评估 SEL/MH 项目效果 → 则 : 用前后测标准化量表(DESSA/SAEBRS)而非满意度调查,至少追踪一个完整学年。案例: Panorama Edu

相关心智模型:
  • 发展适配优先 — 青春期不是成人的缩小版: 青少年的大脑、认知和情绪发展处于独特阶段——前额叶皮层 25 岁前未完全成熟、杏仁核反应性高、同伴影响权重超越成人直觉——任何干预方案必须以发展阶段为锚点设计,而非照搬成人模型。
  • 预防优于治疗 — MTSS 三级金字塔: 心理健康教育的核心逻辑是三级预防——Tier 1 全员预防(SEL/心理课)覆盖约 80% 的学生、Tier 2 小组干预(针对筛查出的 at-risk 群体)覆盖约 15%、Tier 3 个别临床干

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "学生出现自伤/自杀信号"
  "要选择 SEL 课程"
  "筛查发现高风险学生"
  "教师反映某班级情绪问题集中"
  "发现学生遭受虐待/忽视"
  "需要评估 SEL/MH 项目效果"
)
declare -a RULE_ACTIONS=(
  ": 立即启用 C-SSRS 标准化评估 + 通知家长 + 联系 988 生命线,绝不独自判断风险等级。案例: 2023 年伊利诺伊州立法要求所有学校必须有书面自杀预防协议(T03-S005)"
  ": 先查 CASEL Program Guide 循证评级,拒绝没有 RCT 支持的商业课程。案例: Second Step 和 RULER 是 CASEL 高评级课程,大量学区采用(约业内估, 覆盖 30,000+ 学校, T02-S001)"
  ": 筛查≠诊断,必须由临床专业人员(非学校辅导员)确认。案例: Panorama Education 平台的筛查报告明确标注\"此为筛查结果非临床诊断\"(T02-S028)"
  ": 先排查环境因素(校园欺凌/教师关系/课业负担),再考虑个体因素。案例: PBIS 框架强调先改环境再改行为(T06-S001, T02-S013)"
  ": 启动强制报告义务(mandatory reporting),保密权不覆盖此项,记录保留供执法/儿保部门调取。案例: FERPA 和各州法律均要求教育工作者为强制报告人(T06-S010)"
  ": 用前后测标准化量表(DESSA/SAEBRS)而非满意度调查,至少追踪一个完整学年。案例: Panorama Education 提供从筛查到成效追踪的完整数据管线(T02-S028)"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
