#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for 投行并购.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="投行并购"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 保密性/规模/敏感度高 → 则 收窄竞价广度 (broad→limited→targeted→exclusive)，用分阶段信息闸 (teaser→ND
  • 如果 跨 HSR 阈值或 CFIUS 敏感 (跨境/critical tech) → 则 在谈判时**前置**反垄断 risk allocation (HOHW vs efforts standard、RTF 
  • 如果 用 AI 起草 (pitchbook/CIM/diligence) → 则 只当 first-draft 并强制人工 sign-off，且 live-deal/MNPI 数据**只用内部 wall

相关心智模型:
  • 三层价格——价值——成交价: 这行的人脑子里永远有三个数在打架——**内在价值** (DCF/现金流基本面) ⇄ **市场价格** (trading comps/情绪与动量) ⇄ **成交价** (含 control premiu
  • 价值创造 = 增长 × (ROIC − 资本成本): 价值只有一种创造方式——**以高于资本成本的回报率投资资本**；ROIC 低于资本成本时增长反而毁价，会计/财务工程/回购/EPS 目标都只是重新分配现金流，不创造价值 (conservation o

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "保密性/规模/敏感度高"
  "跨 HSR 阈值或 CFIUS 敏感 (跨境/critical tech)"
  "用 AI 起草 (pitchbook/CIM/diligence)"
)
declare -a RULE_ACTIONS=(
  "收窄竞价广度 (broad→limited→targeted→exclusive)，用分阶段信息闸 (teaser→NDA→CIM→IOI→data room→LOI) 当杠杆；granting exclusivity 即关闭拍卖"
  "在谈判时**前置**反垄断 risk allocation (HOHW vs efforts standard、RTF 大小) + \"fix-it-first\" 预备 divestiture，别等监管时钟在最坏时点炸掉交易"
  "只当 first-draft 并强制人工 sign-off，且 live-deal/MNPI 数据**只用内部 walled LLM**，公共 ChatGPT/Perplexity 是红线"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
