#!/usr/bin/env bash
# high-density-capacity-planning-8.sh — High-density capacity planning (80+ user dense office) ★ USER SCENARIO ★ SOP walkthrough for UBNT/UniFi 企业 Wi-Fi 工程.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="UBNT/UniFi 企业 Wi-Fi 工程"
WORKFLOW="High-density capacity planning (80+ user dense office) ★ USER SCENARIO ★"

usage() {
  cat <<EOF
high-density-capacity-planning-8.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./high-density-capacity-planning-8.sh             # interactive
  ./high-density-capacity-planning-8.sh --dry-run
  ./high-density-capacity-planning-8.sh --json
  ./high-density-capacity-planning-8.sh --explain
  ./high-density-capacity-planning-8.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "High-density capacity planning (80+ user dense office) ★ USER SCENARIO ★" 工作流。

一句话: When the office is ≥50 active clients per shared zone, you cannot do this by coverage intuition — capacity math drives AP count + placement + channel + Tx power. This IS the user's scenario (evidence: [T03-S001, T03-S002, T03-S008])

入门 SOP 共 12 步, 失败模式自检 10 项。

相关心智模型:
  • 容量优先, 覆盖次之 (Capacity-first, coverage second): 80 人密集办公的 Wi-Fi 瓶颈不是覆盖, 是同信道干扰 (CCI) — 加 AP 反而让网络更慢; 工程师先算 airtime budget, 后摆 AP.
  • Retry rate > RSSI (重试率比信号强度更能定位问题): 客户跟你说 "信号差", 你先要 retry % 和 channel utilization, 不要 RSSI — RSSI 满格但 retry 30% (业内估计 — CCI 阈值) 是 CCI /

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Estimate concurrent client count**: 80 ppl × 1.5-2 devices each = 120-160 active clients (peak); not all simultaneously transmitting — apply 30-50% concurrency factor → ~50-80 active radios per moment. Skip → AP undersizing (designed for 80 endpoints not 160)."
  "**Define throughput requirement per client**: typical office mix = 25 Mbps avg (Teams/Zoom video + cloud apps); voice-heavy = 1 Mbps but with strict latency; dense engineering = 50-100 Mbps. Skip → can't compute airtime budget."
  "**Calculate total airtime budget per band**: total demand = (clients × throughput); 5 GHz nominal capacity ~100-200 Mbps per AP under load (NOT PHY rate of 1.2 Gbps — apply 30-60% efficiency factor). Skip → over-/under-provisioning by 2x."
  "**Decide AP count per band** (vonNagy formula or rule-of-thumb): ~25 active 5 GHz clients per AP at 25 Mbps demand → 80 clients ÷ 25 = ~3-4 APs minimum 5GHz; oversize by 50-100% for conference room density → 6-8 APs. 2.4 GHz: 1 AP per 3-5 APs of 5 GHz (most APs disable 2.4). Skip → CCI from overprovision OR thrashing from underprovision."
  "**AP placement**: ceiling-mount, line-of-sight to most users, **even spacing** (~10-15m apart depending on attenuation), NOT clustered (e.g., NOT 4 APs above server room + 0 in open office). Skip → coverage holes + uneven CCI domain (evidence: [T03-S001] vonNagy + [T03-S007] Willie Howe System Builder)."
  "**Channel plan**:"
  "**Tx Power**: reduce from default Max — start at Medium (~14 dBm 5 GHz, ~11 dBm 2.4) and equalize across all APs to balance CCI domain. Skip → asymmetric Tx (Pitfall #1) + CCI."
  "**Min RSSI**: -75 to -78 dBm for U6/U7 series typical; -72 dBm if voice-heavy. UBNT-specific kick mechanism — test before going aggressive on production (evidence: [T03-S010, T03-S019]). Skip → sticky clients OR thrashing clients depending on direction."
  "**Band steering ON, fast roaming (802.11r) ON if clients support** — verify by client inventory; if there are Windows XP / old Android, 11r breaks them. Skip → sticky 2.4 GHz clients dragging capacity down."
  "**PoE switch capacity check**: U7 series often 25-30W per AP → 8 APs × 30W = 240W PoE budget — need ≥24-port PoE++ switch with appropriate budget. Skip → AP boots in reduced-radio mode (Track 06 PoE entry)."
  "**Backhaul / uplink validation**: each AP should have ≥1 Gbps wired uplink; aggregate backbone to controller ≥10 Gbps if >6 APs streaming video. Skip → backhaul bottleneck masquerading as Wi-Fi problem."
  "**Validation**: WiFiman walk all zones — RSSI ≥ -67 dBm at every desk, ≥ -72 dBm in conference rooms; iperf3 from multiple zones — measured throughput ≥ designed 25 Mbps per client × concurrent factor; Wireshark sanity check on 4-way handshake + roaming. Skip → silent failures until first sales demo fails."
)
declare -a FAILURE_MODES=(
  "**F1**: Assume PHY rate (1.2 Gbps) = real throughput; design for \"Wi-Fi 6 can do 9.6 Gbps\" — actual 5 GHz capacity is 100-200 Mbps per AP. Undersize APs by 4-6x. Discovered at first all-hands meeting."
  "**F2**: Enable 80 MHz width 5 GHz in a dense scenario without DFS support → only 1-2 non-overlapping channels → CCI catastrophe + auto-channel-thrashing (evidence: Track 02 Pitfall #1, #3; [T03-S006] Channel Map)."
  "**F3**: Cluster APs in one corner (e.g., where IT closet is) thinking \"central placement\" — actual coverage drops on far end, dense central CCI. Common in retrofit scenarios where cabling existed."
  "**F4**: Forget PoE budget; deploy 8 U7 Pro on a 12-port PoE+ switch with 60W total budget → APs randomly reduce radios → flaky network (evidence: Track 06 PoE entry)."
  "**Sources**:"
  "[Primary] vonNagy Revolution Wi-Fi capacity-first (T03-S001, collected 2026-06-02)"
  "[Primary] iFeelTech 40-75+ employee blueprint (T03-S008)"
  "[Primary] Willie Howe UniFi WiFi Channel Map (T03-S007)"
  "[Secondary] NETGEAR HD best practices WP citing vonNagy (T03-S002)"
  "[Reference] CWDP capacity-first doctrine (Track 04 canon)"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "high-density-capacity-planning-8-walkthrough"
fi
