#!/usr/bin/env bash
# roaming-optimization-sticky-clie.sh — Roaming optimization (sticky clients / slow roam) SOP walkthrough for UBNT/UniFi 企业 Wi-Fi 工程.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="UBNT/UniFi 企业 Wi-Fi 工程"
WORKFLOW="Roaming optimization (sticky clients / slow roam)"

usage() {
  cat <<EOF
roaming-optimization-sticky-clie.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./roaming-optimization-sticky-clie.sh             # interactive
  ./roaming-optimization-sticky-clie.sh --dry-run
  ./roaming-optimization-sticky-clie.sh --json
  ./roaming-optimization-sticky-clie.sh --explain
  ./roaming-optimization-sticky-clie.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Roaming optimization (sticky clients / slow roam)" 工作流。

一句话: Voice/video session drops or stutters crossing an AP boundary; clients "stick" to a far AP at -85 dBm instead of jumping to a closer one at -55 dBm (evidence: [T03-S019, T03-S020, T03-S010])

入门 SOP 共 6 步, 失败模式自检 8 项。

相关心智模型:
  • 容量优先, 覆盖次之 (Capacity-first, coverage second): 80 人密集办公的 Wi-Fi 瓶颈不是覆盖, 是同信道干扰 (CCI) — 加 AP 反而让网络更慢; 工程师先算 airtime budget, 后摆 AP.
  • Retry rate > RSSI (重试率比信号强度更能定位问题): 客户跟你说 "信号差", 你先要 retry % 和 channel utilization, 不要 RSSI — RSSI 满格但 retry 30% (业内估计 — CCI 阈值) 是 CCI /

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Inventory clients**: list device types (iOS / Android / Windows / macOS / Wi-Fi calling phones / IoT). 11r support varies — some old Android breaks with 11r enabled. Skip → enable 11r globally, break user devices, revert under fire."
  "**Enable 802.11k**: AP gives client neighbor list. Lower-risk than 11r. Skip → clients have no idea of better APs nearby, decide based on RSSI alone (slowly)."
  "**Enable 802.11v BSS Transition Management**: AP can politely ask client to move. Wide support. Skip → AP can only kick or wait."
  "**Enable 802.11r Fast Transition where supported**: pre-cached PMK-R1 enables sub-50 ms handoff (vs ~500 ms full re-association + 4-way). Risk: legacy clients break. Skip → voice handoff is 200-500 ms = clipped audio."
  "**Tune Min RSSI** (UBNT-specific): -75 dBm typical data, -72 dBm voice; this kicks sticky clients to roam. Test gradually. Skip → sticky clients OR thrashing clients."
  "**Validate**: walk a path covering multiple APs while in a Teams/Zoom call; capture Wireshark on monitor station to log reassoc events; measure handoff time (target < 100 ms, ideal < 50 ms with 11r). Skip → ship it broken."
)
declare -a FAILURE_MODES=(
  "**F1**: Enable 11r globally without client inventory; old Android devices fail association silently — looks like \"Wi-Fi broken\" to user. Roll back under pressure, lose trust."
  "**F2**: Set Min RSSI aggressively (-65 dBm) thinking \"force roaming\" — clients in distant desks get kicked with no better AP available, drop completely (Pitfall #5 in Track 02)."
  "**F3**: Declare roaming \"fixed\" based on AP showing client moved — but didn't measure actual handoff latency. Voice call still clips. Customer reports back."
  "**Sources**:"
  "[Primary] CWNP 11k/v/r blog explainer (T03-S019)"
  "[Primary] Microsoft Learn 11k/v/r reference (T03-S020)"
  "[Primary] UBNT Min RSSI guide (T03-S010)"
  "[Reference] Heavy Wireless roaming episodes (T03-S012)"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "roaming-optimization-sticky-clie-walkthrough"
fi
