#!/usr/bin/env bash
# site-survey-post-install-validat.sh — Site survey + post-install validation SOP walkthrough for UBNT/UniFi 企业 Wi-Fi 工程.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="UBNT/UniFi 企业 Wi-Fi 工程"
WORKFLOW="Site survey + post-install validation"

usage() {
  cat <<EOF
site-survey-post-install-validat.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./site-survey-post-install-validat.sh             # interactive
  ./site-survey-post-install-validat.sh --dry-run
  ./site-survey-post-install-validat.sh --json
  ./site-survey-post-install-validat.sh --explain
  ./site-survey-post-install-validat.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Site survey + post-install validation" 工作流。

一句话: Predictive design alone is a model — it must be validated against reality with on-site survey before, during, and after install (evidence: [T03-S003, T03-S014])

入门 SOP 共 7 步, 失败模式自检 8 项。

相关心智模型:
  • 容量优先, 覆盖次之 (Capacity-first, coverage second): 80 人密集办公的 Wi-Fi 瓶颈不是覆盖, 是同信道干扰 (CCI) — 加 AP 反而让网络更慢; 工程师先算 airtime budget, 后摆 AP.
  • Retry rate > RSSI (重试率比信号强度更能定位问题): 客户跟你说 "信号差", 你先要 retry % 和 channel utilization, 不要 RSSI — RSSI 满格但 retry 30% (业内估计 — CCI 阈值) 是 CCI /

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Floorplan import + scale**: import floor PDF/DWG into Ekahau / Hamina, set scale. Skip → simulated coverage doesn't map to real distances."
  "**Predictive design**: drop APs in expected positions, apply attenuation modeling (drywall, glass, concrete), generate RSSI / SNR / capacity heatmaps. Skip → no design baseline to validate against."
  "**AP-on-a-stick (optional, recommended for new buildings)**: take 1 AP on a tripod, place at planned positions, walk-survey using Sidekick / WLAN Pi → calibrate predictive model with real attenuation values. Skip → predictive may be off by 10+ dB in unusual building materials."
  "**Install (Workflow W1 step 4 inherits here)**."
  "**Passive walk-through survey**: walk all areas with Sidekick / WLAN Pi connected to laptop running Ekahau / Hamina, capture passive measurements (RSSI, SNR, channel utilization, neighboring BSSIDs). Skip → never know if signal matches design."
  "**Active survey (target SSID)**: same walk but actively associated to target SSID + running iperf3 → measure end-to-end throughput per location. Skip → RSSI ok but throughput tanks (e.g., from CCI), undetected."
  "**Compare to predictive + write report**: side-by-side maps, document deviations, recommend tuning if needed. Skip → no record of design vs reality gap."
)
declare -a FAILURE_MODES=(
  "**F1**: Run only predictive, never validate — discover real-world dead zone after move-in (e.g., previously-unknown rebar wall absorbs signal)."
  "**F2**: Validate only with WiFiman from a phone — phone antennas are poor, gives misleading RSSI compared to laptop / Sidekick (Track 02 Pitfall #2)."
  "**F3**: Survey at noon Saturday when office is empty — capacity behavior nothing like Monday 10am. Real validation requires loaded testing."
  "**Sources**:"
  "[Primary] Ekahau active survey best practices (T03-S003)"
  "[Primary] Ekahau AI Pro product page (T03-S014)"
  "[Reference] CWDP / Mackenzie methodology (T03-S027)"
  "[Reference] iFeelTech blueprint variations (T03-S008)"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "site-survey-post-install-validat-walkthrough"
fi
