#!/usr/bin/env bash
# wpa3-security-hardening-dragonbl.sh — WPA3 security hardening + Dragonblood-aware audit SOP walkthrough for UBNT/UniFi 企业 Wi-Fi 工程.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="UBNT/UniFi 企业 Wi-Fi 工程"
WORKFLOW="WPA3 security hardening + Dragonblood-aware audit"

usage() {
  cat <<EOF
wpa3-security-hardening-dragonbl.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./wpa3-security-hardening-dragonbl.sh             # interactive
  ./wpa3-security-hardening-dragonbl.sh --dry-run
  ./wpa3-security-hardening-dragonbl.sh --json
  ./wpa3-security-hardening-dragonbl.sh --explain
  ./wpa3-security-hardening-dragonbl.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "WPA3 security hardening + Dragonblood-aware audit" 工作流。

一句话: Enabling WPA3 in the GUI is not enough — must verify clients don't downgrade to WPA2 + check PMF is mandatory + run hostapd-mana rogue-AP test (evidence: [T03-S018, T03-S022, T03-S030])

入门 SOP 共 6 步, 失败模式自检 10 项。

相关心智模型:
  • 容量优先, 覆盖次之 (Capacity-first, coverage second): 80 人密集办公的 Wi-Fi 瓶颈不是覆盖, 是同信道干扰 (CCI) — 加 AP 反而让网络更慢; 工程师先算 airtime budget, 后摆 AP.
  • Retry rate > RSSI (重试率比信号强度更能定位问题): 客户跟你说 "信号差", 你先要 retry % 和 channel utilization, 不要 RSSI — RSSI 满格但 retry 30% (业内估计 — CCI 阈值) 是 CCI /

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Enable WPA3 in UniFi Network App per SSID**: choose WPA3-Personal (SAE) or WPA3-Enterprise; for SMB 80-person, Personal is fine with strong passphrase + 802.1X for sensitive VLANs. Skip → still on WPA2, exposed to offline dictionary attacks."
  "**Set PMF to Mandatory** (not Optional) on WPA3 SSIDs; check WPA3 mixed-mode (WPA2/3 transition) only as temp during rollout — eventually disable WPA2 backward compatibility. Skip → PMF spoof / deauth attack vector remains."
  "**Test client compatibility**: walk through device inventory — iOS / modern Android / Win 10+ / macOS support WPA3; old IoT may not. Use dedicated \"IoT\" SSID with WPA2-PSK + isolated VLAN. Skip → IoT devices fail silently, support tickets."
  "**Run hostapd-mana rogue-AP test**: simulate a rogue AP advertising the same SSID with WPA2 — verify clients DO NOT silently fall back. Skip → Dragonblood-style downgrade still possible."
  "**Run nmap from guest VLAN → internal**: verify VLAN isolation actually blocks (port-scan should fail), not just configured. Skip → \"WPA3 secure SSID\" leaking to corp via misconfigured VLAN."
  "**Document + sign-off**: report shows WPA3 enforced, PMF mandatory, fallback test passed, VLAN pen-test passed. Skip → audit fails, regulator / customer not satisfied."
)
declare -a FAILURE_MODES=(
  "**F1**: Enable WPA3 in GUI, declare \"we're WPA3 now\" without running fallback test — silent downgrade via mixed-mode still possible. Discovered when an auditor runs hostapd-mana."
  "**F2**: Set PMF Optional thinking \"for compatibility\" — defeats the whole point. PMF Optional is functionally equivalent to PMF off for attackers."
  "**F3**: Forget to test IoT segment — Apple HomeKit / Google Cast / Sonos devices silently fall off network, customer reports \"smart home broken since last week.\""
  "**F4**: Assume \"WPA3 = no need to think about CVEs\" — wrong; SAE implementations have their own CVE stream (evidence: [T03-S018])."
  "**Sources**:"
  "[Primary] Vanhoef Dragonblood (T03-S018)"
  "[Primary] Vanhoef FragAttacks (T03-S022)"
  "[Primary] Wi-Fi Alliance WPA3 spec hub (T03-S030)"
  "[Reference] nmap official docs (T03-S029)"
  "[Reference] CWSP material (Track 04)"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "wpa3-security-hardening-dragonbl-walkthrough"
fi
