#!/usr/bin/env bash
# messaging-message-testing-with-r.sh — 用真实买家测 messaging (Message testing with real buyers) SOP walkthrough for 产品营销 (PMM, Product Marketing) — 拥有「产品如何被定位 / 表达 / 发布 / 卖进市场」的从业者认知操作系统: 是产品 / 销售 / 市场 / 客户之间的连接组织, 负责把产品能力翻译成市场价值, 并把市场声音带回产品。覆盖 (a) 定位与差异化 (April Dunford 「刻意选择语境」框架 + 竞争性替代方案 + 卖价值不卖功能 + 选择「让你优势成立的市场参照系」, 对照 Ries & Trout 经典「定位是占领心智」), (b) 信息传递与叙事 (messaging 层级 / 信息屋 + 价值主张 + 收益导向 vs 战略叙事「换框架」Andy Raskin + 表达清晰度 Emma Stratton / Punchy + 初创 homepage 定位 FletchPMM), (c) 进入市场 (GTM) 策略与产品发布 (发布分级 T1/T2/T3 + 发布流程与跨职能编排 + GTM 打法 PLG vs SLG vs 混合 + 滩头细分选择), (d) 市场与竞争情报 (竞品分析 + battlecard 战卡 + 输赢分析 win/loss + 竞争赋能 Klue/Crayon/Clozd), (e) 买家与客户研究 (ICP 理想客户画像 + 买家 / 用户 persona + Jobs-to-be-Done 任务理论 Christensen/Moesta/Ulwick ODI + 客户之声 VoC + 用真实买家测信息 Wynter/Peep Laja), (f) 销售赋能 (战卡 + pitch / 销售 deck + 一页纸 + demo 叙事 + 异议处理 + 销售培训 + 内容采用率 — 你的产出只值销售实际用到的那部分), (g) 定价与打包 (价值定价 + 打包分层 + 《Monetizing Innovation》Ramanujam/Simon-Kucher + PLG 定价 — 常与产品 / 财务共担), (h) 细分与品类 (市场细分 + TAM/SAM/SOM + 技术采用生命周期与跨越鸿沟 Geoffrey Moore + 品类设计与叙事 Play Bigger / Christopher Lochhead — 稀有且昂贵, 不是默认选项), (i) 需求生成与内容协同 (campaign 信息 + 思想领导力 + 漏斗内容 TOFU/MOFU/BOFU + ABM 基于客户营销), (j) 分析师与影响者关系 (Gartner 魔力象限 + Forrester Wave + 分析师 briefing — To B 场景, 对 pay-to-play 影响诚实标注), (k) 客户营销与倡导 (参考客户 + case study + 评测站 G2/TrustRadius/Capterra 运营 + 社区), (l) PMM 运营与度量 (影响管道 + 赢率 + 发布采用率 + 信息穿透率 + 角色汇报线「向产品还是向市场」之争 + PMM 作为战略职能 vs 接单工具人陷阱); 跨 B2B SaaS (该学科重心) / B2C 消费 / 开发者 PLG / 平台产品。不含 产品管理 (PM 造产品 / 拥有 roadmap, PMM 拥有市场 — 相邻且极易混淆) / 增长 / 效果营销 / 付费投放 (平行学科) / 品牌 / 企业传播 / 公关为终点 / 需求生成为终点 (PMM 与之协同但不等同) / 平面设计 /「做 slide 和周边的团队」(PMM 抗争的接单工具人窄化) / 泛泛「市场营销」。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="产品营销 (PMM, Product Marketing) — 拥有「产品如何被定位 / 表达 / 发布 / 卖进市场」的从业者认知操作系统: 是产品 / 销售 / 市场 / 客户之间的连接组织, 负责把产品能力翻译成市场价值, 并把市场声音带回产品。覆盖 (a) 定位与差异化 (April Dunford 「刻意选择语境」框架 + 竞争性替代方案 + 卖价值不卖功能 + 选择「让你优势成立的市场参照系」, 对照 Ries & Trout 经典「定位是占领心智」), (b) 信息传递与叙事 (messaging 层级 / 信息屋 + 价值主张 + 收益导向 vs 战略叙事「换框架」Andy Raskin + 表达清晰度 Emma Stratton / Punchy + 初创 homepage 定位 FletchPMM), (c) 进入市场 (GTM) 策略与产品发布 (发布分级 T1/T2/T3 + 发布流程与跨职能编排 + GTM 打法 PLG vs SLG vs 混合 + 滩头细分选择), (d) 市场与竞争情报 (竞品分析 + battlecard 战卡 + 输赢分析 win/loss + 竞争赋能 Klue/Crayon/Clozd), (e) 买家与客户研究 (ICP 理想客户画像 + 买家 / 用户 persona + Jobs-to-be-Done 任务理论 Christensen/Moesta/Ulwick ODI + 客户之声 VoC + 用真实买家测信息 Wynter/Peep Laja), (f) 销售赋能 (战卡 + pitch / 销售 deck + 一页纸 + demo 叙事 + 异议处理 + 销售培训 + 内容采用率 — 你的产出只值销售实际用到的那部分), (g) 定价与打包 (价值定价 + 打包分层 + 《Monetizing Innovation》Ramanujam/Simon-Kucher + PLG 定价 — 常与产品 / 财务共担), (h) 细分与品类 (市场细分 + TAM/SAM/SOM + 技术采用生命周期与跨越鸿沟 Geoffrey Moore + 品类设计与叙事 Play Bigger / Christopher Lochhead — 稀有且昂贵, 不是默认选项), (i) 需求生成与内容协同 (campaign 信息 + 思想领导力 + 漏斗内容 TOFU/MOFU/BOFU + ABM 基于客户营销), (j) 分析师与影响者关系 (Gartner 魔力象限 + Forrester Wave + 分析师 briefing — To B 场景, 对 pay-to-play 影响诚实标注), (k) 客户营销与倡导 (参考客户 + case study + 评测站 G2/TrustRadius/Capterra 运营 + 社区), (l) PMM 运营与度量 (影响管道 + 赢率 + 发布采用率 + 信息穿透率 + 角色汇报线「向产品还是向市场」之争 + PMM 作为战略职能 vs 接单工具人陷阱); 跨 B2B SaaS (该学科重心) / B2C 消费 / 开发者 PLG / 平台产品。不含 产品管理 (PM 造产品 / 拥有 roadmap, PMM 拥有市场 — 相邻且极易混淆) / 增长 / 效果营销 / 付费投放 (平行学科) / 品牌 / 企业传播 / 公关为终点 / 需求生成为终点 (PMM 与之协同但不等同) / 平面设计 /「做 slide 和周边的团队」(PMM 抗争的接单工具人窄化) / 泛泛「市场营销」。"
WORKFLOW="用真实买家测 messaging (Message testing with real buyers)"

usage() {
  cat <<EOF
messaging-message-testing-with-r.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./messaging-message-testing-with-r.sh             # interactive
  ./messaging-message-testing-with-r.sh --dry-run
  ./messaging-message-testing-with-r.sh --json
  ./messaging-message-testing-with-r.sh --explain
  ./messaging-message-testing-with-r.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "用真实买家测 messaging (Message testing with real buyers)" 工作流。

一句话: Validate messaging variants with a panel of real target buyers — measure clarity, relevance, value, and differentiation — and iterate, instead of trusting internal opinion.

入门 SOP 共 5 步, 失败模式自检 0 项。

相关心智模型:
  • 定位是刻意选择的「参照系」, 不是描述你有什么: 定位的本质是**选择「让你的优势成立的市场参照系」**——先问「客户不买你, 会拿什么替代 (competitive alternatives)」, 从那个参照系反推你的独特价值; 经典派 (Ries
  • 客户「雇用」产品完成一个 job — 卖结果, 不卖功能: 客户不是「买产品」, 而是**「雇用 (hire)」一个产品来完成生活/工作里的某个 job** (Christensen 奶昔例); 所以 messaging 要讲「能帮你完成什么 + 取得什么 p

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Recruit / target the right buyers** — filter a B2B panel by job title and seniority so respondents match the actual ICP/persona (W6)."
  "**Submit the message to test** — paste a live URL or upload the copy/creative (homepage, value prop, headline variants), highlighting the sections you want granular feedback on."
  "**Test the message against the components** — Clarity (do they get it?), Relevance (does it matter to them?), Value (do they want it?), Differentiation (why you?), and Brand."
  "**Read the playback** — check whether buyers can restate what you do in their own words and where they get confused; that confusion is the signal."
  "**Iterate** — revise the weak components and re-test variants until clarity and value land; then promote the winner to web/sales."
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "messaging-message-testing-with-r-walkthrough"
fi
