#!/usr/bin/env bash
# topic-1.sh — 用户 决策助手 for 产品设计 / UX 设计.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="产品设计 / UX 设计"
TOPIC="用户"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 用户 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 方案争执基于意见而非数据/观察 → 则 用一次折扣可用性测试（5 人定性）或拉行为数据来裁决，而不是比谁嗓门大或职级高——"opinions are not d
  • 如果 有人提"加个新功能" → 则 先问"它解决用户哪个 job（JTBD）、是 discovery 验证过的 opportunity 吗"，否则警惕 fe
  • 如果 用户不知道某元素可点/怎么操作 → 则 问题是缺 signifier（可感知线索）而非缺功能，先补线索而不是加说明文字。案例：用户找不到隐藏在汉堡菜单里的核心入
  • 如果 要不要打破平台惯例 → 则 默认遵循 Jakob's Law，破例前确认"创新收益 > 用户重新学习成本"且破例可学习。案例：把"返回"放到非常规位

相关心智模型:
  • 行为 > 自陈（You are not the user）: 设计决策必须基于**观察到的真实行为**，而非设计师/利益相关者的意见、也不是用户口头说的偏好——"你不是用户"，"opinions are not data"。 (figures: Krug / H
  • 认知负荷最小化（Don't Make Me Think）: 好设计让"正确操作显而易见"，把思考成本从用户身上移走——识别（recognition）优于回忆（recall），扫读优于阅读，满意即止（satisficing）。 (figures: Krug / 

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "方案争执基于意见而非数据/观察"
  "有人提\"加个新功能\""
  "用户不知道某元素可点/怎么操作"
  "要不要打破平台惯例"
)
declare -a RULE_ACTIONS=(
  "用一次折扣可用性测试（5 人定性）或拉行为数据来裁决，而不是比谁嗓门大或职级高——\"opinions are not data\"。案例：stakeholder 坚持\"用户喜欢轮播图 banner\"，一轮真人测试常发现没人点第 2 屏，用行为数据收束争论"
  "先问\"它解决用户哪个 job（JTBD）、是 discovery 验证过的 opportunity 吗\"，否则警惕 feature creep。案例：利益相关者要求加\"AI 助手\"按钮，用机会树倒推发现没有对应的用户问题，砍掉避免功能膨胀"
  "问题是缺 signifier（可感知线索）而非缺功能，先补线索而不是加说明文字。案例：用户找不到隐藏在汉堡菜单里的核心入口，解法是把入口显性化，而非加一行\"点这里\"提示"
  "默认遵循 Jakob's Law，破例前确认\"创新收益 > 用户重新学习成本\"且破例可学习。案例：把\"返回\"放到非常规位置以求独特，实测增加误操作，回退到惯例位置"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
