#!/usr/bin/env bash
# topic-1.sh — —— 决策助手 for 研学营地教育.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="研学营地教育"
TOPIC="——"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 —— 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 一个方案没有可测学习目标 + 没有反思/复盘环节 + 没有评价或公开成果 → 则 它是旅游不是研学——立项即主动附「本项目对应哪条课标 / 综合实践活动方式（考察探究/社会服务/设计制作/职业体验）」的
  • 如果 还没拿到合规资格（B 端报批未通过 / 未进服务机构名录） → 则 先过这道闸再启动商业动作——**先批后招、先名录后投标**，绝不先收费再补报批、绝不无名录硬投标、绝不中标后转包给名录外
  • 如果 用 AI 研学方案/手册/线路生成器 → 则 只当**草稿层**，必用 Kolb/PBL/UbD 人工把关教育性与安全后才成品——AI 生成易堆砌景点、缺反思与评价（
  • 如果 一期营/一个项目办得满意度高 → 则 立即把口碑转成**复购与转介绍引擎**（闭营典礼设家长参与+成果可晒+老带新优惠+营辅持续维系群），而不是让它停在偶然—

相关心智模型:
  • 「研学是课程不是行程」——教育属性优先: 研学/营地的本体是**课程**（有学习目标—实施—评价闭环），不是**行程**（景点+讲解词）；从业者用「教育本质」作为对抗旅游化、获客化、速成化的立场锚与对客叙事。
  • 体验—反思闭环（Kolb 圈）——「经验无反思即旅游」: 学习不是「去过/动手过」就发生，而要走完「具体经验→反思观察→抽象概念化→主动实践」的圈；**「反思/复盘」环节的有无，是研学区别于旅游的命门工序**。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "一个方案没有可测学习目标 + 没有反思/复盘环节 + 没有评价或公开成果"
  "还没拿到合规资格（B 端报批未通过 / 未进服务机构名录）"
  "用 AI 研学方案/手册/线路生成器"
  "一期营/一个项目办得满意度高"
)
declare -a RULE_ACTIONS=(
  "它是旅游不是研学——立项即主动附「本项目对应哪条课标 / 综合实践活动方式（考察探究/社会服务/设计制作/职业体验）」的**对照表**自证教育性，否则过不了监管核查、家长验收、B 端评标"
  "先过这道闸再启动商业动作——**先批后招、先名录后投标**，绝不先收费再补报批、绝不无名录硬投标、绝不中标后转包给名录外机构"
  "只当**草稿层**，必用 Kolb/PBL/UbD 人工把关教育性与安全后才成品——AI 生成易堆砌景点、缺反思与评价（典型「只游不学」），当成品=把不合规的产品卖得更快"
  "立即把口碑转成**复购与转介绍引擎**（闭营典礼设家长参与+成果可晒+老带新优惠+营辅持续维系群），而不是让它停在偶然——C 端单位经济的命门是把单期口碑沉淀成复购资产，否则下期又从零买量、获客成本压垮利润"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
