#!/usr/bin/env bash
# topic-2.sh — 安全 决策助手 for 研学营地教育.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="研学营地教育"
TOPIC="安全"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 安全 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 三案（活动方案/安全预案/应急预案）+ 三层险栈（校方责任险+旅行社责任险+人身意外险）+ 人员配比（研学指导≥1:30 → 则 无论课程多漂亮、SaaS 多先进、报价多有竞争力，都**不准成行 / 不准投标**——这是先于一切设计与选型的硬前置门
  • 如果 是新基地 / 换季 / 雨季 / 新增高风险项目（涉水/高海拔/交通节点） → 则 绝不凭图册或招商话术决策，必**实地踩点 + 标准核查清单逐项核**（安全设施/容量/食宿/应急/医疗 + 满员峰值动线
  • 如果 机构营期少、预算有限、刚起步（单一夏令营级） → 则 默认用**通用工具拼装**（微信小程序+金数据/腾讯收集表做报名+健康信息+监护授权+微信支付；需线上课/分销再叠加小鹅
  • 如果 在招聘或培训研学导师 / 营地辅导员 → 则 按**研学指导师四维能力（态度/知识/技能/发展）+ 课程设计能力**筛选，而不是用导游或带队老师的标准——导师管学习目

相关心智模型:
  • 「研学是课程不是行程」——教育属性优先: 研学/营地的本体是**课程**（有学习目标—实施—评价闭环），不是**行程**（景点+讲解词）；从业者用「教育本质」作为对抗旅游化、获客化、速成化的立场锚与对客叙事。
  • 体验—反思闭环（Kolb 圈）——「经验无反思即旅游」: 学习不是「去过/动手过」就发生，而要走完「具体经验→反思观察→抽象概念化→主动实践」的圈；**「反思/复盘」环节的有无，是研学区别于旅游的命门工序**。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "三案（活动方案/安全预案/应急预案）+ 三层险栈（校方责任险+旅行社责任险+人身意外险）+ 人员配比（研学指导≥1:30、随团服务≥1:20、营辅按年龄分级、每团≥1 专职安全员）+ 对标 LB/T 054-2025 任一项不达标"
  "是新基地 / 换季 / 雨季 / 新增高风险项目（涉水/高海拔/交通节点）"
  "机构营期少、预算有限、刚起步（单一夏令营级）"
  "在招聘或培训研学导师 / 营地辅导员"
)
declare -a RULE_ACTIONS=(
  "无论课程多漂亮、SaaS 多先进、报价多有竞争力，都**不准成行 / 不准投标**——这是先于一切设计与选型的硬前置门"
  "绝不凭图册或招商话术决策，必**实地踩点 + 标准核查清单逐项核**（安全设施/容量/食宿/应急/医疗 + 满员峰值动线 + 雨备室内替代场地）；仅长期合作、近期带过且无变更的成熟基地可凭既有踩点报告+电话复核跳过重踩"
  "默认用**通用工具拼装**（微信小程序+金数据/腾讯收集表做报名+健康信息+监护授权+微信支付；需线上课/分销再叠加小鹅通或有赞教育）；只有当成体系运营、多营期多渠道、需安全档案/营辅排班/位置追踪时，才上垂直研学 SaaS（旅科云等），且采购前必试用+索取真实客户案例核验（行业自评垂直 SaaS「炒概念、实用性弱」，vendor 自报市占需独立核验）"
  "按**研学指导师四维能力（态度/知识/技能/发展）+ 课程设计能力**筛选，而不是用导游或带队老师的标准——导师管学习目标与课程，导游管行程交通，安全员管安全，三者分列配置不可一人兼；营辅需培训+背景审查"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
