#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 医疗美容.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="医疗美容"
DIM_COUNT=6

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (6 个):
  9.1 合规与正品核验
  9.2 解剖与危险区评估
  9.3 适应证与体象/动机筛查
  9.4 材料/术式选型与可逆性
  9.5 并发症预案与急救能力
  9.6 监管与平台时效核查

背后的心智模型:
  • 医美的第一性是医疗，不是消费: 医疗美容首先是外科与皮肤科的**医疗行为**（可致盲、致残、致死），不是快消品；任何决策的第一约束是安全与合规，不是美学最大化或转化率。
  • 先安全后审美：风险分层判断: 资深人的核心能力不是「打得漂亮」，而是**在安全处提效、在危险处零妥协**——知道哪一步能省、哪一步一步都不能省。
  • 把徒手手艺变成可教、可审计、可复现: 注射美容正从「老师傅徒手手艺」走向**方法学化**——MD Codes 全脸分区编码、精细解剖图谱、专家共识把深度/工具/剂量/危险结构编码成可教、可审计、可复现的语言。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "合规与正品核验"
  "解剖与危险区评估"
  "适应证与体象/动机筛查"
  "材料/术式选型与可逆性"
  "并发症预案与急救能力"
  "监管与平台时效核查"
)
declare -a DIM_QUESTIONS=(
  "机构《医疗机构执业许可证》经营范围、主诊医师备案与执业类别、产品/设备的 NMPA 械字号（国械注准编号、分类、有效期、正品溯源）。"
  "目标部位的注射层次（皮内/真皮/皮下/骨膜上/SMAS）、血管走行与危险三角/鼻/颞/泪沟等高危结构、是否需要超声血管 mapping。"
  "该项目的适应证/禁忌证、求美者的真实主诉与心理动机、是否存在 BDD/体象障碍或容貌焦虑驱动、是否该劝退。"
  "按机制选（容积→填充/动态肌→肉毒/肤质→光电/松弛按层次）、可逆性（玻尿酸可溶 vs 再生类/线雕不可逆）、维持时长与个体适配。"
  "该项目最坏并发症（栓塞致盲/坏死/感染/结节/肉毒中毒）、急救流程与时间窗、是否备足溶解酶/急救设备、转诊绿色通道。"
  "是否有新监管政策/专项整治、新品 NMPA 获批与市场格局变化、医美广告「八不准」与平台种草规则、off-label 用药边界。"
)
declare -a DIM_SOURCES=(
  "NMPA 国家药监局器械查询（nmpa.gov.cn）、卫健委医疗机构与医师执业查询、第三方正品验真平台。"
  "注射解剖图谱/精细解剖教材（吴溯帆著作 T01-S005）、面部危险区解剖文献（T04-S013/S014）、专家共识避险要点（T01-S006）。"
  "项目专家共识的适应证/禁忌章节、面诊问诊与触诊、BDD 筛查要点。"
  "Track 02 工具栈三层与选型决策树（02-tools.md）、厂商械字号官方信息 + ≥2 source 交叉、再生类机制文献（T06-S016）。"
  "并发症处理专家共识（T03-S004）、栓塞致盲急救与透明质酸酶应用文献（T03-S017/T06-S010）。"
  "NMPA/卫健委公告通告、《医疗美容广告执法指南》（T06-S004）、专项整治文件、上市公司披露（cninfo）。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句「资质/备案/械字号是否齐全合法、是否正品」的红绿灯结论 + 缺失项清单。"
  "「层次 + 避险动作（钝针/回抽/缓推/单点限量）+ 是否上超声」的操作要点 + 高危标记。"
  "「做/不做/转介」的分诊结论 + 禁忌与劝退理由。"
  "「首选材料/术式 + 备选 + 可逆性权重说明 + 不可逆告知点」。"
  "「最坏情况 + 急救步骤（无可省）+ 术前预案清单」。"
  "「政策/新品/平台规则是否有新变化 + 对当前方案的合规影响」+ \`last_checked\` 日期。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
