#!/usr/bin/env bash
# topic-1.sh — 创作 决策助手 for 调香师与香水.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="调香师与香水"
TOPIC="创作"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 创作 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 一个配方要上市（哪怕全天然、哪怕个人小批） → 则 先过 IFRA + EU 致敏原闸门、且引用任何限值必标修订版本号——合规先于创作自由，天然不豁免
  • 如果 用户在商业（B2B）语境创作 → 则 中枢是「core list → brief → creation → submission → mods → win/l

相关心智模型:
  • codifiable 原料 ⇄ tacit 嗅觉记忆（第一性张力）: 这行可背诵的一半（原料、香料化学、accord 公式、挥发度、IFRA 限值）能进教科书；另一半——成为「the nose」的嗅觉记忆与品味——不可言传，只能靠每天盲嗅背料一克一克长出来。学校先让学徒
  • 暗示而非复刻：香水是「说真话的谎言」: 顶级调香不复刻自然，而是用（多为合成的）分子制造一个比真实更可信的**嗅觉幻觉**——Ellena 自称 illusionist，Ropion 的 Carnal Flower 是「扭曲/暗示一朵晚香玉

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "一个配方要上市（哪怕全天然、哪怕个人小批）"
  "用户在商业（B2B）语境创作"
)
declare -a RULE_ACTIONS=(
  "先过 IFRA + EU 致敏原闸门、且引用任何限值必标修订版本号——合规先于创作自由，天然不豁免"
  "中枢是「core list → brief → creation → submission → mods → win/lose」，且 evaluator 是 brief 翻译器 + 客观性闸门——别用「每支都是独一无二人手艺术」的浪漫叙事去解释商业线"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
