#!/usr/bin/env bash
# 3d.sh — 端到端线上展览制作（自研真 3D 全流程） SOP walkthrough for Web 线上展览开发 (虚拟展厅).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web 线上展览开发 (虚拟展厅)"
WORKFLOW="端到端线上展览制作（自研真 3D 全流程）"

usage() {
  cat <<EOF
3d.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./3d.sh             # interactive
  ./3d.sh --dry-run
  ./3d.sh --json
  ./3d.sh --explain
  ./3d.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "端到端线上展览制作（自研真 3D 全流程）" 工作流。

一句话: 从「客户要个沉浸式线上展厅」到「一个 CDN 上能漫游、能交互、移动端不崩的 3D web 展厅」的完整闭环——这是自研路线的主干 SOP。

入门 SOP 共 8 步, 失败模式自检 4 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**需求 / 策展定位**：明确「要不要自由走动 / 绕物 / 拾取交互」（这一刀决定真 3D vs 全景，是整条管线的总开关）；定目标设备（移动占比？低端机？）、首屏预算、转化目标 (evidence: [T04-S016, T02-S016])"
  "**内容采集**：按展品性质选 —— 数字建模（Blender/DCC）/ 全景拍摄 / 3D 扫描·摄影测量（Metashape/RealityCapture）/ 高斯泼溅（见 W7）。文物类要对齐采集合规 (evidence: [T03-S012, T03-S013, T04-S021])"
  "**资产优化（命门，详见 W4 §资产管线）**：源模型先在 DCC/MeshLab 减面到 web 量级（摄影测量常减到 100k–500k 面），再走 glTF-Transform \`optimize\`：Draco/Meshopt 压几何 + KTX2 压纹理 + dedup/weld/prune (evidence: [T03-S001, T03-S003, T03-S012])"
  "**场景搭建**：React/Next 站内 → R3F + drei（gltfjsx 把 GLB 转 JSX）；非 React/要底层控制 → 裸 Three.js；要内建物理/编辑器 → Babylon/PlayCanvas。布光、相机、环境贴图、PBR 材质 (evidence: [T02-S003, T02-S001, T04-S005])"
  "**交互 / 动线 / 热点 / 讲解**：第一人称或轨道相机控制；动线引导（视角序列/路径）；热点（图文/语音/跳转）；语音导览 (evidence: [T04-S020 概念, T02-S024])"
  "**性能调优（命门，整套见 W4）**：draw call / 显存 / 移动端 / 首屏分级加载 / 降级链 (evidence: [T03-S001, T03-S004])"
  "**部署**：资产上 CDN；流式 / 分级加载；跨端兼容（WebGL2 fallback、iOS 兜底）(evidence: [T03-S001, T03-S004])"
  "**数据埋点 · 线索转化**：停留/点击/热点曝光埋点；表单/预约/带看等转化钩子（营销型展厅核心 KPI）(evidence: [T02-S027])"
)
declare -a FAILURE_MODES=(
  "大模型不压缩直接上 → 首屏崩：必须先 DCC 减面 + glTF-Transform optimize，别把 50MB GLTF 丢上线 (evidence: [T03-S001])"
  "把展厅当普通网页写、不立性能预算 → 后期推倒重来：day 1 定 draw call/首屏/显存预算再选栈 (evidence: [T03-S001])"
  "动线/热点缺失 → 用户迷路：先用灰模走通动线再美化 (evidence: [T02-S024])"
  "忘了埋点 → 无法证明 ROI：转化钩子和埋点设计要前置 (evidence: [T02-S027])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "3d-walkthrough"
fi
