#!/usr/bin/env bash
# model-viewer.sh — 单展品 model-viewer 嵌入 SOP walkthrough for Web 线上展览开发 (虚拟展厅).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web 线上展览开发 (虚拟展厅)"
WORKFLOW="单展品 model-viewer 嵌入"

usage() {
  cat <<EOF
model-viewer.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./model-viewer.sh             # interactive
  ./model-viewer.sh --dry-run
  ./model-viewer.sh --json
  ./model-viewer.sh --explain
  ./model-viewer.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "单展品 model-viewer 嵌入" 工作流。

一句话: 从「详情页要嵌一个可旋转 + AR 的展品」到「一行 HTML 的 3D/AR 展品」——零 3D 编程的最快出活路线。

入门 SOP 共 5 步, 失败模式自检 3 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**准备资产**：模型转 GLB + 走 glTF-Transform 压缩；iOS AR 额外出 USDZ（\`ios-src\`）(evidence: [T02-S007, T03-S003])"
  "**嵌标签 + 基础属性**：\`<model-viewer src poster camera-controls auto-rotate environment-image shadow-intensity exposure>\`；\`poster\` 给首屏占位图、\`loading=\"lazy\"\` + \`reveal\` 控制首屏性能 (evidence: [T03-S005, T03-S006])"
  "**配 AR**：\`ar ar-modes=\"webxr scene-viewer quick-look\"\`——Android 走 Scene Viewer、iOS 走 Quick Look（USDZ）(evidence: [T03-S006, T02-S007])"
  "**加热点 / 注解**：子元素 \`slot\` 以 \`hotspot\` 开头即为热点，配 \`data-position\` + \`data-normal\`（或动画模型用 \`data-surface\`）；编辑器里点选生成坐标，或 \`updateHotspot({name,position,normal})\` 动态更新 (evidence: [T03-S006])"
  "**嵌入页面 / 验收**：iframe 或直接组件；移动端 AR 真机测 (evidence: [T03-S005])"
)
declare -a FAILURE_MODES=(
  "没出 USDZ → iOS AR 不可用：iOS 必备 \`ios-src\` USDZ (evidence: [T02-S007])"
  "模型没压缩 → 详情页首屏慢：嵌入前必压 + 用 poster/lazy (evidence: [T03-S001, T03-S005])"
  "热点坐标手填错位 → 飘在模型外：用编辑器点选生成 data-surface/data-position (evidence: [T03-S006])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "model-viewer-walkthrough"
fi
