#!/usr/bin/env bash
# playbook.sh — 性能优化 Playbook（命门 — 单列） SOP walkthrough for Web 线上展览开发 (虚拟展厅).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web 线上展览开发 (虚拟展厅)"
WORKFLOW="性能优化 Playbook（命门 — 单列）"

usage() {
  cat <<EOF
playbook.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./playbook.sh             # interactive
  ./playbook.sh --dry-run
  ./playbook.sh --json
  ./playbook.sh --explain
  ./playbook.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "性能优化 Playbook（命门 — 单列）" 工作流。

一句话: 从「首屏慢 / 移动端崩 / 掉帧」到「首屏达标 + 帧率稳定 + 各端不崩」——这是线上展览的生死线，几乎所有项目的真正难点。

入门 SOP 共 8 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**① 资产管线压缩（第一刀，收益最大）**："
  "**② draw call / instancing / 合批**：目标 **<100 draw calls/帧** 才稳 60fps；重复物体用 \`InstancedMesh\`（1000 棵树 1000→1 call；实测案例 9000→300）；异几何同材质用 \`BatchedMesh\`；静态合并 \`mergeGeometries\`；共享材质 + 纹理 atlas (evidence: [T03-S001])"
  "**③ LOD / frustum culling**：按距离切精度（drei \`<Detailed distances={[0,50,100]}>\`，大场景提帧 30–40%）；保证 bounding box 准确让视锥剔除生效 (evidence: [T03-S001])"
  "**④ 首屏分级加载**：先加载 \`low.glb\` 立即可交互，后台换 \`high.glb\`；\`<link rel=\"preload\" as=\"fetch\">\` 预载关键资产；R3F \`<Suspense>\` + 占位低模盒；按相机邻近度流式加载分区；Web Worker 卸载重活；代码分割 loader (evidence: [T03-S001])"
  "**⑤ 移动端显存 / pixelRatio**：移动 \`pixelRatio\` 限到 1（或半分辨率渲染再上采样可翻倍帧率）；阴影贴图移动 512–1024、桌面 1024–2048；mediump（移动快 2x）；varying < 3；避免分支用 \`mix()/step()\` (evidence: [T03-S001, T03-S004])"
  "**⑥ 显存释放 / 防泄漏**：用完 \`geometry/material/texture/renderTarget.dispose()\`；GLTF 的 ImageBitmap 要 \`texture.source.data.close?.()\`；多展厅切换用对象池 + 卸载 (evidence: [T03-S001])"
  "**⑦ WebGL 降级链**：\`three/webgpu\` 入口自动回退 WebGL2；手搓渲染要 \`canvas.getContext('webgl2')||getContext('webgl')\` 判空兜底；扩展按可选优雅降级 (evidence: [T03-S002, T03-S004])"
  "**⑧ 监控（draw call / FPS / 帧时间）**：\`renderer.info.render.calls / .triangles\`、\`renderer.info.memory.geometries/.textures\`（数值只增=泄漏）；stats-gl 看 FPS/CPU/GPU（兼容 WebGL+WebGPU）；Spector.js 抓帧逐 draw call；Chrome Performance 看帧时间/GC (evidence: [T03-S001])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "playbook-walkthrough"
fi
