#!/usr/bin/env bash
# saas-matterport-artsteps.sh — SaaS 平台快速搭建（众趣 / 酷雷曼 / Matterport / Artsteps） SOP walkthrough for Web 线上展览开发 (虚拟展厅).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web 线上展览开发 (虚拟展厅)"
WORKFLOW="SaaS 平台快速搭建（众趣 / 酷雷曼 / Matterport / Artsteps）"

usage() {
  cat <<EOF
saas-matterport-artsteps.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./saas-matterport-artsteps.sh             # interactive
  ./saas-matterport-artsteps.sh --dry-run
  ./saas-matterport-artsteps.sh --json
  ./saas-matterport-artsteps.sh --explain
  ./saas-matterport-artsteps.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "SaaS 平台快速搭建（众趣 / 酷雷曼 / Matterport / Artsteps）" 工作流。

一句话: 从「工期紧、没 3D 团队」到「几天内上线一个全景或数字孪生展厅」——买平台换速度的主干 SOP。

入门 SOP 共 5 步, 失败模式自检 3 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**选平台 + 尽调锁定**：海外艺术教育→Artsteps（免费 no-code）；国内营销→众趣/酷雷曼/720云；高保真数字孪生→Matterport。**先查能否导出 / 二开 / 私有部署**（Matterport/Kuula 云端独占不可导出）(evidence: [T02-S024, S027, S020, S026])"
  "**内容采集**：平台自有设备（Matterport Pro / 众趣 SPACCOM）或第三方全景相机拍摄；或导入已有 3D 数据 (evidence: [T02-S020, S027])"
  "**平台内搭建**：选模板 / 摆墙·展柜（Artsteps）；上传图文/视频/音频/3D；自动生成漫游 (evidence: [T02-S024])"
  "**加热点 / 导览 / 转化工具**：图文热点、语音导览、楼层图、空间测量；营销表单/直播/VR 带看 (evidence: [T02-S027, S024])"
  "**发布 / 嵌入 / 分发**：站内发布或 iframe 嵌入官网；国内绑小程序生态 (evidence: [T02-S024, S029])"
)
declare -a FAILURE_MODES=(
  "选了云端独占平台才发现导不出 → 永久锁定：选型即查导出能力，要自托管选 3DVista，要二开选可 OEM 的 (evidence: [T02-S026, S028])"
  "以为 SDK 免费能商用 → 上线被卡：Matterport SDK 生产用需付费订阅，先确认授权档 (evidence: [T02-S022])"
  "只发布不分发 → 零触达：国内必绑小程序生态，海外靠链接/嵌入 (evidence: [T02-S029])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "saas-matterport-artsteps-walkthrough"
fi
