#!/usr/bin/env bash
# workflow-1.sh — 高斯泼溅「实景扫描即展厅」管线（新兴） SOP walkthrough for Web 线上展览开发 (虚拟展厅).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web 线上展览开发 (虚拟展厅)"
WORKFLOW="高斯泼溅「实景扫描即展厅」管线（新兴）"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "高斯泼溅「实景扫描即展厅」管线（新兴）" 工作流。

一句话: 从「要 photoreal 实景、又不接受全景的平面感」到「可在 web 漫游的 3D 高斯泼溅场景」——2024–2026 兴起的第三条实景路线（全景与摄影测量 mesh 之外）。

入门 SOP 共 5 步, 失败模式自检 4 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**采集**：手机视频 / 多角度照片 / 无人机绕拍（覆盖全、视差足、曝光稳）；Niantic Scaniverse、Polycam 等移动 app 可一站采集 (evidence: [T03-S009, T03-S010])"
  "**处理 / 训练**：SfM（COLMAP）求相机位姿 → 训练高斯（postshot/brush/nerfstudio 类）；从草稿到高质量大场景分档 (evidence: [T03-S009, T03-S010])"
  "**清洗 / 编辑**：用 **SuperSplat**（浏览器内开源编辑器）裁掉漂浮物、背景、地面噪点，框定展示范围 (evidence: [T03-S014, T01-S034])"
  "**压缩 / 导出**：导出 web 友好格式——Niantic **SPZ**（开源、为渐进 web 传输优化）/ .ksplat / .sog 压缩；原始 .ply 太大需压 (evidence: [T03-S009, T03-S010])"
  "**web viewer 集成 + 兜底**：PlayCanvas（一等支持）/ Spark / mkkellogg GaussianSplats3D（Three.js）/ Babylon 渲染；移动端性能与低端机降级要测 (evidence: [T01-S032, S033, T03-S010])"
)
declare -a FAILURE_MODES=(
  "采集覆盖/视差不足 → 重建糊/空洞：环绕 + 多高度 + 稳曝光，宁多拍 (evidence: [T03-S009])"
  "不清洗直接上 → 满场漂浮高斯：SuperSplat 裁噪、框范围后再发布 (evidence: [T03-S014])"
  "原始 .ply 直接上 web → 体积爆/移动崩：导 SPZ/.ksplat 压缩 + 测低端机 (evidence: [T03-S009, T03-S010])"
  "当成 ratified 标准做长期依赖 → 规范变动返工：KHR_gaussian_splatting 仍 RC，留迁移余地 (evidence: [T03-S008])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
