#!/usr/bin/env bash
# workflow-5.sh — 手机/网络沉迷干预工作流 SOP walkthrough for 家庭教育指导.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="家庭教育指导"
WORKFLOW="手机/网络沉迷干预工作流"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "手机/网络沉迷干预工作流" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 关系先于教育 (Connection Before Correction): 家庭教育指导的第一原则不是「教家长正确做法」, 而是先修复或巩固亲子情感连接 — 没有安全依恋基础的教养技术是空中楼阁, Bowlby/Ainsworth 的依恋理论和 Siegel 的「连接先于纠正
  • 行为是信号, 不是问题本身 (Behavior Is a Signal, Not the Problem): 孩子的「问题行为」(发脾气/撒谎/拒学/手机沉迷) 几乎从来不是问题本身, 而是未被满足的需求在呐喊 — Dreikurs 的四个错误目标 (寻求关注/争夺权力/报复/自我放弃) 和 Rosenber

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "使用评估 → 使用手机依赖指数量表（MPAI）对青少年进行初步筛查；评估使用时长/使用场景/家长管控模式 2. 家庭系统评估 → 识别手机沉迷的家庭功能背景（亲子关系疏离/家长自身手机使用问题/家庭规则缺失/现实替代需求） 3. 心理教育（双轨）→ 向家长讲解手机沉迷的心理需求满足机制（自主/胜任/关系三需求）；向青少年说明大脑奖励回路与习惯形成 4. 制定亲子使用协议 → 家长与子女共同协商（非家长单方面规定）：使用时间/场所/内容/违约处理方式；协议白纸黑字签署 5. 替代活动设计 → 帮助家庭找到能满足同等心理需求的线下替代（运动/社交/创造性活动）；优先选择亲子共同参与的活动 6. 4-6周随访 → 检视协议执行情况；调整策略；防止家长单方面撕毁协议引发信任危机"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
