#!/usr/bin/env bash
# workflow-8.sh — 家庭教育指导师职业培训工作流 SOP walkthrough for 家庭教育指导.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="家庭教育指导"
WORKFLOW="家庭教育指导师职业培训工作流"

usage() {
  cat <<EOF
workflow-8.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-8.sh             # interactive
  ./workflow-8.sh --dry-run
  ./workflow-8.sh --json
  ./workflow-8.sh --explain
  ./workflow-8.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "家庭教育指导师职业培训工作流" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 关系先于教育 (Connection Before Correction): 家庭教育指导的第一原则不是「教家长正确做法」, 而是先修复或巩固亲子情感连接 — 没有安全依恋基础的教养技术是空中楼阁, Bowlby/Ainsworth 的依恋理论和 Siegel 的「连接先于纠正
  • 行为是信号, 不是问题本身 (Behavior Is a Signal, Not the Problem): 孩子的「问题行为」(发脾气/撒谎/拒学/手机沉迷) 几乎从来不是问题本身, 而是未被满足的需求在呐喊 — Dreikurs 的四个错误目标 (寻求关注/争夺权力/报复/自我放弃) 和 Rosenber

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "报名资质核实 → 确认基础条件（大专及以上学历/相关工作经验/无违规记录）；了解报考动机和职业规划 2. 基础理论课程 → 发展心理学基础（Erikson/Bowlby/Baumrind/Dreikurs）+ 家庭教育学理论（陈鹤琴/赵忠心框架）+ 《家庭教育促进法》政策解读；线上/线下共96-128课时 3. 实操技能训练 → 亲子沟通技术（NVC/积极倾听/I-message）+ 评估工具使用（SDQ/PSI/ECBI基础）+ 个案咨询记录规范；角色扮演演练 4. 督导实习 → 在督导下完成至少10个家庭指导个案；提交案例报告；参加案例讨论 5. 考核认证 → 笔试（理论知识）+ 口试/实操考核（现场模拟咨询）+ 案例报告提交；合格者获证书 6. 持续教育 → 每年参加继续教育课程≥16学时；定期督导；参与同伴学习社群"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-8-walkthrough"
fi
