#!/usr/bin/env bash
# workflow-6.sh — 离异家庭共同养育指导工作流 SOP walkthrough for 家庭教育指导.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="家庭教育指导"
WORKFLOW="离异家庭共同养育指导工作流"

usage() {
  cat <<EOF
workflow-6.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-6.sh             # interactive
  ./workflow-6.sh --dry-run
  ./workflow-6.sh --json
  ./workflow-6.sh --explain
  ./workflow-6.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "离异家庭共同养育指导工作流" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 关系先于教育 (Connection Before Correction): 家庭教育指导的第一原则不是「教家长正确做法」, 而是先修复或巩固亲子情感连接 — 没有安全依恋基础的教养技术是空中楼阁, Bowlby/Ainsworth 的依恋理论和 Siegel 的「连接先于纠正
  • 行为是信号, 不是问题本身 (Behavior Is a Signal, Not the Problem): 孩子的「问题行为」(发脾气/撒谎/拒学/手机沉迷) 几乎从来不是问题本身, 而是未被满足的需求在呐喊 — Dreikurs 的四个错误目标 (寻求关注/争夺权力/报复/自我放弃) 和 Rosenber

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "分别评估 → 与离异双方分别会面（避免联合面谈初期），了解各自的养育诉求、冲突点、对孩子影响的认知 2. 子女福祉评估 → 以子女最佳利益为框架评估现状；使用SDQ评估孩子的情绪行为状态；了解孩子在双方家庭间的适应情况 3. 共同养育框架建立 → 教育双方\"合作式养育\"（cooperative co-parenting）的核心原则：以孩子为中心/分离个人情感与养育职责/保持一致性 4. 沟通规则设定 → 协助制定书面共同养育沟通协议（时间安排/重大决策通知规则/禁止在孩子面前贬低对方） 5. 冲突降级技术 → 教授情绪管理策略；使用I-message表达诉求；建议使用中性沟通渠道（书面/应用） 6. 持续随访 → 每月一次跟进；识别孩子调适困难的早期信号"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-6-walkthrough"
fi
