#!/usr/bin/env bash
# on-call-sop-alert-triage-declare.sh — 事件响应 + on-call SOP（alert → triage → declare SEV → IC → mitigate → comms → resolve） SOP walkthrough for DevOps 与 SRE.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="DevOps 与 SRE"
WORKFLOW="事件响应 + on-call SOP（alert → triage → declare SEV → IC → mitigate → comms → resolve）"

usage() {
  cat <<EOF
on-call-sop-alert-triage-declare.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./on-call-sop-alert-triage-declare.sh             # interactive
  ./on-call-sop-alert-triage-declare.sh --dry-run
  ./on-call-sop-alert-triage-declare.sh --json
  ./on-call-sop-alert-triage-declare.sh --explain
  ./on-call-sop-alert-triage-declare.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "事件响应 + on-call SOP（alert → triage → declare SEV → IC → mitigate → comms → resolve）" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

相关心智模型:
  • 错误预算思维 — 可靠性是产品决策, 不是技术债; 100% 是错误的目标: 可靠性不是越高越好 — `error budget = 1 - SLO` 是一笔可花的预算, 它把"该发功能还是修可靠性"从情绪/道德争论变成 dev/SRE/产品三方共享的数字决策; 盲目追 100
  • 小批量高频部署 > 少发布 (反直觉) — 速度与稳定不是 trade-off: 直觉是"少发布就少出事", 但 DORA 用 23,000+ 受访者的统计学证明这是错的 — 低部署频率 = 大批量变更 = 更高 change failure rate + 更难定位; elite 

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "acknowledge 告警：on-call 在 SLA 内 ack，表示\"我接手了\""
  "triage + 评估影响：多少用户/哪些功能受影响、是否在恶化"
  "declare SEV 等级：按影响定级（SEV-1 关键/广泛影响 → SEV-3 小问题）。超过 SEV-3 即\"major incident\"启动更重响应"
  "指定 Incident Commander（IC）：IC 只协调不动手改系统，明确\"谁是 IC\""
  "mitigate（先止血）：回滚/切流量/降级/扩容——先恢复服务，root cause TBD"
  "comms / status page：IC 指定 comms 角色对外（status page）+ 对内（stakeholder）定期更新"
  "resolve + 移交复盘：服务恢复、降级、留时间线、安排 blameless postmortem"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "on-call-sop-alert-triage-declare-walkthrough"
fi
