#!/usr/bin/env bash
# workflow-4.sh — 趋势 / 动量工作流（定信号 → 分散篮子 → 系统化进出 → 风险定仓 → 跟系统） SOP walkthrough for 个人投资理财.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="个人投资理财"
WORKFLOW="趋势 / 动量工作流（定信号 → 分散篮子 → 系统化进出 → 风险定仓 → 跟系统）"

usage() {
  cat <<EOF
workflow-4.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-4.sh             # interactive
  ./workflow-4.sh --dry-run
  ./workflow-4.sh --json
  ./workflow-4.sh --explain
  ./workflow-4.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "趋势 / 动量工作流（定信号 → 分散篮子 → 系统化进出 → 风险定仓 → 跟系统）" 工作流。

一句话: 从「我想用机械规则跟随价格趋势、在熊市自动离场」到「一套不预测方向、纯按信号进出、分散在多资产篮子上、严格控仓的系统化策略」—— 与技术派（主观读图）的关键区别：**完全机械、规则前置、不主观**；与价值/被动的根本分歧：不看价值、不长期死扛，跟趋势 + 让利润奔跑 + 严格止损。学术地基 = Jegadeesh-Titman 1993 动量效应（→ T04-P05）。本派是散户能照着做的「可回测、可复制」择时路线，区别于技术派的酌情交易。

入门 SOP 共 5 步, 失败模式自检 5 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定信号（机械、可回测）**：选一个明确规则。两条散户常引路线：① **Faber 200 日/10 个月 MA**——价格在 10 个月(≈200日)均线**之上**则持有、**之下**则移到现金（结果：约 70% 时间在市、每年 < 1 次往返、股票级回报+债券级回撤）。② **Antonacci 双动量 (GEM)**——用**相对动量**在美股 vs 非美股间选强者，用**绝对动量**（自身近 12 月正/负）在股票 vs 债券间切换。(evidence: [T03-S023, T03-S017])"
  "**分散篮子（多资产）**：把信号应用到一篮**低相关**资产（美股/国际股/债/REIT/商品），而非单一标的——趋势在「几乎所有资产、所有市场」都存在（Asness「Value and Momentum Everywhere」），分散摊平单一市场失效。(evidence: [T03-S017])"
  "**系统化进出**：信号触发就**无条件**执行进出（不二次猜测、不因「这次不一样」覆盖规则）。(evidence: [T03-S023])"
  "**风险（平价）定仓**：按**风险贡献**而非等资金分配（波动率目标 / 风险平价），让每个仓位贡献相近风险；或按 ATR/波动率反推仓位。(evidence: [T03-S017])"
  "**跟系统不主观（核心纪律）**：长期严格执行，**扛得住**策略阶段性难看（趋势策略会有长期跑输/震荡市连续小亏的「煎熬期」）。Asness：「理性、能分散的策略期望回报更高，但你得先扛得住它阶段性的难看。」(evidence: [T03-S017])"
)
declare -a FAILURE_MODES=(
  "**煎熬期放弃系统**：连续假信号/跑输后人为中断，恰在该兑现前离场。自检：你写下「能忍 N 个月跑输」并据此定了仓位吗？"
  "**单一资产跑趋势被锯死**：震荡市 whipsaw。自检：你的信号是应用在一篮低相关资产上吗？"
  "**选择性执行规则**：只在「感觉对」时跟信号。自检：上次信号触发你是无条件执行还是覆盖了规则？"
  "**过拟合回测**：调参到历史完美曲线、样本外崩（→ T02 反模式）。自检：换市场/换时段/加交易成本后系统还正吗？"
  "**忽略换手成本**：趋势策略高换手，实盘被佣金+滑点吃掉回测收益。自检：你的回测含交易成本和滑点了吗？"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-4-walkthrough"
fi
