#!/usr/bin/env bash
# preventive-security-hardening.sh — 预防性安全加固 (Preventive Security Hardening) SOP walkthrough for GitHub 解封 — 账号封禁/限制/恢复的领域操作系统。覆盖：(a) GitHub 官方政策体系 (TOS / 可接受使用政策 / Trust & Safety 执行模式 / 公开申诉路径 / 受制裁地区解读)；(b) 封号原因诊断学 (spam / abuse / 制裁误标 / 2FA 丢失 / ToS 违规 / 账号劫持误判 / ban evasion 等子类型 + 症状→原因映射 + 自我分诊压测)；(c) 申诉实操 craft (写一封能让 T&S 快速判误伤的英文申诉信 + 升级阶梯 + 法务介入边界 + Don'ts)；(d) 制裁与合规硬边界 (OFAC SDN 名单 / 哪些国家或地区真不可达 / VPN 误判路径 / 中国大陆不是美国制裁地区的反复重申)；(e) 中国大陆开发者特别处境 (sanctioned region 误标 + SMS 验证不支持 +86/+852 + Gitee/GitLab/Codeberg/JihuLab 备用迁移 + 私有自托管 Gitea/Forgejo)；(f) 真实案例库 (~30+ 公开案例分类拆解：误伤 / 真违规 / 制裁误标三类各自赔率与申诉成功路径)。伦理锚绝不软化：不教 ban evasion / 不教撒谎式申诉 / 真违规承认改进 / 丢 2FA 无恢复因子则诚实告知 / 中国制裁误标靠申诉不靠换 VPN / 申诉 6 个月窗口必算清 / ~3% 真违规恢复 vs ~79% 误伤申诉成功率分层标。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="GitHub 解封 — 账号封禁/限制/恢复的领域操作系统。覆盖：(a) GitHub 官方政策体系 (TOS / 可接受使用政策 / Trust & Safety 执行模式 / 公开申诉路径 / 受制裁地区解读)；(b) 封号原因诊断学 (spam / abuse / 制裁误标 / 2FA 丢失 / ToS 违规 / 账号劫持误判 / ban evasion 等子类型 + 症状→原因映射 + 自我分诊压测)；(c) 申诉实操 craft (写一封能让 T&S 快速判误伤的英文申诉信 + 升级阶梯 + 法务介入边界 + Don'ts)；(d) 制裁与合规硬边界 (OFAC SDN 名单 / 哪些国家或地区真不可达 / VPN 误判路径 / 中国大陆不是美国制裁地区的反复重申)；(e) 中国大陆开发者特别处境 (sanctioned region 误标 + SMS 验证不支持 +86/+852 + Gitee/GitLab/Codeberg/JihuLab 备用迁移 + 私有自托管 Gitea/Forgejo)；(f) 真实案例库 (~30+ 公开案例分类拆解：误伤 / 真违规 / 制裁误标三类各自赔率与申诉成功路径)。伦理锚绝不软化：不教 ban evasion / 不教撒谎式申诉 / 真违规承认改进 / 丢 2FA 无恢复因子则诚实告知 / 中国制裁误标靠申诉不靠换 VPN / 申诉 6 个月窗口必算清 / ~3% 真违规恢复 vs ~79% 误伤申诉成功率分层标。"
WORKFLOW="预防性安全加固 (Preventive Security Hardening)"

usage() {
  cat <<EOF
preventive-security-hardening.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./preventive-security-hardening.sh             # interactive
  ./preventive-security-hardening.sh --dry-run
  ./preventive-security-hardening.sh --json
  ./preventive-security-hardening.sh --explain
  ./preventive-security-hardening.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "预防性安全加固 (Preventive Security Hardening)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "2FA 强化 (按安全等级从高到低): 最高: 硬件安全钥匙 (YubiKey 5 系列 / Google Titan / Feitian), 注册为 FIDO2/WebAuthn 凭据 — 抗钓鱼, 不可被远程窃取; 次高: Passkey (synced across devices), 同时满足密码和 2FA, 2024 年起 GitHub 原生支持; 高: TOTP 应用 (Authy / 1Password / Aegis), 扫码绑定后生成时间码; 低 (不推荐): SMS 验证 — 易被 SIM swap 攻击, 且不支持 +86 / +852 等国家代码 [T03-S003] [T03-S016] [T03-S017] [T03-S029]"
  "Recovery Codes 离线存储: 启用 2FA 时生成的恢复码 (默认文件名 github-recovery-codes.txt) 必须安全存储; 推荐: 打印纸质副本放保险箱 + 密码管理器中加密存储一份; 禁止: 仅存在同一台手机/电脑上 (设备丢失则 codes 同时丢失) [T03-S003] [T03-S026]"
  "注册多个验证方式: 至少注册两种不同类别的 2FA 方式 (例如: 一个硬件钥匙 + 一个 TOTP app); 注册 passkey 到至少两个不同设备上 (以防一个设备丢失); 如果使用硬件钥匙, 买两把 (一把日常使用, 一把作为备份存放在不同物理位置) [T03-S003] [T03-S017]"
  "定期备份自动化: 设置 cron job 或 scheduled task 定期执行 \`git clone --mirror\` (或 \`git remote update --prune\` 更新已有 mirror); 推荐频率: 重要项目每日, 一般项目每周; 备份应包含非 Git 数据: 使用 \`gh issue list --json\` + \`gh pr list --json\` 导出 issues 和 PRs; 使用 GitHub Migration API 定期做完整归档导出; 备份存储在 GitHub 以外的位置 (本地磁盘 + 外部硬盘/NAS/S3) [T03-S013] [T03-S014] [T03-S034]"
  "多平台冗余 (mirror): 设置 Git 仓库自动 mirror 到第二平台 — GitLab (Settings → Repository → Mirroring) 或 Codeberg 支持自动从 GitHub 拉取; 配置方式: \`git remote add mirror URL && git push --mirror mirror\` 放入 cron; 或使用 GitLab 的 pull mirror 功能 (每 5 分钟自动同步) [T03-S015] [T03-S031]"
  "避免触发风控的行为模式: 不使用 \"star exchange\" / \"互 star\" 平台 (直接导致封号) [T03-S022] [T03-S035]; 不在短时间内批量 fork / star / create issues (会被自动化检测为 bot/spam); 不使用来路不明的第三方 GitHub App/OAuth App (可能注入恶意代码或窃取 token) [T03-S025]; 自动化 API 操作遵守 rate limit (5000 requests/hour for authenticated users); 避免 commit message 中包含敏感关键词 (某些过滤器可能误判) [T03-S022]"
  "VPN 使用注意事项: 如果你在非制裁区但使用 VPN, 确保 VPN 出口 IP 不在制裁区 (伊朗 / 克里米亚 / 朝鲜 / 古巴); 推荐: 使用知名 VPN 服务商的日本/新加坡/美国/欧盟出口节点; GitHub 通过 IP + 支付历史判断位置, 长期使用同一制裁区 IP 会被标记; 如果必须使用 VPN, 确保 GitHub 账号的支付信息 (如有) 指向你的真实位置 [T03-S002] [T03-S024]"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "preventive-security-hardening-walkthrough"
fi
