#!/usr/bin/env bash
# topic-4.sh — 价值 决策助手 for 个人投资理财.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="个人投资理财"
TOPIC="价值"

usage() {
  cat <<EOF
topic-4.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-4.sh             # interactive
  ./topic-4.sh --dry-run   # walk through but no file
  ./topic-4.sh --json      # JSON to stdout
  ./topic-4.sh --explain   # show backing playbook rules + mental models
  ./topic-4.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 价值 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 你要主动下注 → 则 等明确的确认条件满足再动，不在「便宜/像要涨」时就动——价值派：价格相对内在价值有显著折扣（安全边际）才买；技术派：放量
  • 如果 一笔持仓的卖出决策来了 → 则 按 thesis/规则驱动而非价格情绪——价值派：thesis 被证伪/估值远超价值才卖；趋势派：触止损无条件出。案例：

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "你要主动下注"
  "一笔持仓的卖出决策来了"
)
declare -a RULE_ACTIONS=(
  "等明确的确认条件满足再动，不在「便宜/像要涨」时就动——价值派：价格相对内在价值有显著折扣（安全边际）才买；技术派：放量突破确认才入场；趋势派：绝对动量转正才持有。案例：一只低 P/E 股「看着便宜」直接买 → 踩价值陷阱（低 P/E 因盈利将崩）；正解是先估内在价值、确认是 price 跌而非 value 跌。evidence: [T03-S014, T04-S004]"
  "按 thesis/规则驱动而非价格情绪——价值派：thesis 被证伪/估值远超价值才卖；趋势派：触止损无条件出。案例：一只股涨了想「落袋为安」、跌了想「割肉」→ 处置效应（砍赢家留输家）；改成只问「当初买入的理由还成立吗 / 规则说什么」。evidence: [T03-S014, T01-S001]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-4-decision"
fi
