#!/usr/bin/env bash
# ai-curious-refuge-ai-decay-risk-.sh — AI 短片 / 分镜全流程（Curious Refuge 式 AI 影视）(Decay risk: high) last_updated: 2026-06-22 SOP walkthrough for AIGC 创作工作流.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AIGC 创作工作流"
WORKFLOW="AI 短片 / 分镜全流程（Curious Refuge 式 AI 影视）(Decay risk: high) last_updated: 2026-06-22"

usage() {
  cat <<EOF
ai-curious-refuge-ai-decay-risk-.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./ai-curious-refuge-ai-decay-risk-.sh             # interactive
  ./ai-curious-refuge-ai-decay-risk-.sh --dry-run
  ./ai-curious-refuge-ai-decay-risk-.sh --json
  ./ai-curious-refuge-ai-decay-risk-.sh --explain
  ./ai-curious-refuge-ai-decay-risk-.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "AI 短片 / 分镜全流程（Curious Refuge 式 AI 影视）(Decay risk: high) last_updated: 2026-06-22" 工作流。

一句话: 做一支完整 AI 短片 —— 脚本→分镜→角色/世界设定→关键帧→逐镜头视频生成→配音音效→剪辑成片。从「一个故事 idea」到「一支可播放的短片」。

入门 SOP 共 7 步, 失败模式自检 4 项。

相关心智模型:
  • 可控性 ⇄ 抽卡随机（slot machine）的第一性张力: 扩散模型本质是「抽卡机」（Bilawal Sidhu 直接命名 slot machine nature），同 prompt 多跑挑可用——生成式视觉创作的每个决策都在「可控性/工程化复现 ⇄ 随机性/
  • 模型是地板，审美与判断是天花板: 同样的模型与参数，产出天差地别取决于人的审美判断、概念、构图、镜头语言与「在哪一步停」的判断；模型决定下限（地板），人的审美与工程判断决定上限（天花板），「换个更大的底模就行」是外行幻觉。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**脚本**：用 AI 文本工具（或自写）生成 idea、写脚本、按制作 pipeline 格式化分场。(evidence: [T03-S018])"
  "**分镜（storyboard）**：把脚本拆成镜头，每镜头定景别/构图/运镜，用快速图像模型 blocking 出分镜帧。(evidence: [T03-S019])"
  "**角色/世界设定**：建角色 sheet（多角度参考图）+ 世界/美术风格基调，作为全片一致性锚。(evidence: [T03-S018])"
  "**逐镜头出关键帧**：按分镜用图像工作流（workflow 1 + 一致性 workflow 3）出每镜头首帧，锁角色一致。"
  "**逐镜头视频生成**：每个关键帧走 I2V（workflow 6），按 shot 选合适视频模型（控制多 cut 用 Kling，物理真实用 Sora 等）。(evidence: [T03-S019])"
  "**配音音效**：AI 配音/voice-over、音效、配乐（或 Veo 原生音频）。(evidence: [T03-S018])"
  "**剪辑成片**：剪辑软件里拼镜头、调节奏、转场、调色，输出成片。"
)
declare -a FAILURE_MODES=(
  "**跳过 preproduction 直接生成**：没脚本没分镜没角色 sheet，镜头碎、角色乱 —— 脚本→分镜→角色 sheet 先做完再生成第一帧。"
  "**全片平均用力精修每帧**：算力/时间耗在不重要镜头 —— 快模型 blocking 全片，只精修关键镜头。"
  "**一个模型扛全片**：某些镜头动态/控制达不到 —— 按 shot 需求选不同视频模型。"
  "**忽视声音与剪辑**：画面好但没声音设计/剪辑节奏，不成片 —— 后期（配音/音效/剪辑）是成片感主来源。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "ai-curious-refuge-ai-decay-risk--walkthrough"
fi
