#!/usr/bin/env bash
# midjourney-sref-cref-oref-decay-.sh — Midjourney 闭源易用出图流（sref/cref/oref 一致性）(Decay risk: high) last_updated: 2026-06-22 SOP walkthrough for AIGC 创作工作流.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AIGC 创作工作流"
WORKFLOW="Midjourney 闭源易用出图流（sref/cref/oref 一致性）(Decay risk: high) last_updated: 2026-06-22"

usage() {
  cat <<EOF
midjourney-sref-cref-oref-decay-.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./midjourney-sref-cref-oref-decay-.sh             # interactive
  ./midjourney-sref-cref-oref-decay-.sh --dry-run
  ./midjourney-sref-cref-oref-decay-.sh --json
  ./midjourney-sref-cref-oref-decay-.sh --explain
  ./midjourney-sref-cref-oref-decay-.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Midjourney 闭源易用出图流（sref/cref/oref 一致性）(Decay risk: high) last_updated: 2026-06-22" 工作流。

一句话: 零工程门槛在 Midjourney 出高审美图，并用风格/角色参考做一致性 —— Draft 探方向→prompt+参数→风格(--sref)/角色(--oref)参考锁一致→精修。从「要好看的图但不想搭环境」到「高一致性成图组」。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 可控性 ⇄ 抽卡随机（slot machine）的第一性张力: 扩散模型本质是「抽卡机」（Bilawal Sidhu 直接命名 slot machine nature），同 prompt 多跑挑可用——生成式视觉创作的每个决策都在「可控性/工程化复现 ⇄ 随机性/
  • 模型是地板，审美与判断是天花板: 同样的模型与参数，产出天差地别取决于人的审美判断、概念、构图、镜头语言与「在哪一步停」的判断；模型决定下限（地板），人的审美与工程判断决定上限（天花板），「换个更大的底模就行」是外行幻觉。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**写 prompt**：自然语言描述主体+风格+氛围，加纵横比 --ar 等基础参数。"
  "**Draft 模式探方向**：用 Draft 模式（半价、10× 速度）快速出大量草图筛方向。(evidence: [T03-S022])"
  "**锁风格（--sref）**：找到喜欢的风格后，用 --sref + 图 URL 或风格码锁风格，--sw（0-1000，默认 100）调风格强度。(evidence: [T03-S014])"
  "**锁角色（v7 用 --oref）**：用 Omni Reference --oref + 图 URL 锁角色/物体，--ow（1-1000）调影响（25-50 偏风格化、400+ 强遵循）。注意 v7 不兼容旧 --cref。(evidence: [T03-S013, T03-S015])"
  "**Upscale 精修出图**：挑满意的 upscale 到成图分辨率。"
)
declare -a FAILURE_MODES=(
  "**v7 还用 --cref**：报错/被忽略，角色锁不住 —— v7 改用 --oref（Omni Reference）。"
  "**不用 Draft 烧算力试错**：探方向用正式模式 2× 成本 —— 探方向全程 Draft，定方向才正式 upscale。"
  "**闭源当可复现管线**：MJ 不可锁种子精确复现，批产/法务追溯需求 —— 这类需求改用开源 + 固定 seed 的 ComfyUI 链。"
  "**--ow/--sw 默认不调**：一致性强度与需求错配 —— 按要风格 vs 要角色精调 --sw/--ow。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "midjourney-sref-cref-oref-decay--walkthrough"
fi
