#!/usr/bin/env bash
# topic-1.sh — 案例 决策助手 for Web 线上展览开发 (虚拟展厅).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web 线上展览开发 (虚拟展厅)"
TOPIC="案例"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 7 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 案例 主题下的 playbook 规则组合成交互树。

基于 7 条规则:
  • 如果 自研 vs SaaS 按定制/周期/锁定选 → 则 ：怕锁定选可导出(3DVista)或可 OEM(酷雷曼)。案例：两周上线的营销快闪展 → SaaS 快搭；品牌旗舰长期迭
  • 如果 上线前必跑 `gltf-transform optimize` → 则 ：Draco/Meshopt 几何降 ~90-95% + KTX2 纹理省约 10× 显存。案例：单张 4K 贴图 64
  • 如果 draw call 压到 <100/帧，重复展品合批 → 则 ：用 InstancedMesh/BatchedMesh。案例：一个摆了上千件相同展品的展厅 9000 draw cal
  • 如果 先定位真瓶颈再优化，别盲优化 → 则 ：用 `renderer.info`/Spector.js 看 draw call/显存/帧时间。案例：以为卡在面数，实
  • 如果 移动端当默认 → 则 ：pixelRatio=1、`.dispose()` 防泄漏、首屏分级加载、WebGL 降级。案例：iOS Safari
  • 如果 动线/热点设计先于建模 → 则 ：没有导览动线的 3D 空间=用户迷路。案例：进场先给引导动线 + 热点指引，而不是把用户丢进一个空房间自己找。evid
  • 如果 WebGPU/TSL 可上但带 WebGL2 fallback，高斯泼溅观望 → 则 ：KHR splat 扩展仍 RC。案例：新项目用 WebGPU/TSL 提性能，但 `navigator.gpu` 判

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "自研 vs SaaS 按定制/周期/锁定选"
  "上线前必跑 \`gltf-transform optimize\`"
  "draw call 压到 <100/帧，重复展品合批"
  "先定位真瓶颈再优化，别盲优化"
  "移动端当默认"
  "动线/热点设计先于建模"
  "WebGPU/TSL 可上但带 WebGL2 fallback，高斯泼溅观望"
)
declare -a RULE_ACTIONS=(
  "：怕锁定选可导出(3DVista)或可 OEM(酷雷曼)。案例：两周上线的营销快闪展 → SaaS 快搭；品牌旗舰长期迭代 → 自研 Three.js/R3F。evidence: [T02-S006, T06-S003]"
  "：Draco/Meshopt 几何降 ~90-95% + KTX2 纹理省约 10× 显存。案例：单张 4K 贴图 64MB+ 直接让移动端崩 → KTX2 转码后降到几 MB，手机能开了。evidence: [T03-S004, T02-S001]"
  "：用 InstancedMesh/BatchedMesh。案例：一个摆了上千件相同展品的展厅 9000 draw call 卡死 → 合批到 ~300，帧率回稳。evidence: [T03-S004, T02-S001]"
  "：用 \`renderer.info\`/Spector.js 看 draw call/显存/帧时间。案例：以为卡在面数，实测是纹理显存爆 → 先压纹理而非减面。evidence: [T03-S004, T02-S001]"
  "：pixelRatio=1、\`.dispose()\` 防泄漏、首屏分级加载、WebGL 降级。案例：iOS Safari 白屏 → 加 \`navigator.gpu\` 判空降 WebGL2 + 控显存，恢复显示。案例验证以真机为准。evidence: [T03-S006, T04-S010]"
  "：没有导览动线的 3D 空间=用户迷路。案例：进场先给引导动线 + 热点指引，而不是把用户丢进一个空房间自己找。evidence: [T03-S001, T06-S001]"
  "：KHR splat 扩展仍 RC。案例：新项目用 WebGPU/TSL 提性能，但 \`navigator.gpu\` 判空自动降 WebGL2，别裸用。evidence: [T04-S003, T03-S008]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
