#!/usr/bin/env bash
# topic-2.sh — 全景 决策助手 for Web 线上展览开发 (虚拟展厅).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web 线上展览开发 (虚拟展厅)"
TOPIC="全景"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 全景 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 先定真 3D 还是全景（要不要走动 + 交互） → 则 ：只站点看图 → 全景；要绕看/走进/拾取 → 真 3D。案例：一个雕塑展要观众绕着看每个角度 → 真 3D（Three
  • 如果 全景项目别承诺 3D 交互 → 则 ：避免验收翻车。案例：客户拍了 720 全景却要"走进去拿起展品" → 立项就讲清全景做不到，要交互得改真 3D。evi

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "先定真 3D 还是全景（要不要走动 + 交互）"
  "全景项目别承诺 3D 交互"
)
declare -a RULE_ACTIONS=(
  "：只站点看图 → 全景；要绕看/走进/拾取 → 真 3D。案例：一个雕塑展要观众绕着看每个角度 → 真 3D（Three.js），而不是 720 全景拼图。evidence: [T02-S005, T06-S002]"
  "：避免验收翻车。案例：客户拍了 720 全景却要\"走进去拿起展品\" → 立项就讲清全景做不到，要交互得改真 3D。evidence: [T06-S002, T02-S005]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
