#!/usr/bin/env bash
# topic-1.sh — 案例 决策助手 for DevOps 与 SRE.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="DevOps 与 SRE"
TOPIC="案例"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 10 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 案例 主题下的 playbook 规则组合成交互树。

基于 10 条规则:
  • 如果 服务上线但没有可靠性目标 / 告警全是 cause-based 噪音 / dev 与 SRE 在"发功能还是修稳定"扯皮 → 则 : 则 选 user-facing SLI → 定一个用户无感的 SLO (不是越高越好) → 算 error budg
  • 如果 change failure rate 高、团队想"少发布更安全" → 则 : 则 答案不是少发布, 而是减小批量 + 自动化测试 + 自动回滚 + 渐进式发布 + trunk-based。案例:
  • 如果 生产正在受损 (事件战时) → 则 : 则 先止血 (回滚 / 切流量 / 降级 / 扩容), root cause TBD, 永不 fix-and-lea
  • 如果 一个达到门槛的事件解决后 (通常 SEV-2+) → 则 : 则 开 blameless 复盘 — 列 ≥ 3 个贡献因素而非单一 root cause, 追问"为什么难检测/难
  • 如果 要新建/修改/删除基础设施资源 → 则 : 则 写声明式代码 → 远程加密加锁 state → `plan` 预演 → code+plan review (尤其
  • 如果 要配一条告警 → 则 : 则 必须基于用户感知的 symptom (四个黄金信号 / SLO burn-rate) 且 actionable 
  • 如果 某运维任务手工、重复、且随服务规模线性增长 → 则 : 则 标记为 toil、量化耗时、列入自动化 backlog (不是"有空再做"), 目标 toil < 50% 时间
  • 如果 想做混沌工程 / game day → 则 : 则 先定义稳态 (可量化的"正常") + 提假设 + 最小化爆炸半径 + 准备自动 abort, 而非随机砍服务; 
  • 如果 是小团队 (<10 人) / 刚起步 / 验证想法 → 则 : 则 默认托管 PaaS (Cloud Run/ECS/Fly.io) + GitHub Actions + 云原生托
  • 如果 选可观测性/云/IaC 工具 → 则 : 则 用厂商中立标准层防锁定 — OTel 之于可观测性、Terraform/OpenTofu 之于云、K8s 之于编

相关心智模型:
  • 错误预算思维 — 可靠性是产品决策, 不是技术债; 100% 是错误的目标: 可靠性不是越高越好 — `error budget = 1 - SLO` 是一笔可花的预算, 它把"该发功能还是修可靠性"从情绪/道德争论变成 dev/SRE/产品三方共享的数字决策; 盲目追 100
  • 小批量高频部署 > 少发布 (反直觉) — 速度与稳定不是 trade-off: 直觉是"少发布就少出事", 但 DORA 用 23,000+ 受访者的统计学证明这是错的 — 低部署频率 = 大批量变更 = 更高 change failure rate + 更难定位; elite 

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "服务上线但没有可靠性目标 / 告警全是 cause-based 噪音 / dev 与 SRE 在\"发功能还是修稳定\"扯皮"
  "change failure rate 高、团队想\"少发布更安全\""
  "生产正在受损 (事件战时)"
  "一个达到门槛的事件解决后 (通常 SEV-2+)"
  "要新建/修改/删除基础设施资源"
  "要配一条告警"
  "某运维任务手工、重复、且随服务规模线性增长"
  "想做混沌工程 / game day"
  "是小团队 (<10 人) / 刚起步 / 验证想法"
  "选可观测性/云/IaC 工具"
)
declare -a RULE_ACTIONS=(
  ": 则 选 user-facing SLI → 定一个用户无感的 SLO (不是越高越好) → 算 error budget → 写\"烧光就冻结发布\"的 policy (跨 dev/SRE/产品签字)。案例: Google SRE 把 100% 列为错误目标, 99.9% vs 99.99% 用户多半无感, 余下预算用来发功能 (T03-S002 / T04-S001)"
  ": 则 答案不是少发布, 而是减小批量 + 自动化测试 + 自动回滚 + 渐进式发布 + trunk-based。案例: DORA Accelerate 证明 elite performer 部署更频繁 AND 更稳定, 速度与稳定不是 trade-off (T03-S029 / T04-S009)"
  ": 则 先止血 (回滚 / 切流量 / 降级 / 扩容), root cause TBD, 永不 fix-and-learn 同时进行。案例: Knight Capital 2012 边查边亏 45 分钟 4.4 亿美元破产; 资深 IC 严守 \"let's not fix and learn at the same time\" (T03-S010)"
  ": 则 开 blameless 复盘 — 列 ≥ 3 个贡献因素而非单一 root cause, 追问\"为什么难检测/难止血\", action items 必带 owner + 日期 + 闭环。案例: GitLab 2017 误删生产主库 + 5 层备份全失效, 正确复盘不骂工程师而落在\"备份必须验证恢复 + 危险操作防呆\" (T03-S028 / T04-S020)"
  ": 则 写声明式代码 → 远程加密加锁 state → \`plan\` 预演 → code+plan review (尤其 destroy) → \`apply\` → 定时 drift 检测; 禁手改控制台。案例: AWS S3 us-east-1 2017 一条命令 typo 多删服务器引发大面积故障, 教训是危险操作要有防呆 + 预览 (T03-S016 / T04-S028)"
  ": 则 必须基于用户感知的 symptom (四个黄金信号 / SLO burn-rate) 且 actionable (有人能立刻做某事), 否则删掉或降级为 ticket/dashboard。案例: alert fatigue 是管理失败不是个人韧性问题, \"这个告警一直响先静音吧\"是漏报真事故的温床 (T03-S032 / T04-S001)"
  ": 则 标记为 toil、量化耗时、列入自动化 backlog (不是\"有空再做\"), 目标 toil < 50% 时间。案例: SRE 把削减 toil 当 mandate, 把救火加班当美德是组织失败信号 (T03-S005 / T06-S003)"
  ": 则 先定义稳态 (可量化的\"正常\") + 提假设 + 最小化爆炸半径 + 准备自动 abort, 而非随机砍服务; 且 chaos 前先验证基本功 (备份能恢复、告警 actionable、能回滚)。案例: Cloudflare 2019 一条 WAF 正则灾难性回溯 100% CPU 全球宕机, game day 正可暴露这类\"全量推送\"风险 (T03-S025 / T04-S025)"
  ": 则 默认托管 PaaS (Cloud Run/ECS/Fly.io) + GitHub Actions + 云原生托管监控, 别为\"显得专业\"上 K8s + service mesh + multi-cloud。案例: DORA 2025 强调平台质量 > 工具先进度, 小团队的可靠性瓶颈是基本功不是工具栈复杂度, \"do you really need Kubernetes for this\" (T02-S060 / T02-S049)"
  ": 则 用厂商中立标准层防锁定 — OTel 之于可观测性、Terraform/OpenTofu 之于云、K8s 之于编排; instrument/声明一次, 后端/云可换, 别把 instrument code 绑死厂商 SDK。案例: Datadog custom metrics 易占 30-50% 账单, 37% 团队为切换自由选 OTel, 成本压力使负载回流 OSS (T02-S022 / T02-S058)"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
