#!/usr/bin/env bash
# evidence.sh — Evidence 决策助手 for 影视编剧 (Scriptwriting / Screenwriting) — 为电影 / 电视 / 流媒体剧集写戏剧蓝本的从业者认知操作系统: 决定「讲什么故事、人物是谁为何转变、场景如何被戏剧化、主题为何重要」的学科 —— 区别于导演 (调度 / 视觉实现)、制片 (融资 / 排期)、小说 (无格式 / 场景 / 视觉动作约束)。覆盖 (a) 故事与结构理论 (亚里士多德《诗学》情节 / 人物 / 思想 + 突转 peripeteia / 发现 anagnorisis + 净化 catharsis; Syd Field 范式 / 三幕 / 情节点; Freytag 金字塔; Egri 前提; McKee《故事》掌控性理念 / 鸿沟 / 价值正负转变 / 激励事件 / 渐进式复杂化; Truby《故事剖析》22 步 + 道德论证; Vogler/Campbell 英雄之旅; Blake Snyder《救猫咪》15 拍节拍表; Dan Harmon 故事环; John Yorke 五幕《进入森林》; Frank Daniel 八序列法; 起承转合东亚戏剧结构), (b) 人物 (想要 vs 需要 / 外在目标 vs 内在缺失, 人物弧光 正 / 负 / 平, flaw-wound-ghost 创伤背景, 主动 vs 被动主角的能动性, Egri 三维人物 生理 / 社会 / 心理, 反派是主角的镜子, 群像与关系网, 人物在压力下的选择中显形), (c) 对白 (潜台词 subtext, 对白即动作与冲突而非信息, 避免太直白 on the nose, 人物独特声口, 信息植入 exposition, Mamet/Sorkin 意图-阻碍式对白, 展示而非告知, 中文剧台词工艺), (d) 场景与序列工艺 (场景是有目标 / 冲突 / 转折的微型故事, 场景价值充能与转折点, 晚进早出, 八序列法, set piece, 转场, 场景头 / 动作行 / 括号提示 格式工艺), (e) 主题与前提 (掌控性理念 / 前提, 主题是被戏剧化的论证而非说教, 道德论证 Truby, 主题统一性, 这到底在讲什么), (f) 类型 (类型惯例是对观众的承诺, Snyder 10 类故事, 颠覆 vs 尊重套路, 类型片 vs 文艺片, 中国类型 主旋律 / 古装 / 年代 / 悬疑 / 甜宠 / 都市 / 军旅 / 历史正剧), (g) 格式与工业流程 (好莱坞剧本格式与 Final Draft, logline 一句话故事, treatment 故事大纲, 节拍表, 分场 / 分集大纲, spec 原创剧本 vs 委托, pitch, coverage, 美剧编剧室与 showrunner 制; 中国 大纲→人物小传→分集大纲→剧本, 长剧集 40 集结构, 网络电影 / 网大, 分账剧, 平台定制剧, 微短剧竖屏短剧), (h) 改稿与开发 (写作就是改写, 改稿 / 润色 / 推倒重写, 处理意见 / 改稿意见, 片方与平台 notes, 杀死你的宝贝, 围读, 开发地狱), (i) 改编 (IP改编 小说 / 漫画 / 游戏改编, 忠于精神而非字句, 压缩, 中国网文 IP 热), (j) 中国影视编剧产业现实 (审查 / 广电总局约束, 备案 / 立项, 平台定制剧 爱优腾芒, 分账, 编剧维权 署名权 / 欠薪 / 枪手, 注水剧, 流量 + 大IP 资本逻辑 vs 原创工艺, 导演中心制 vs 编剧话语权), (k) 编剧职业与工艺生涯 (spec vs 委托, 编剧 vs 编审 / 策划, 单兵 vs 编剧室, 在开发链条中的位置, WGA 与署名仲裁规范, 入行, 中国编剧地位与权益)。跨 电影 / 美剧流媒体 / 中国电影与长剧集。不含 导演 / 摄影 / 制片 / 融资 / 表演 / 电影理论批评为终点 / 泛小说写作 / 纪录片 / 新闻 —— 本 skill 是「戏剧化编剧」工艺: 故事 / 人物 / 场景 / 对白 / 主题 / 结构 / 格式 与围绕它们的产业流程。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="影视编剧 (Scriptwriting / Screenwriting) — 为电影 / 电视 / 流媒体剧集写戏剧蓝本的从业者认知操作系统: 决定「讲什么故事、人物是谁为何转变、场景如何被戏剧化、主题为何重要」的学科 —— 区别于导演 (调度 / 视觉实现)、制片 (融资 / 排期)、小说 (无格式 / 场景 / 视觉动作约束)。覆盖 (a) 故事与结构理论 (亚里士多德《诗学》情节 / 人物 / 思想 + 突转 peripeteia / 发现 anagnorisis + 净化 catharsis; Syd Field 范式 / 三幕 / 情节点; Freytag 金字塔; Egri 前提; McKee《故事》掌控性理念 / 鸿沟 / 价值正负转变 / 激励事件 / 渐进式复杂化; Truby《故事剖析》22 步 + 道德论证; Vogler/Campbell 英雄之旅; Blake Snyder《救猫咪》15 拍节拍表; Dan Harmon 故事环; John Yorke 五幕《进入森林》; Frank Daniel 八序列法; 起承转合东亚戏剧结构), (b) 人物 (想要 vs 需要 / 外在目标 vs 内在缺失, 人物弧光 正 / 负 / 平, flaw-wound-ghost 创伤背景, 主动 vs 被动主角的能动性, Egri 三维人物 生理 / 社会 / 心理, 反派是主角的镜子, 群像与关系网, 人物在压力下的选择中显形), (c) 对白 (潜台词 subtext, 对白即动作与冲突而非信息, 避免太直白 on the nose, 人物独特声口, 信息植入 exposition, Mamet/Sorkin 意图-阻碍式对白, 展示而非告知, 中文剧台词工艺), (d) 场景与序列工艺 (场景是有目标 / 冲突 / 转折的微型故事, 场景价值充能与转折点, 晚进早出, 八序列法, set piece, 转场, 场景头 / 动作行 / 括号提示 格式工艺), (e) 主题与前提 (掌控性理念 / 前提, 主题是被戏剧化的论证而非说教, 道德论证 Truby, 主题统一性, 这到底在讲什么), (f) 类型 (类型惯例是对观众的承诺, Snyder 10 类故事, 颠覆 vs 尊重套路, 类型片 vs 文艺片, 中国类型 主旋律 / 古装 / 年代 / 悬疑 / 甜宠 / 都市 / 军旅 / 历史正剧), (g) 格式与工业流程 (好莱坞剧本格式与 Final Draft, logline 一句话故事, treatment 故事大纲, 节拍表, 分场 / 分集大纲, spec 原创剧本 vs 委托, pitch, coverage, 美剧编剧室与 showrunner 制; 中国 大纲→人物小传→分集大纲→剧本, 长剧集 40 集结构, 网络电影 / 网大, 分账剧, 平台定制剧, 微短剧竖屏短剧), (h) 改稿与开发 (写作就是改写, 改稿 / 润色 / 推倒重写, 处理意见 / 改稿意见, 片方与平台 notes, 杀死你的宝贝, 围读, 开发地狱), (i) 改编 (IP改编 小说 / 漫画 / 游戏改编, 忠于精神而非字句, 压缩, 中国网文 IP 热), (j) 中国影视编剧产业现实 (审查 / 广电总局约束, 备案 / 立项, 平台定制剧 爱优腾芒, 分账, 编剧维权 署名权 / 欠薪 / 枪手, 注水剧, 流量 + 大IP 资本逻辑 vs 原创工艺, 导演中心制 vs 编剧话语权), (k) 编剧职业与工艺生涯 (spec vs 委托, 编剧 vs 编审 / 策划, 单兵 vs 编剧室, 在开发链条中的位置, WGA 与署名仲裁规范, 入行, 中国编剧地位与权益)。跨 电影 / 美剧流媒体 / 中国电影与长剧集。不含 导演 / 摄影 / 制片 / 融资 / 表演 / 电影理论批评为终点 / 泛小说写作 / 纪录片 / 新闻 —— 本 skill 是「戏剧化编剧」工艺: 故事 / 人物 / 场景 / 对白 / 主题 / 结构 / 格式 与围绕它们的产业流程。"
TOPIC="Evidence"

usage() {
  cat <<EOF
evidence.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 7 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./evidence.sh             # interactive
  ./evidence.sh --dry-run   # walk through but no file
  ./evidence.sh --json      # JSON to stdout
  ./evidence.sh --explain   # show backing playbook rules + mental models
  ./evidence.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Evidence 主题下的 playbook 规则组合成交互树。

基于 7 条规则:
  • 如果 主角的想要和需要不冲突 → 则 : 则人物立不住 — 回头给主角一个 flaw (致命缺陷) 和一个 wound (创伤),让外在目标和内在需要拉扯。案
  • 如果 一场戏读完没有价值翻转 → 则 : 则删或重写 — 问 Mamet 三问 (角色想要什么/障碍/价值转了吗),三答不出就剪。案例: 《社交网络》每场存证
  • 如果 收到改稿意见 (notes) → 则 : 则不要照改 — 找 note behind the note (真问题而非表面指令)。片方说「第二幕太慢」,真问题可
  • 如果 logline 用一句话说不清主角+冲突+风险 → 则 : 则概念不够锋利 — 回头重想,不要急着写大纲。Logline 是压力测试。案例: Alien 的 logline 「
  • 如果 故事结构出问题,优先查第一幕 → 则 : 则激励事件位置或主角目标可能没定清 — 第二幕坍塌 (约 90% 编剧 自称难点, 业内估) 的根因多在第一幕。案例
  • 如果 入行编剧 → 则 : 则写 spec (原创) 而非等委托 — 无名编剧靠 spec 证明能力; 投 Black List/竞赛/agen
  • 如果 做中国长剧集项目 → 则 : 则审查判断前置到选题阶段 — 不要写完 40 集再发现拍不了;备案/立项/龙标是硬约束,提前评估题材红线。案例: 广

相关心智模型:
  • 想要 vs 需要 (Want vs Need — 人物弧光的发动机): 主角的外在目标 (想要) 与内在缺失 (需要) 之间的鸿沟驱动一切戏剧张力 — 弧光不是角色变好,是角色认清自己真正需要什么
  • 每场戏必须转 (Scene Value Charge — 场景诊断的唯一标准): 一场戏读完,如果某个价值 (爱/恨、希望/绝望、自由/困境) 没有从正翻到负或从负翻到正,这场戏就没有存在理由 — 删或重写

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "主角的想要和需要不冲突"
  "一场戏读完没有价值翻转"
  "收到改稿意见 (notes)"
  "logline 用一句话说不清主角+冲突+风险"
  "故事结构出问题,优先查第一幕"
  "入行编剧"
  "做中国长剧集项目"
)
declare -a RULE_ACTIONS=(
  ": 则人物立不住 — 回头给主角一个 flaw (致命缺陷) 和一个 wound (创伤),让外在目标和内在需要拉扯。案例: Walter White 想要 (给家人留钱) vs 需要 (被世界承认) evidence: [T04-S009, T01-S006]"
  ": 则删或重写 — 问 Mamet 三问 (角色想要什么/障碍/价值转了吗),三答不出就剪。案例: 《社交网络》每场存证会戏都翻转权力关系 evidence: [T04-S007, T01-S014]"
  ": 则不要照改 — 找 note behind the note (真问题而非表面指令)。片方说「第二幕太慢」,真问题可能是「主角目标不清」。案例: Craig Mazin 谈 Chernobyl notes evidence: [T01-S019, T04-S021]"
  ": 则概念不够锋利 — 回头重想,不要急着写大纲。Logline 是压力测试。案例: Alien 的 logline 「太空中没人听到你的尖叫」 evidence: [T04-S021, T03-S004]"
  ": 则激励事件位置或主角目标可能没定清 — 第二幕坍塌 (约 90% 编剧 自称难点, 业内估) 的根因多在第一幕。案例: McKee 讲「第二幕问题向第一幕找答案」 evidence: [T04-S007, T01-S001]"
  ": 则写 spec (原创) 而非等委托 — 无名编剧靠 spec 证明能力; 投 Black List/竞赛/agent,spec 是入场券。案例: Diablo Cody《朱诺》spec → Oscar evidence: [T03-S023, T02-S001]"
  ": 则审查判断前置到选题阶段 — 不要写完 40 集再发现拍不了;备案/立项/龙标是硬约束,提前评估题材红线。案例: 广电总局题材引导目录 evidence: [T03-S012, T06-S033]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "evidence-decision"
fi
