#!/usr/bin/env bash
# run-a-balancing-and-tuning-pass.sh — Run a Balancing and Tuning Pass SOP walkthrough for 游戏设计 (Game Design) — 设计游戏的规则 / 系统 / 机制 / 体验 的从业者认知操作系统 (以电子游戏为主, 含桌游 / 卡牌 / 棋盘游戏): 决定「玩家做什么、为什么有意义、每一刻的体验如何」的学科 —— 区别于游戏程序 (引擎 / 代码)、游戏美术 (视觉 / 音频)、游戏制作 (排期 / 预算 / 团队)。覆盖 (a) 核心设计理论与框架 (MDA 机制-动态-美学 Hunicke/LeBlanc/Zubek + Schell 的「透镜」+ Koster「乐趣即学习」理论 + Sid Meier「一连串有趣的决策」+ Salen & Zimmerman「有意义的游玩」/「二阶设计」/「魔法圈」+ Costikyan 论不确定性 + Suits/Huizinga 游戏哲学), (b) 系统与机制设计 (核心循环 + 游戏经济 sink/source/产出-消耗 + 正负反馈环 + 资源与成长系统 + 涌现 vs 脚本 Will Wright「可能性空间」+ Machinations 经济建模 Dormans + 支配 / 退化策略 + 正交设计 Garfield), (c) 关卡与遭遇设计 (灰盒 blockout + 节奏与张力 + 预告 telegraphing + 主线 vs 探索 + 环境叙事 + 锁钥 gating + 难度曲线), (d) 游戏手感与「juice」(Steve Swink《Game Feel》+ 即时响应 + 屏震 / 反馈 / 打磨 + 输入与镜头 + 「手感」是设计出来的不是附带的), (e) 玩家心理与 UX (Celia Hodent《The Gamer's Brain》+ 心流通道 挑战 vs 技能 Csikszentmihalyi/陈星汉 Jenova Chen + Bartle 玩家类型 + 动机与奖励节奏 + 新手引导 FTUE / 教学化 + 认知负荷 + 无障碍), (f) 平衡与调优 (Ian Schreiber《Game Balance》+ 对称 / 非对称 + 动态难度 DDA + 传递 / 非传递平衡 + nerf/buff + 消除支配策略 + 测试驱动调优), (g) 叙事与任务设计 (ludonarrative 失调 / 和谐 + 环境与系统叙事 + 分支 vs 线性 + Amy Hennig 角色驱动 + 任务结构), (h) 以玩家为中心的迭代流程 (Tracy Fullerton《Game Design Workshop》playcentric + 纸面原型 + 垂直切片 + 测试协议「看而不说 / 你不是你的玩家」+ 快速迭代 + game jam), (i) 类型与形态工艺 (roguelike/roguelite 与程序生成 Derek Yu + 平台跳跃 + RPG 系统 + 策略 4X + 解谜设计 Jonathan Blow + 多人 / PvP 平衡 + 桌游 / 卡牌设计 Reiner Knizia/Richard Garfield/Brenda Romero), (j) F2P / 长线运营 / 商业化设计 (核心 / 元 / 经济循环 + 抽卡 gacha / 开箱 loot box / 战令 battle pass 机制 + 留存 D1/D7/D30 + 转化 + 鲸鱼 + live ops 内容节奏 —— 并诚实处理掠夺式暗黑模式 / 强迫循环 / 剥削式商业化的伦理), (k) 设计师角色与工艺职业 (系统 / 关卡 / 叙事 / UX 设计师之分 + 通才 vs 专才 + 独立作者 vs 3A 团队 + 设计文档 + 传达设计意图 + GDC 工艺社区)。跨 3A / 独立 / 手游 F2P / 桌游。不含 游戏程序 / 引擎 (Unity/Unreal 编码 / 图形 / 网络同步) / 游戏美术 / 动画 / 音频 / 游戏制作 / 项目管理 / 排期 / QA / 游戏作为生意 / 发行 / 市场 / 电竞运营为终点 / 泛泛「我想做游戏」的 game-dev 教程 —— 本 skill 是「设计」学科: 规则 / 系统 / 机制 / 体验。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="游戏设计 (Game Design) — 设计游戏的规则 / 系统 / 机制 / 体验 的从业者认知操作系统 (以电子游戏为主, 含桌游 / 卡牌 / 棋盘游戏): 决定「玩家做什么、为什么有意义、每一刻的体验如何」的学科 —— 区别于游戏程序 (引擎 / 代码)、游戏美术 (视觉 / 音频)、游戏制作 (排期 / 预算 / 团队)。覆盖 (a) 核心设计理论与框架 (MDA 机制-动态-美学 Hunicke/LeBlanc/Zubek + Schell 的「透镜」+ Koster「乐趣即学习」理论 + Sid Meier「一连串有趣的决策」+ Salen & Zimmerman「有意义的游玩」/「二阶设计」/「魔法圈」+ Costikyan 论不确定性 + Suits/Huizinga 游戏哲学), (b) 系统与机制设计 (核心循环 + 游戏经济 sink/source/产出-消耗 + 正负反馈环 + 资源与成长系统 + 涌现 vs 脚本 Will Wright「可能性空间」+ Machinations 经济建模 Dormans + 支配 / 退化策略 + 正交设计 Garfield), (c) 关卡与遭遇设计 (灰盒 blockout + 节奏与张力 + 预告 telegraphing + 主线 vs 探索 + 环境叙事 + 锁钥 gating + 难度曲线), (d) 游戏手感与「juice」(Steve Swink《Game Feel》+ 即时响应 + 屏震 / 反馈 / 打磨 + 输入与镜头 + 「手感」是设计出来的不是附带的), (e) 玩家心理与 UX (Celia Hodent《The Gamer's Brain》+ 心流通道 挑战 vs 技能 Csikszentmihalyi/陈星汉 Jenova Chen + Bartle 玩家类型 + 动机与奖励节奏 + 新手引导 FTUE / 教学化 + 认知负荷 + 无障碍), (f) 平衡与调优 (Ian Schreiber《Game Balance》+ 对称 / 非对称 + 动态难度 DDA + 传递 / 非传递平衡 + nerf/buff + 消除支配策略 + 测试驱动调优), (g) 叙事与任务设计 (ludonarrative 失调 / 和谐 + 环境与系统叙事 + 分支 vs 线性 + Amy Hennig 角色驱动 + 任务结构), (h) 以玩家为中心的迭代流程 (Tracy Fullerton《Game Design Workshop》playcentric + 纸面原型 + 垂直切片 + 测试协议「看而不说 / 你不是你的玩家」+ 快速迭代 + game jam), (i) 类型与形态工艺 (roguelike/roguelite 与程序生成 Derek Yu + 平台跳跃 + RPG 系统 + 策略 4X + 解谜设计 Jonathan Blow + 多人 / PvP 平衡 + 桌游 / 卡牌设计 Reiner Knizia/Richard Garfield/Brenda Romero), (j) F2P / 长线运营 / 商业化设计 (核心 / 元 / 经济循环 + 抽卡 gacha / 开箱 loot box / 战令 battle pass 机制 + 留存 D1/D7/D30 + 转化 + 鲸鱼 + live ops 内容节奏 —— 并诚实处理掠夺式暗黑模式 / 强迫循环 / 剥削式商业化的伦理), (k) 设计师角色与工艺职业 (系统 / 关卡 / 叙事 / UX 设计师之分 + 通才 vs 专才 + 独立作者 vs 3A 团队 + 设计文档 + 传达设计意图 + GDC 工艺社区)。跨 3A / 独立 / 手游 F2P / 桌游。不含 游戏程序 / 引擎 (Unity/Unreal 编码 / 图形 / 网络同步) / 游戏美术 / 动画 / 音频 / 游戏制作 / 项目管理 / 排期 / QA / 游戏作为生意 / 发行 / 市场 / 电竞运营为终点 / 泛泛「我想做游戏」的 game-dev 教程 —— 本 skill 是「设计」学科: 规则 / 系统 / 机制 / 体验。"
WORKFLOW="Run a Balancing and Tuning Pass"

usage() {
  cat <<EOF
run-a-balancing-and-tuning-pass.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./run-a-balancing-and-tuning-pass.sh             # interactive
  ./run-a-balancing-and-tuning-pass.sh --dry-run
  ./run-a-balancing-and-tuning-pass.sh --json
  ./run-a-balancing-and-tuning-pass.sh --explain
  ./run-a-balancing-and-tuning-pass.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Run a Balancing and Tuning Pass" 工作流。

一句话: 找出并消灭支配/退化策略、修复僵化的元游戏——用数据 (遥测) + 观察 (playtest) 双轨定位「永远最优解」或「永远陷阱选项」，调整后验证元游戏健康。 (evidence: [T03-S011, T03-S012])

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 设计的是「体验」, 不是「产物」 — 从美学倒推, 间接控制: 游戏本身 (规则/关卡/代码) 只是手段, **目的是玩家脑中产生的体验**——而设计师只能**间接**控制它 (Schell: 你打造的是体验的「容器」, 不是体验本身)。MDA 框架把这条落成可操
  • 游戏是「一连串有趣的决策」 — 有意义的取舍, 没有显然最优: Sid Meier 的设计学科第一名言——**「a game is a series of interesting decisions」**。一个决策「有趣」的条件:① 有真实取舍 (每个选项都有得有

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "定位问题：从数据 (胜率/选取率/通关率) 找异常项——某角色/武器/build 选取率或胜率远超其他 = 嫌疑支配项。"
  "观察验证「为什么」：数据说「哪里」，去看 playtest/对局录像看「为什么」——是数值过强，还是机制无对策 (退化打法)。"
  "判定类型：是 transitive (线性强弱，调数值即可) 还是 intransitive (石头剪刀布被破，要补克制关系)？是难度还是设计失败 (false choice)？"
  "最小化调整：优先调数值 (nerf 强项/buff 弱项)，能不动机制就不动；Sid Meier「翻倍或砍半」找边界再收敛。"
  "重测元游戏健康：调完后是否出现新支配项 (打地鼠)？是否有 ≥2-3 个可行打法？是否消除了「无脑最优」。"
  "上线 + 监控：发版本，盯数据看玩家是否迁移到新支配项，准备下一轮迭代 (平衡是持续的，不是一次算对)。"
)
declare -a FAILURE_MODES=(
  "只看数据不看玩家：数字说某 build 选取率高就闷头 nerf，其实是它「好玩」不是「过强」，nerf 后玩家流失——数据定位「哪里」，必须配观察看「为什么」。"
  "打地鼠式过度调整：nerf 了 A，B 立刻成新支配项，每版本都在追——step 5 调完先模拟「下一个最优是谁」，整体调而非单点追。"
  "把 false choice 当深度卖：保留一个永远是陷阱的选项假装「选择丰富」——那不是有趣决策是欺骗 (newbie trap)，要么修要么删。"
  "动机制不动数值：能调数值解决的非要重做机制，引入更多未知失衡——优先最小数值调整，机制改动是最后手段。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "run-a-balancing-and-tuning-pass-walkthrough"
fi
