#!/usr/bin/env bash
# run-the-playtesting-protocol.sh — Run the Playtesting Protocol SOP walkthrough for 游戏设计 (Game Design) — 设计游戏的规则 / 系统 / 机制 / 体验 的从业者认知操作系统 (以电子游戏为主, 含桌游 / 卡牌 / 棋盘游戏): 决定「玩家做什么、为什么有意义、每一刻的体验如何」的学科 —— 区别于游戏程序 (引擎 / 代码)、游戏美术 (视觉 / 音频)、游戏制作 (排期 / 预算 / 团队)。覆盖 (a) 核心设计理论与框架 (MDA 机制-动态-美学 Hunicke/LeBlanc/Zubek + Schell 的「透镜」+ Koster「乐趣即学习」理论 + Sid Meier「一连串有趣的决策」+ Salen & Zimmerman「有意义的游玩」/「二阶设计」/「魔法圈」+ Costikyan 论不确定性 + Suits/Huizinga 游戏哲学), (b) 系统与机制设计 (核心循环 + 游戏经济 sink/source/产出-消耗 + 正负反馈环 + 资源与成长系统 + 涌现 vs 脚本 Will Wright「可能性空间」+ Machinations 经济建模 Dormans + 支配 / 退化策略 + 正交设计 Garfield), (c) 关卡与遭遇设计 (灰盒 blockout + 节奏与张力 + 预告 telegraphing + 主线 vs 探索 + 环境叙事 + 锁钥 gating + 难度曲线), (d) 游戏手感与「juice」(Steve Swink《Game Feel》+ 即时响应 + 屏震 / 反馈 / 打磨 + 输入与镜头 + 「手感」是设计出来的不是附带的), (e) 玩家心理与 UX (Celia Hodent《The Gamer's Brain》+ 心流通道 挑战 vs 技能 Csikszentmihalyi/陈星汉 Jenova Chen + Bartle 玩家类型 + 动机与奖励节奏 + 新手引导 FTUE / 教学化 + 认知负荷 + 无障碍), (f) 平衡与调优 (Ian Schreiber《Game Balance》+ 对称 / 非对称 + 动态难度 DDA + 传递 / 非传递平衡 + nerf/buff + 消除支配策略 + 测试驱动调优), (g) 叙事与任务设计 (ludonarrative 失调 / 和谐 + 环境与系统叙事 + 分支 vs 线性 + Amy Hennig 角色驱动 + 任务结构), (h) 以玩家为中心的迭代流程 (Tracy Fullerton《Game Design Workshop》playcentric + 纸面原型 + 垂直切片 + 测试协议「看而不说 / 你不是你的玩家」+ 快速迭代 + game jam), (i) 类型与形态工艺 (roguelike/roguelite 与程序生成 Derek Yu + 平台跳跃 + RPG 系统 + 策略 4X + 解谜设计 Jonathan Blow + 多人 / PvP 平衡 + 桌游 / 卡牌设计 Reiner Knizia/Richard Garfield/Brenda Romero), (j) F2P / 长线运营 / 商业化设计 (核心 / 元 / 经济循环 + 抽卡 gacha / 开箱 loot box / 战令 battle pass 机制 + 留存 D1/D7/D30 + 转化 + 鲸鱼 + live ops 内容节奏 —— 并诚实处理掠夺式暗黑模式 / 强迫循环 / 剥削式商业化的伦理), (k) 设计师角色与工艺职业 (系统 / 关卡 / 叙事 / UX 设计师之分 + 通才 vs 专才 + 独立作者 vs 3A 团队 + 设计文档 + 传达设计意图 + GDC 工艺社区)。跨 3A / 独立 / 手游 F2P / 桌游。不含 游戏程序 / 引擎 (Unity/Unreal 编码 / 图形 / 网络同步) / 游戏美术 / 动画 / 音频 / 游戏制作 / 项目管理 / 排期 / QA / 游戏作为生意 / 发行 / 市场 / 电竞运营为终点 / 泛泛「我想做游戏」的 game-dev 教程 —— 本 skill 是「设计」学科: 规则 / 系统 / 机制 / 体验。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="游戏设计 (Game Design) — 设计游戏的规则 / 系统 / 机制 / 体验 的从业者认知操作系统 (以电子游戏为主, 含桌游 / 卡牌 / 棋盘游戏): 决定「玩家做什么、为什么有意义、每一刻的体验如何」的学科 —— 区别于游戏程序 (引擎 / 代码)、游戏美术 (视觉 / 音频)、游戏制作 (排期 / 预算 / 团队)。覆盖 (a) 核心设计理论与框架 (MDA 机制-动态-美学 Hunicke/LeBlanc/Zubek + Schell 的「透镜」+ Koster「乐趣即学习」理论 + Sid Meier「一连串有趣的决策」+ Salen & Zimmerman「有意义的游玩」/「二阶设计」/「魔法圈」+ Costikyan 论不确定性 + Suits/Huizinga 游戏哲学), (b) 系统与机制设计 (核心循环 + 游戏经济 sink/source/产出-消耗 + 正负反馈环 + 资源与成长系统 + 涌现 vs 脚本 Will Wright「可能性空间」+ Machinations 经济建模 Dormans + 支配 / 退化策略 + 正交设计 Garfield), (c) 关卡与遭遇设计 (灰盒 blockout + 节奏与张力 + 预告 telegraphing + 主线 vs 探索 + 环境叙事 + 锁钥 gating + 难度曲线), (d) 游戏手感与「juice」(Steve Swink《Game Feel》+ 即时响应 + 屏震 / 反馈 / 打磨 + 输入与镜头 + 「手感」是设计出来的不是附带的), (e) 玩家心理与 UX (Celia Hodent《The Gamer's Brain》+ 心流通道 挑战 vs 技能 Csikszentmihalyi/陈星汉 Jenova Chen + Bartle 玩家类型 + 动机与奖励节奏 + 新手引导 FTUE / 教学化 + 认知负荷 + 无障碍), (f) 平衡与调优 (Ian Schreiber《Game Balance》+ 对称 / 非对称 + 动态难度 DDA + 传递 / 非传递平衡 + nerf/buff + 消除支配策略 + 测试驱动调优), (g) 叙事与任务设计 (ludonarrative 失调 / 和谐 + 环境与系统叙事 + 分支 vs 线性 + Amy Hennig 角色驱动 + 任务结构), (h) 以玩家为中心的迭代流程 (Tracy Fullerton《Game Design Workshop》playcentric + 纸面原型 + 垂直切片 + 测试协议「看而不说 / 你不是你的玩家」+ 快速迭代 + game jam), (i) 类型与形态工艺 (roguelike/roguelite 与程序生成 Derek Yu + 平台跳跃 + RPG 系统 + 策略 4X + 解谜设计 Jonathan Blow + 多人 / PvP 平衡 + 桌游 / 卡牌设计 Reiner Knizia/Richard Garfield/Brenda Romero), (j) F2P / 长线运营 / 商业化设计 (核心 / 元 / 经济循环 + 抽卡 gacha / 开箱 loot box / 战令 battle pass 机制 + 留存 D1/D7/D30 + 转化 + 鲸鱼 + live ops 内容节奏 —— 并诚实处理掠夺式暗黑模式 / 强迫循环 / 剥削式商业化的伦理), (k) 设计师角色与工艺职业 (系统 / 关卡 / 叙事 / UX 设计师之分 + 通才 vs 专才 + 独立作者 vs 3A 团队 + 设计文档 + 传达设计意图 + GDC 工艺社区)。跨 3A / 独立 / 手游 F2P / 桌游。不含 游戏程序 / 引擎 (Unity/Unreal 编码 / 图形 / 网络同步) / 游戏美术 / 动画 / 音频 / 游戏制作 / 项目管理 / 排期 / QA / 游戏作为生意 / 发行 / 市场 / 电竞运营为终点 / 泛泛「我想做游戏」的 game-dev 教程 —— 本 skill 是「设计」学科: 规则 / 系统 / 机制 / 体验。"
WORKFLOW="Run the Playtesting Protocol"

usage() {
  cat <<EOF
run-the-playtesting-protocol.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./run-the-playtesting-protocol.sh             # interactive
  ./run-the-playtesting-protocol.sh --dry-run
  ./run-the-playtesting-protocol.sh --json
  ./run-the-playtesting-protocol.sh --explain
  ./run-the-playtesting-protocol.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Run the Playtesting Protocol" 工作流。

一句话: 用纪律化的协议拿到玩家真实体验——招代表性陌生玩家 → watch-don't-talk / don't-lead-the-witness → 记 blocker 不记意见 → 三角化 triage，区分「你以为好玩」与「玩家实际体验」。 (evidence: [T03-S001, T03-S015])

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 设计的是「体验」, 不是「产物」 — 从美学倒推, 间接控制: 游戏本身 (规则/关卡/代码) 只是手段, **目的是玩家脑中产生的体验**——而设计师只能**间接**控制它 (Schell: 你打造的是体验的「容器」, 不是体验本身)。MDA 框架把这条落成可操
  • 游戏是「一连串有趣的决策」 — 有意义的取舍, 没有显然最优: Sid Meier 的设计学科第一名言——**「a game is a series of interesting decisions」**。一个决策「有趣」的条件:① 有真实取舍 (每个选项都有得有

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "定测试目标与代表性玩家：想验什么 (onboarding? 难度? fun?)，招符合目标人群的陌生玩家——不是开发者朋友 (你不是你的玩家，朋友也不是)。"
  "设最小引导：给玩家应得的最少信息 (像他们在真实环境拿到的)，然后闭嘴。"
  "Watch don't talk：观察玩家实际行为——卡在哪、误解什么、何时困惑/弃坑；绝不提示、绝不引导 (don't lead the witness)。"
  "记 blocker 不记意见：记「他在第 3 关卡了 5 分钟找不到门」(行为)，不记「他说关卡有点难」(意见)——玩家诊断不可信，玩家行为可信。"
  "测后访谈 (放最后)：问开放问题 (「刚才哪段最迷茫」)，但权重远低于观察到的行为。"
  "三角化 triage：多个玩家在同一处卡 = 真问题优先修；单人卡可能是个体差异——按「多少玩家撞同一墙」排序。"
)
declare -a FAILURE_MODES=(
  "提示/引导测试者 (lead the witness)：玩家一卡你就忍不住说「点那个」，于是永远看不到真实卡点——闭嘴，让他卡，记下来。"
  "记意见不记行为：写「玩家说难度还行」却没记他第 2 关死了 8 次——玩家嘴上的评价和实际行为常矛盾，只信行为。"
  "用熟人/开发者当测试者：他们懂意图、不忍批评，给你虚假信号——招真正不认识你的代表性玩家。"
  "采纳玩家的解决方案：玩家说「应该加个箭头指路」你就加箭头，其实真问题是关卡可读性差——挖痛点根因，别让玩家当设计师。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "run-the-playtesting-protocol-walkthrough"
fi
