#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 临床诊断思维.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="临床诊断思维"
DIM_COUNT=6

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (6 个):
  9.1 问题表征
  9.2 鉴别诊断生成与排序
  9.3 概率与定向检验
  9.4 安全网与不确定性沟通
  9.5 偏倚与元认知检查
  9.6 证据强度与边界标注

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "问题表征"
  "鉴别诊断生成与排序"
  "概率与定向检验"
  "安全网与不确定性沟通"
  "偏倚与元认知检查"
  "证据强度与边界标注"
)
declare -a DIM_QUESTIONS=(
  "人口学 + 关键 semantic qualifiers（急慢/单双侧/进行性等）+ 综合征 → one-liner。"
  "按 schema/解剖定位/VINDICATE 生成，按常见 × 致命不能漏（can't-miss/Big Three）双轴排。"
  "验前概率、各检查的似然比、test/treatment 阈值；低概率先用规则排除。"
  "red flag、test of time / test of treatment、follow-up 安排。"
  "是否过早闭合、锚定、可得性偏倚；做一次 diagnostic timeout\"还能是什么\"。"
  "每个数字/结论的来源与口径、是否 contested estimate、AI 结论的 decay。"
)
declare -a DIM_SOURCES=(
  "病史（为王）+ 针对性体检；Track 04 problem representation 方法。"
  "Track 02 schema/DDx 工具 + Track 04 鉴别方法；必要时 LLM 扩列（不拍板）。"
  "JAMA RCE / McGee 的 LR 数据、MDCalc 决策规则、Fagan nomogram。"
  "Track 03 安全网工作流。"
  "Track 04 偏倚分类 + 去偏策略（标注：干预证据弱，当低成本兜底）。"
  "Track 04/05 一手来源；区分 verified vs 估计。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话 one-liner + 已识别的语义限定词。"
  "排序后的 DDx + 明确标出 can't-miss 项。"
  "选定检查 + 理由（LR/阈值逻辑），而非\"全查一遍\"。"
  "working diagnosis + 明确安全网（\"出现 X 立刻就医\"）+ 不确定性说明。"
  "timeout 结论 + 主力仍是补知识/脚本的提示。"
  "结论 + 证据强度标注（估计/争议/高 decay）+ \"非医疗建议、需执业医师核实\"。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
