#!/usr/bin/env bash
# dtco-pathfinding-pdk.sh — DTCO 设计-工艺协同优化（pathfinding → 协同迭代 → 设计规则/标准单元 → PDK） SOP walkthrough for 半导体芯片制造工艺.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="半导体芯片制造工艺"
WORKFLOW="DTCO 设计-工艺协同优化（pathfinding → 协同迭代 → 设计规则/标准单元 → PDK）"

usage() {
  cat <<EOF
dtco-pathfinding-pdk.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./dtco-pathfinding-pdk.sh             # interactive
  ./dtco-pathfinding-pdk.sh --dry-run
  ./dtco-pathfinding-pdk.sh --json
  ./dtco-pathfinding-pdk.sh --explain
  ./dtco-pathfinding-pdk.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "DTCO 设计-工艺协同优化（pathfinding → 协同迭代 → 设计规则/标准单元 → PDK）" 工作流。

一句话: 从「单纯 dimensional scaling（缩尺寸）收益不足、PPAC 提升乏力」到「通过设计与工艺反复协同迭代，挤出额外 PPAC 的设计规则 + 标准单元 + PDK」。等效微缩时代的核心方法学。 (evidence: [T03-S004, T04-S018])

入门 SOP 共 4 步, 失败模式自检 3 项。

相关心智模型:
  • 物理硬约束 ⇄ 良率/成本经济约束（第一性双重张力）: 半导体工艺的每个决策都同时受两类硬约束——物理/化学/材料（量子隧穿、短沟道效应、RC 延迟、热预算、缺陷物理）与良率/成本经济（D0 缺陷密度、每片晶圆成本、wph、折旧）；摩尔定律首先是**经济命
  • 设备/工艺是必要非充分，良率 know-how 才是真壁垒: 能不能做先进制程，从来不是「有没有 EUV/光刻机」单一决定的——设备 + 材料 + 刻蚀/沉积 + 工艺整合 + 良率爬坡**五要素缺一不可**，而良率 ramp 的 know-how 是 silo

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Technology 阶段 pathfinding**：探索器件架构/工艺选项与对应 PPAC，用 TCAD/SEMulator3D 评估候选。 (evidence: [T03-S004])"
  "**设计-工艺协同迭代**：把工艺能力（可做的最小 pitch、overlay 预算）与设计需求（标准单元高度、布线资源）反复对撞，找联合最优。 (evidence: [T03-S004])"
  "**Design Enablement（产出 PDK）**：生成器件模型、标准单元库、布线 tech file、RC 寄生模型。 (evidence: [T03-S004])"
  "**Design 阶段验证**：用 PDK 做逻辑综合 + place&route，回测真实设计的 PPAC 是否达标，不达标回到 step2。 (evidence: [T03-S004])"
)
declare -a FAILURE_MODES=(
  "**死磕 dimensional scaling**：在已到光刻/物理极限的 pitch 上硬缩，良率/成本崩 —— 改用 DTCO 设计手段提密度。"
  "**工艺设计不协同**：规则工艺做不出或设计用不上 —— step2 反复对撞迭代。"
  "**只做 cell 级 DTCO 忽略系统**：错失 STCO/3D 封装的等效微缩红利 —— 把系统级纳入协同。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "dtco-pathfinding-pdk-walkthrough"
fi
