#!/usr/bin/env bash
# patterning-opc-overlay.sh — 光刻层 patterning 方案开发（曝光条件 → OPC/计算光刻 → overlay 预算 → 多重曝光分解） SOP walkthrough for 半导体芯片制造工艺.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="半导体芯片制造工艺"
WORKFLOW="光刻层 patterning 方案开发（曝光条件 → OPC/计算光刻 → overlay 预算 → 多重曝光分解）"

usage() {
  cat <<EOF
patterning-opc-overlay.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./patterning-opc-overlay.sh             # interactive
  ./patterning-opc-overlay.sh --dry-run
  ./patterning-opc-overlay.sh --json
  ./patterning-opc-overlay.sh --explain
  ./patterning-opc-overlay.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "光刻层 patterning 方案开发（曝光条件 → OPC/计算光刻 → overlay 预算 → 多重曝光分解）" 工作流。

一句话: 从「一个关键层在给定光刻能力（DUV 193i / EUV 0.33NA / high-NA 0.55NA）下需要成像合格」到「一套 patterning 方案：mask + OPC + 必要的多重曝光分解 + overlay 预算」。光刻是 fab 的中枢节奏。 (evidence: [T03-S011, T02-S010])

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 物理硬约束 ⇄ 良率/成本经济约束（第一性双重张力）: 半导体工艺的每个决策都同时受两类硬约束——物理/化学/材料（量子隧穿、短沟道效应、RC 延迟、热预算、缺陷物理）与良率/成本经济（D0 缺陷密度、每片晶圆成本、wph、折旧）；摩尔定律首先是**经济命
  • 设备/工艺是必要非充分，良率 know-how 才是真壁垒: 能不能做先进制程，从来不是「有没有 EUV/光刻机」单一决定的——设备 + 材料 + 刻蚀/沉积 + 工艺整合 + 良率爬坡**五要素缺一不可**，而良率 ramp 的 know-how 是 silo

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定曝光平台与 k1**：根据层 pitch 与可用光源（193i/EUV/high-NA）判断单次曝光能否成像（k1 因子），决定是否需要多重曝光。 (evidence: [T03-S011])"
  "**若需则做多重曝光分解**：把单层图案分解成多次曝光（LELE 或自对准 SADP/SAQP），分解算法保证可制造且 overlay 可控。 (evidence: [T03-S011])"
  "**OPC / 计算光刻**：用 OPC/ILT（Calibre/Proteus）对 mask 做光学邻近校正/逆光刻，补偿衍射与邻近效应。 (evidence: [T02-S010, T02-S011])"
  "**overlay 预算与量测反馈**：定 overlay 误差预算（先进节点 <2nm），用量测（KLA overlay）反馈到曝光机做高阶校正。 (evidence: [T03-S011])"
  "**随机缺陷 / 工艺窗口验证**：EUV 层验证 stochastic 缺陷（line-edge roughness/bridging）预算与曝光-焦深工艺窗口。 (evidence: [T03-S011])"
)
declare -a FAILURE_MODES=(
  "**不做 OPC 直接上 mask**：硅上图案严重失真（线端缩短/桥接），整层报废 —— OPC/ILT 是关键层强制步骤。"
  "**多重曝光 overlay 失控**：各次曝光对不齐，先进节点 <2nm overlay 超标短路 —— 严格 overlay 预算 + 高阶量测反馈。"
  "**EUV 层忽略 stochastic 缺陷**：只调平均成像、不做随机缺陷预算，random bridging/断线良率塌 —— EUV 层必做 stochastic 预算 + SMO。"
  "**盲目追 high-NA**：经济性未证明就引入 high-NA（>3.5 亿美元/台），成本墙 —— 评估单曝收益 vs 多重曝光成本再决定（TSMC 即因此推迟）。 (evidence: [T02-S005])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "patterning-opc-overlay-walkthrough"
fi
