#!/usr/bin/env bash
# yield-ramp-commonality-spc.sh — 良率爬坡 Yield Ramp（缺陷采集→分类→commonality→根因→改善→SPC固化） SOP walkthrough for 半导体芯片制造工艺.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="半导体芯片制造工艺"
WORKFLOW="良率爬坡 Yield Ramp（缺陷采集→分类→commonality→根因→改善→SPC固化）"

usage() {
  cat <<EOF
yield-ramp-commonality-spc.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./yield-ramp-commonality-spc.sh             # interactive
  ./yield-ramp-commonality-spc.sh --dry-run
  ./yield-ramp-commonality-spc.sh --json
  ./yield-ramp-commonality-spc.sh --explain
  ./yield-ramp-commonality-spc.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "良率爬坡 Yield Ramp（缺陷采集→分类→commonality→根因→改善→SPC固化）" 工作流。

一句话: 从「新节点/新产品良率远低于量产目标」到「良率爬到量产目标、缺陷 Pareto 主项关闭、SPC 固化」。这是 fab 最核心也最 know-how 密集的 workflow，决定一个节点能否赚钱。 (evidence: [T03-S001, T04-S034])

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 物理硬约束 ⇄ 良率/成本经济约束（第一性双重张力）: 半导体工艺的每个决策都同时受两类硬约束——物理/化学/材料（量子隧穿、短沟道效应、RC 延迟、热预算、缺陷物理）与良率/成本经济（D0 缺陷密度、每片晶圆成本、wph、折旧）；摩尔定律首先是**经济命
  • 设备/工艺是必要非充分，良率 know-how 才是真壁垒: 能不能做先进制程，从来不是「有没有 EUV/光刻机」单一决定的——设备 + 材料 + 刻蚀/沉积 + 工艺整合 + 良率爬坡**五要素缺一不可**，而良率 ramp 的 know-how 是 silo

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**缺陷与良率数据采集**：inline defect inspection（KLA 光学/e-beam）逐层扫 + 终测 bin map + WAT/PCM 电性参数，建立良率与缺陷数据库。 (evidence: [T02-S019, T03-S003])"
  "**缺陷分类与 Pareto**：把 fail 按 bin / 缺陷类型排 Pareto（通常前三 bin 占 >70% 良率损失），先打最大的。 (evidence: [T03-S001])"
  "**Commonality / 逐层定位**：用 commonality analysis（哪台设备/哪一层/哪个时间段的 lot 共性 fail）+ 逐层 inline 数据，把良率损失定位到具体工艺步骤/设备。 (evidence: [T03-S001, T03-S002])"
  "**根因分析（FA）**：对定位到的缺陷做物理 FA（SEM/TEM/FIB）或 volume scan diagnosis 找系统性 vs 随机根因。 (evidence: [T03-S002])"
  "**工艺改善验证**：针对根因改配方/设备/设计，用 split lot 验证良率提升与无副作用。"
  "**SPC 固化 + BKM**：把改善固化进 SPC 限/APC 规则，写成 BKM 防复发并复制到同类产线。 (evidence: [T03-S007, T04-S034])"
)
declare -a FAILURE_MODES=(
  "**只看物理缺陷、不看电性 WAT/PCM**：漏掉无可见缺陷的参数型良率损失（阈值漂移/漏电），根因找错，浪费数周追错缺陷 —— 电性 + 物理双轨 commonality。"
  "**不排 Pareto 就逐片救火**：精力分散在小 bin，良率爬坡拖几个月 —— 先 Pareto，前三 bin 占 >70% 损失，集中打最大的。"
  "**改善不做 split 验证就上线**：以为改对了，结果引入新副作用或根因没关闭，良率再次跌 —— 必须 split lot 验证提升且无副作用再固化。"
  "**改善不固化进 SPC/BKM**：同一 excursion 在不同 lot/不同 fab 反复发生 —— 固化进 SPC 限 + APC + BKM 复制。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "yield-ramp-commonality-spc-walkthrough"
fi
