#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 青少年心理健康教育.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="青少年心理健康教育"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 年龄与发展阶段
  9.2 循证干预匹配
  9.3 筛查与评估工具选择
  9.4 政策与法规合规
  9.5 文化语境适配
  9.6 实施资源评估
  9.7 最新研究动态

背后的心智模型:
  • 发展适配优先 — 青春期不是成人的缩小版: 青少年的大脑、认知和情绪发展处于独特阶段——前额叶皮层 25 岁前未完全成熟、杏仁核反应性高、同伴影响权重超越成人直觉——任何干预方案必须以发展阶段为锚点设计,而非照搬成人模型。
  • 预防优于治疗 — MTSS 三级金字塔: 心理健康教育的核心逻辑是三级预防——Tier 1 全员预防(SEL/心理课)覆盖约 80% 的学生、Tier 2 小组干预(针对筛查出的 at-risk 群体)覆盖约 15%、Tier 3 个别临床干
  • 循证实践不可妥协 — 干预必须有证据: 青少年心理干预必须基于 RCT 或高质量 meta-analysis 支持的循证方案(CBT-A、DBT-A、MI 等),非循证方法(如纯"正能量"讲座、心灵鸡汤课、伪心理学疗法)不仅无效,还可能有害

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "年龄与发展阶段"
  "循证干预匹配"
  "筛查与评估工具选择"
  "政策与法规合规"
  "文化语境适配"
  "实施资源评估"
  "最新研究动态"
)
declare -a DIM_QUESTIONS=(
  "目标学生的年龄段(小学/初中/高中)及对应的认知发展水平和常见心理挑战"
  "对应问题(焦虑/抑郁/行为/社交/创伤)有哪些循证干预方案,效果量多大"
  "可用的标准化量表、该量表的年龄适配范围、常模、信效度"
  "当地学校心理健康的法律要求(FERPA/HIPAA/未成年人保护法/教育部纲要)、强制报告义务、数据隐私"
  "目标学校/社区的文化背景对心理健康的认知、求助行为模式、污名化程度"
  "学校/机构现有的人力(持证心理教师数量)、经费、课时、数据基础设施"
  "近 6 个月内相关领域的新研究/政策变化/工具更新(特别是社交媒体争论的最新数据)"
)
declare -a DIM_SOURCES=(
  "Steinberg \"Adolescence\" 对应章节 / APA developmental milestones / 林崇德《发展心理学》"
  "effectivechildtherapy.org (APA Div 53) / CASEL Program Guide / Cochrane Reviews / NICE Guidelines"
  "APA PsycTests / SAMHSA NREPP / 量表原始论文 / 出版商官网"
  "ed.gov / moe.gov.cn / NASP position statements / 当地教育局文件"
  "相关人群的心理健康素养研究 / 社区需求评估报告 / 当地心理健康服务利用数据"
  "学校人事编制 / 预算文件 / MTSS 实施指南中的资源需求表"
  "PubMed 近期文献 / CASEL newsletter / NASP Communiqué / After Babel (Haidt) / NSDUH 最新数据"
)
declare -a DIM_OUTPUT_FORMATS=(
  "该年龄段的典型发展任务和适配干预策略"
  "推荐方案 + 证据等级 + 适用条件"
  "推荐量表 + 施测说明 + 解释注意事项"
  "合规要点清单 + 需要注意的法律红线"
  "需要适配的文化因素 + 沟通策略建议"
  "可行方案(在现有资源约束下能做什么)vs 理想方案(需要争取什么额外资源)"
  "是否有新证据改变了现有建议"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
