#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for AI自适应学习.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AI自适应学习"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 学生建模与追踪策略
  9.2 内容粒度与 KC 结构评估
  9.3 效果证据审计
  9.4 合规地图绘制
  9.5 工具生态匹配
  9.6 学派语境定位
  9.7 LLM 冲击评估

背后的心智模型:
  • 追踪-适应闭环 (Trace-then-Adapt Loop): 自适应学习的核心运作模式是「持续估计学生的潜在知识状态 → 基于估计选择最优下一步教学动作」的概率闭环, 而非简单的分数累加-推荐
  • 粒度决定效果 (Granularity Determines Effectiveness): 自适应的粒度越细 (从课程级→单元级→步骤级→子步骤级), 效果越接近人类一对一辅导 — VanLehn (2011) meta-review 证实步骤级 ITS 效果量约 d=0.76 (业内估),
  • 遗忘可预测且可利用 (Forgetting Is Predictable and Exploitable): 记忆衰减遵循可建模的数学规律 (Ebbinghaus 1885), 间隔重复算法 (SM-2/HLR/FSRS) 是实证验证最充分的教学干预手段 — 不建模遗忘的自适应系统隐含「掌握永久」的假设, 在

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "学生建模与追踪策略"
  "内容粒度与 KC 结构评估"
  "效果证据审计"
  "合规地图绘制"
  "工具生态匹配"
  "学派语境定位"
  "LLM 冲击评估"
)
declare -a DIM_QUESTIONS=(
  "目标场景的数据量级 (交互记录数) + 可解释性需求 (高利害 vs formative) + 是否需要建模遗忘"
  "现有课程的 KC 分解粒度 + 前置关系图完整度 + 学习曲线是否下降"
  "产品效果宣称的独立 RCT + 效果量 (d) + 对照条件 + 样本量"
  "目标市场 × 用户年龄 × 数据类型 → 适用法规组合"
  "机构现有 LMS + 数据标准 + 预算 + 技术能力 → 匹配工具栈"
  "用户/团队的方法论偏好 (心理测量 vs ML vs 学习科学 vs 产品化) + 应用场景"
  "目标应用中 LLM 可替代环节 (内容生成/对话辅导/批改) vs 不可替代环节 (IRT 校准/RCT/合规)"
)
declare -a DIM_SOURCES=(
  "pyBKT/DKT/AKT 的 benchmark 对比 (GitHub repos + EDM proceedings) + DataShop 领域特定学习曲线 + FSRS/HLR 记忆衰减参数"
  "DataShop 学习曲线工具 + 课程标准文件 + 领域专家访谈"
  "IES What Works Clearinghouse + ERIC + PubMed + 产品白皮书 (注意利益冲突)"
  "studentprivacy.ed.gov + SDPC (州级) + cac.gov.cn + ICO.org.uk + 产品法务"
  "1EdTech TrustEd Apps 目录 + LMS 厂商文档 + GitHub 开源活跃度"
  "团队论文/工具使用 (R IRT → 心理测量; PyTorch DKT → ML; DataShop → 学习科学)"
  "Khanmigo responsible AI framework + AIED 2025/2026 论文 + Thinking-KT/Dialogue-KT"
)
declare -a DIM_OUTPUT_FORMATS=(
  "「推荐 {算法}, 理由: 数据量 {N} + 可解释性 {高/低} + 遗忘建模 {需要/不需要}; 备选 {算法B} 当 {条件}」"
  "「KC 粒度 {当前/建议级别}; 前置关系完整度 {%}; 学习曲线异常 {N 个 KC 不下降}」"
  "「证据等级 {ESSA Tier I/II/III/IV 或无}; 效果量 d={值} (来源: {论文}); 利益冲突 {有/无}」"
  "「适用法规 {列表}; 关键要求 {3-5 条}; 最高风险环节 {数据流节点}」"
  "「推荐: {LMS} + {自适应引擎} + {评估} + {分析}; 集成: {LTI 1.3/xAPI/QTI}; 工作量: {人月估}」"
  "「主要倾向: {学派}; 盲区: {该学派忽略的维度}; 补充: {互补学派 1-2 个关键洞见}」"
  "「LLM 适用: {列表}; 不可替代: {列表}; 新增风险: {列表}; human-in-the-loop 设计: {机制}」"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
