#!/usr/bin/env bash
# evidence.sh — Evidence 决策助手 for GitHub 解封 — 账号封禁/限制/恢复的领域操作系统。覆盖：(a) GitHub 官方政策体系 (TOS / 可接受使用政策 / Trust & Safety 执行模式 / 公开申诉路径 / 受制裁地区解读)；(b) 封号原因诊断学 (spam / abuse / 制裁误标 / 2FA 丢失 / ToS 违规 / 账号劫持误判 / ban evasion 等子类型 + 症状→原因映射 + 自我分诊压测)；(c) 申诉实操 craft (写一封能让 T&S 快速判误伤的英文申诉信 + 升级阶梯 + 法务介入边界 + Don'ts)；(d) 制裁与合规硬边界 (OFAC SDN 名单 / 哪些国家或地区真不可达 / VPN 误判路径 / 中国大陆不是美国制裁地区的反复重申)；(e) 中国大陆开发者特别处境 (sanctioned region 误标 + SMS 验证不支持 +86/+852 + Gitee/GitLab/Codeberg/JihuLab 备用迁移 + 私有自托管 Gitea/Forgejo)；(f) 真实案例库 (~30+ 公开案例分类拆解：误伤 / 真违规 / 制裁误标三类各自赔率与申诉成功路径)。伦理锚绝不软化：不教 ban evasion / 不教撒谎式申诉 / 真违规承认改进 / 丢 2FA 无恢复因子则诚实告知 / 中国制裁误标靠申诉不靠换 VPN / 申诉 6 个月窗口必算清 / ~3% 真违规恢复 vs ~79% 误伤申诉成功率分层标。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="GitHub 解封 — 账号封禁/限制/恢复的领域操作系统。覆盖：(a) GitHub 官方政策体系 (TOS / 可接受使用政策 / Trust & Safety 执行模式 / 公开申诉路径 / 受制裁地区解读)；(b) 封号原因诊断学 (spam / abuse / 制裁误标 / 2FA 丢失 / ToS 违规 / 账号劫持误判 / ban evasion 等子类型 + 症状→原因映射 + 自我分诊压测)；(c) 申诉实操 craft (写一封能让 T&S 快速判误伤的英文申诉信 + 升级阶梯 + 法务介入边界 + Don'ts)；(d) 制裁与合规硬边界 (OFAC SDN 名单 / 哪些国家或地区真不可达 / VPN 误判路径 / 中国大陆不是美国制裁地区的反复重申)；(e) 中国大陆开发者特别处境 (sanctioned region 误标 + SMS 验证不支持 +86/+852 + Gitee/GitLab/Codeberg/JihuLab 备用迁移 + 私有自托管 Gitea/Forgejo)；(f) 真实案例库 (~30+ 公开案例分类拆解：误伤 / 真违规 / 制裁误标三类各自赔率与申诉成功路径)。伦理锚绝不软化：不教 ban evasion / 不教撒谎式申诉 / 真违规承认改进 / 丢 2FA 无恢复因子则诚实告知 / 中国制裁误标靠申诉不靠换 VPN / 申诉 6 个月窗口必算清 / ~3% 真违规恢复 vs ~79% 误伤申诉成功率分层标。"
TOPIC="Evidence"

usage() {
  cat <<EOF
evidence.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 6 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./evidence.sh             # interactive
  ./evidence.sh --dry-run   # walk through but no file
  ./evidence.sh --json      # JSON to stdout
  ./evidence.sh --explain   # show backing playbook rules + mental models
  ./evidence.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Evidence 主题下的 playbook 规则组合成交互树。

基于 6 条规则:
  • 如果 收到封号通知 (或发现 profile 404) → 则 : 立即停下所有操作, 不要开新号, 不要在社交媒体发泄, 先启动分诊 SOP (WF1)。案例: pilot2254 
  • 如果 判定是制裁误标 (中国开发者 VPN 导致) → 则 : 准备位置证明三件套 (身份证 + 地址证明 + 自拍), 在申诉信中明确声明 "China (PRC) is not
  • 如果 判定是 spam/abuse 误判 → 则 : 在申诉信中提供账号历史 (注册时间 + 贡献数) + 解释被误判的行为 (如自动化脚本超过 rate limit),
  • 如果 判定是真违规 (确实做了 spam/abuse 行为) → 则 : 承认违规 + 说明已采取的改正措施 + 承诺不再违反, 走 reinstatement 而非 appeal 路径。不
  • 如果 尚未被封 (预防模式) → 则 : 立即执行安全加固 — 硬件安全钥匙 + recovery codes 离线存储 + 定期 git clone --m
  • 如果 是组织 (org) 而非个人被封 → 则 : 立即让其他 org admin 备份 (如果仍有访问权); 申诉时提供组织注册信息; 注意: 因单个成员违规导致全组

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "收到封号通知 (或发现 profile 404)"
  "判定是制裁误标 (中国开发者 VPN 导致)"
  "判定是 spam/abuse 误判"
  "判定是真违规 (确实做了 spam/abuse 行为)"
  "尚未被封 (预防模式)"
  "是组织 (org) 而非个人被封"
)
declare -a RULE_ACTIONS=(
  ": 立即停下所有操作, 不要开新号, 不要在社交媒体发泄, 先启动分诊 SOP (WF1)。案例: pilot2254 (2024) 在发现 profile 404 后冷静记录症状, 最终 40 天后成功恢复 (evidence: [T03-S009, T03-S001])"
  ": 准备位置证明三件套 (身份证 + 地址证明 + 自拍), 在申诉信中明确声明 \"China (PRC) is not a US-sanctioned country\", 解释 VPN 使用原因, 承诺改用非制裁区 IP。案例: lyc8503 (2024) 中国开发者因 VPN 被标, 提供位置证明后约 2 周解封 (evidence: [T03-S010, T03-S002, T03-S024])"
  ": 在申诉信中提供账号历史 (注册时间 + 贡献数) + 解释被误判的行为 (如自动化脚本超过 rate limit), 承诺调整行为。案例: student reinstatement (2024) 学生用户因大量 fork 课程仓库被标 spam, 提供学校证明后约 2 个月恢复 (evidence: [T03-S011, T03-S022])"
  ": 承认违规 + 说明已采取的改正措施 + 承诺不再违反, 走 reinstatement 而非 appeal 路径。不要否认, 不要撒谎 — GitHub T&S 能看到你的操作日志。案例: 约 3% 的真违规恢复率 (业内估, 基于社区汇报) 主要来自真诚悔改 + 具体改正措施, 而非巧辩 (evidence: [T03-S001, T06-S001])"
  ": 立即执行安全加固 — 硬件安全钥匙 + recovery codes 离线存储 + 定期 git clone --mirror 自动备份 + 至少一个平台做 mirror。一次约 2 小时的投入, 可以在封号事件中节约数周的恢复时间。案例: \"GitHub is not your backup\" (2024-2025 社区共识) (evidence: [T03-S013, T03-S034, T03-S016])"
  ": 立即让其他 org admin 备份 (如果仍有访问权); 申诉时提供组织注册信息; 注意: 因单个成员违规导致全组织封禁的情况需要说明其他成员无关。案例: 开源团队因公开 issue 区人身攻击导致全组织封禁 (匿名 aggregate) (evidence: [T03-S022, T03-S035])"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "evidence-decision"
fi
