#!/usr/bin/env bash
# topic-3.sh — 经方 决策助手 for 中医诊疗 — 中医临床医师的认知操作系统 (经典理论 阴阳五行脏腑气血经络六经卫气营血三焦 + 四诊八纲 + 治法 + 方剂学 经方时方 + 中药学 四气五味归经炮制 + 针灸学 经络穴位手法灸法 + 推拿按摩 + 中医各科 内外妇儿骨伤皮肤眼耳鼻喉肛肠老年急症 + 中西医结合 + 循证中医 + NATCM 监管 + 中医诊所备案 + 国家级名老中医 学术继承人 — 不含 道家修炼 / 风水算命 / 中医养生科普 / 中医美容 / 民族医学藏蒙维傣).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中医诊疗 — 中医临床医师的认知操作系统 (经典理论 阴阳五行脏腑气血经络六经卫气营血三焦 + 四诊八纲 + 治法 + 方剂学 经方时方 + 中药学 四气五味归经炮制 + 针灸学 经络穴位手法灸法 + 推拿按摩 + 中医各科 内外妇儿骨伤皮肤眼耳鼻喉肛肠老年急症 + 中西医结合 + 循证中医 + NATCM 监管 + 中医诊所备案 + 国家级名老中医 学术继承人 — 不含 道家修炼 / 风水算命 / 中医养生科普 / 中医美容 / 民族医学藏蒙维傣)"
TOPIC="经方"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 经方 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 处方 含 经方 (仲景方 + 千金方) 适应证 → 则 : 则 优先 经方 + 严守 君臣佐使 + 不轻易加减 — 经方 1800 年验证 + 病机精准 + 配伍紧密 (桂枝汤

相关心智模型:
  • 整体观念 + 辨证论治 (中医方法论灵魂): 中医不是 "症-药" 一对一查表, 是 把人放在 "天人合一 + 形神合一 + 五脏相关 + 经络贯通 + 气血循环" 整体框架里 看症状 → 辨证 (脏腑/六经/卫气营血/三焦/八纲/气血津液) →
  • 三因制宜 — 因人 + 因时 + 因地 (个体化精髓): 同一证 同一方 在 不同 患者 (老人/儿童/孕妇/体质差异 平和/气虚/阳虚/阴虚/痰湿/湿热/瘀血/气郁/特禀) + 不同 季节 (春升/夏长/秋收/冬藏) + 不同 地域 (南湿北燥 / 沿海岛

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "处方 含 经方 (仲景方 + 千金方) 适应证"
)
declare -a RULE_ACTIONS=(
  ": 则 优先 经方 + 严守 君臣佐使 + 不轻易加减 — 经方 1800 年验证 + 病机精准 + 配伍紧密 (桂枝汤 桂枝 君 + 芍药 臣 + 生姜 大枣 佐使 + 甘草 调和); 现代加减 需 充分病机依据 (黄煌 NJUCM 经方派 现代加减体系 可参考)。案例: 黄煌 现代经方派 推 \"方证相应\" + 体质方证 (经方 100 首 中 60% (业内估) 直接对应 现代常见病证), 临床 应用 率 30-40% (业内估)"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
