#!/usr/bin/env bash
# sop.sh — 师资培养 SOP（招聘 → 教练认证/带教 → 课程标准化复制） SOP walkthrough for K12 体育培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="K12 体育培训"
WORKFLOW="师资培养 SOP（招聘 → 教练认证/带教 → 课程标准化复制）"

usage() {
  cat <<EOF
sop.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./sop.sh             # interactive
  ./sop.sh --dry-run
  ./sop.sh --json
  ./sop.sh --explain
  ./sop.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "师资培养 SOP（招聘 → 教练认证/带教 → 课程标准化复制）" 工作流。

一句话: 解决这一行最深的断层「能打≠能教」——把退役运动员/体育生变成「能标准化交付的认证教练」，从招聘到标准化复制的师资闭环。

入门 SOP 共 4 步, 失败模式自检 0 项。

相关心智模型:
  • 能打 ≠ 能教 ≠ 能运营（师资三层断层）: 会打球、会教学、会运营是**三套互不蕴含的能力**——招到退役运动员只解决了第一层，教学法+持证是第二层，单店模型/续费/合规是第三层；这一行最深的坑是用第一层冒充后两层。
  • 续费率才是命门（不是满班，不是获客）: 单店生死线是**续费率 + 转介绍**，不是满班率或获客量——满班且高获客的店也会因续费塌方而死；「收钱 ≠ 课消 ≠ 确认收入」，预收费是受监管负债不是利润。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**招聘**：招体育专业毕业生/退役运动员/专项教练/幼师（JD 普遍要求大专以上+热爱体育教育+能接受销售性质，因教练也背续费/转介绍指标；体育院校就业平台是主要师资来源池）。**跳过会怎样**：招到只会练不会教/不愿沟通家长的人，交付与续费双崩 (evidence: [T03-S001, T03-S003, T03-S002, T03-S004])"
  "**合规持证**：确保执教人员持证（体育教练员职称证/社会体育指导员/单项协会技能等级证/体育教师资格证/职业技能等级证等 6 选 1），公示资质、做背景审查。**跳过会怎样**：无证执教违反《课外体育培训行为规范》，被查停+背景风险 (evidence: [T03-S005])"
  "**教练带教/认证**：补教学法——教案编写、模拟说课、辅助教学→独立授课全流程，加青少年训练指导+运动损伤防护康复，结业考核（理论+实践）。**跳过会怎样**：「能打≠能教」断层不补，课上得差、家长流失 (evidence: [T03-S006])"
  "**课程标准化复制**：把合格教练接入标准化教案库+课程体系，确保不同教练交付一致（加盟扩张尤其依赖）。**跳过会怎样**：教学质量随教练个人波动，无法规模复制 (evidence: [T03-S019])"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "sop-walkthrough"
fi
