#!/usr/bin/env bash
# engagement-case-lifecycle.sh — 项目交付全流程（engagement / case lifecycle） SOP walkthrough for 管理咨询.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="管理咨询"
WORKFLOW="项目交付全流程（engagement / case lifecycle）"

usage() {
  cat <<EOF
engagement-case-lifecycle.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./engagement-case-lifecycle.sh             # interactive
  ./engagement-case-lifecycle.sh --dry-run
  ./engagement-case-lifecycle.sh --json
  ./engagement-case-lifecycle.sh --explain
  ./engagement-case-lifecycle.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "项目交付全流程（engagement / case lifecycle）" 工作流。

一句话: 从客户问题（或 RFP）到交付建议（+ 落地）的完整闭环 —— 把一个模糊的商业难题，经「卖项目 → 定问题 → 搭假设 → 做分析 → 综合 → 讲故事 → 汇报」变成客户能据以决策/行动的产出。这是咨询「the case / study / engagement」的母流程，其它所有 workflow（2/3/5/6）都是它的子环节或并行支线。

入门 SOP 共 9 步, 失败模式自检 5 项。

相关心智模型:
  • 假设驱动是地图不是答案：先射箭再画靶 ⇄ 随时 kill 假设（第一性张力）: 面对模糊大问题，资深咨询人不从穷举数据出发，而是 Day-1 就基于经验立一个**可证伪**的初步答案（hypothesis / initial hypothesis）当地图，再只做能 kill 或 
  • 战略 = 做选择 / 做不同，不是运营效率、不是愿望清单: 这行顶级战略 figure 跨流派一致——战略的本质是**逼自己做取舍**（Martin：where-to-play × how-to-win 两个不可分割的选择；Rumelt：kernel = 诊断

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**提案 (RFP → proposal → SOW)**：响应 RFP 或主动提案，写 proposal（问题 + 范围 + 方法 + 团队 + 报价 + 时间线），赢单后落 SOW（scope of work，界定边界/交付物/排期）。proposal 本身常就是一份 deck。(evidence: [T03-S015scope:RFP→SOW 业内通识], [T06-S019])"
  "**Kickoff（启动会）**：与客户高管 + SteerCo 对齐项目目标、「什么算成功」、关键利益相关方、数据访问、节奏。(evidence: [T03-S006steerco-kickoff], 周节奏见 workflow 5)"
  "**问题定义（最关键 — 真问题 vs 表象问题）**：把模糊主诉收敛成一个**具体、有边界、可验证**的问题陈述（problem statement）；区分客户**说**的问题（表象）和**真正**该解的问题（根因）。McKinsey/Bulletproof 都把这步列为「整个项目最重要的一步，它是后续所有工作的导航」。(evidence: [T04-S035, T03-S014])"
  "**假设树 / issue tree（结构化）**：把问题 MECE 地拆成可分析的子问题（issue tree）或可证伪的子假设（hypothesis tree）—— 见 workflow 2。同时立 **Day-1 初步假设答案**。(evidence: [T03-S002, T04-S037])"
  "**Workplan（工作计划）**：给每个优先 issue/假设排「分析内容 / 终产品（end product）/ 数据源 / 时间与负责人」四列。(evidence: [T03-S014workplan-4col, T04-S035])"
  "**分析 + 建模 + 专家访谈（execute）**：跑分析验证/证伪假设 —— Excel 建模（driver tree / market sizing）、secondary research（行业数据库）、primary research（专家网络 expert call）、客户访谈。(evidence: [T02-S009expert-call, T02-S013data, 见 Track 02])"
  "**综合 (synthesis)**：把零散分析「所以呢 (so-what)」成一个统领性洞见（governing thought）—— 不是罗列发现，是提炼出对决策意味着什么。(evidence: [T04-S041synthesis, T06-S009so-what])"
  "**建议 deck + 汇报 (storyline → readout)**：用金字塔/SCQA 搭 storyline → ghost deck → 填数据 → 现场向 SteerCo readout —— 见 workflow 3 + 5。(evidence: [T04-S001, T03-S015])"
  "**落地 / 交接 (implementation / handoff)**（视项目）：战略+落地两速型项目交 implementation roadmap、建能力、交接给客户团队。(evidence: [T06-S019implementation])"
)
declare -a FAILURE_MODES=(
  "**漂亮地解决了错误的问题**：跳过/草率做 step 3，把客户的表象主诉当真问题。触发：急着进分析、不敢花时间在问题定义上。避免：kickoff 后用 1-2 天专门压问题陈述，向客户确认「我们解的是这个，对吗」。**actionable 自检**：「我能用一句话写出有边界、可验证的问题陈述吗？客户签字认可了吗？」"
  "**Boil the ocean（把海煮干）**：没立 Day-1 假设 + 没用 80/20，试图分析所有分支到 100% 精度，deadline 前崩盘。避免：先立初步假设答案，砍掉对结论无影响的长尾分析。**自检**：「这个分析如果做了，会改变我的建议吗？不会就别做。」"
  "**Confirmation bias（先射箭后画靶的暗面）**：假设驱动滥用成「只找支持自己假设的证据」。避免：每轮主动找**证伪**证据，准备好 kill 假设换靶。**自检**：「我上一个被数据推翻的假设是哪个？如果一个都没有，我可能在自我确认。」"
  "**交分析不交综合（答不出 so-what）**：step 7 缺失，交一堆 what 没有 so-what。避免：每个 exhibit/页强制写 action title（结论句）。**自检**：「把所有 action title 连起来读，是不是一个完整的『所以你该这么做』的论证？」"
  "**纯 deck 交付、不管落地**：跳过 step 9，建议无法执行。避免：建议里带 owner + timeline + 预期影响，必要时帮客户建落地能力。**自检**：「这份建议，客户明天能照着动手吗？谁负责？」"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "engagement-case-lifecycle-walkthrough"
fi
