#!/usr/bin/env bash
# steerco-stakeholder.sh — 客户 / 项目管理（SteerCo / stakeholder 对齐 / 周节奏） SOP walkthrough for 管理咨询.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="管理咨询"
WORKFLOW="客户 / 项目管理（SteerCo / stakeholder 对齐 / 周节奏）"

usage() {
  cat <<EOF
steerco-stakeholder.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./steerco-stakeholder.sh             # interactive
  ./steerco-stakeholder.sh --dry-run
  ./steerco-stakeholder.sh --json
  ./steerco-stakeholder.sh --explain
  ./steerco-stakeholder.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "客户 / 项目管理（SteerCo / stakeholder 对齐 / 周节奏）" 工作流。

一句话: 让 engagement「不翻车」的运作流 —— 经「定治理结构（SteerCo）→ 定节奏（周/双周对齐 + 阶段 readout）→ 管利益相关方与预期 → 中途纠偏」确保分析做对的同时**建议能被采纳、不踩客户政治雷**。这是 EM/partner 的核心活，区别于纯做分析。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 假设驱动是地图不是答案：先射箭再画靶 ⇄ 随时 kill 假设（第一性张力）: 面对模糊大问题，资深咨询人不从穷举数据出发，而是 Day-1 就基于经验立一个**可证伪**的初步答案（hypothesis / initial hypothesis）当地图，再只做能 kill 或 
  • 战略 = 做选择 / 做不同，不是运营效率、不是愿望清单: 这行顶级战略 figure 跨流派一致——战略的本质是**逼自己做取舍**（Martin：where-to-play × how-to-win 两个不可分割的选择；Rumelt：kernel = 诊断

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定治理结构**：明确客户侧 SteerCo（高管指导委员会）+ 关键 stakeholder（谁拍板、谁影响、谁配合数据）+ 客户项目对接人。(evidence: [T06-S019steerco, T03-S006])"
  "**定节奏（cadence）**：约定周/双周内部 + 客户对齐节奏 + 阶段性 readout 时点（项目活跃期常双周 SteerCo，团队内部更频）。(evidence: 通用项目治理实践 + [T03-S006])"
  "**每周/双周对齐 + readout**：定期向客户/SteerCo 汇报进展、初步发现、需要的决策/数据；逐步「预热」最终结论。(evidence: [T03-S006readout])"
  "**管利益相关方与预期**：识别客户内部不同声音/政治，单独对齐关键反对者，确保建议落地路径上的人都被 buy-in。(evidence: [T06-S019stakeholder])"
  "**中途纠偏**：根据 readout 反馈 + SteerCo 指示调整 scope/方向/重点。(evidence: [T03-S006])"
)
declare -a FAILURE_MODES=(
  "**最终汇报才 reveal 结论（surprise）**：高管措手不及而抵触。避免：过程中 readout 逐步预热结论。**自检**：「最终 readout 上的核心结论，关键决策者之前听过/认可过吗？」"
  "**没识别真正的拍板人/反对者**：只对接对接人。避免：早期画 stakeholder/政治地图。**自检**：「谁能一票否决这个建议？我对齐过 ta 吗？」"
  "**scope creep（范围蔓延）**：客户不断加需求无边界。避免：SOW 划界 + 变更走正式流程。**自检**：「这个新需求在 SOW 里吗？不在就要么正式扩 scope 要么礼貌拒绝。」"
  "**闷头做、不定期对齐**：方向偏了无人纠。避免：固定 cadence 的 readout。**自检**：「我上次跟客户对齐方向是几天前？超过一周就该同步了。」"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "steerco-stakeholder-walkthrough"
fi
