#!/usr/bin/env bash
# topic-1.sh — 工艺 决策助手 for 半导体芯片制造工艺.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="半导体芯片制造工艺"
TOPIC="工艺"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 工艺 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 遇到短沟道 / 漏电 / 亚阈摆幅恶化 → 则 优先换器件架构（FinFET/GAA/CFET 加强栅控）而非单纯调工艺参数，这是静电几何问题。案例：平面 CMOS 在
  • 如果 要锁定 / 评估任何工艺或设计-工艺组合 → 则 用 DOE / pathfinding 扫参数找工艺窗口中心，不 OFAT、不全因子穷举（靠经验先砍主因子）。案例：单元
  • 如果 做任何工艺改动 → 则 先 split lot 验证有提升且无副作用，再固化进 SPC/APC 并写成 BKM 复制到同类产线，否则复发或本地发

相关心智模型:
  • 物理硬约束 ⇄ 良率/成本经济约束（第一性双重张力）: 半导体工艺的每个决策都同时受两类硬约束——物理/化学/材料（量子隧穿、短沟道效应、RC 延迟、热预算、缺陷物理）与良率/成本经济（D0 缺陷密度、每片晶圆成本、wph、折旧）；摩尔定律首先是**经济命
  • 设备/工艺是必要非充分，良率 know-how 才是真壁垒: 能不能做先进制程，从来不是「有没有 EUV/光刻机」单一决定的——设备 + 材料 + 刻蚀/沉积 + 工艺整合 + 良率爬坡**五要素缺一不可**，而良率 ramp 的 know-how 是 silo

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "遇到短沟道 / 漏电 / 亚阈摆幅恶化"
  "要锁定 / 评估任何工艺或设计-工艺组合"
  "做任何工艺改动"
)
declare -a RULE_ACTIONS=(
  "优先换器件架构（FinFET/GAA/CFET 加强栅控）而非单纯调工艺参数，这是静电几何问题。案例：平面 CMOS 在约 22nm 撞短沟道墙，FinFET 三面环栅续命（T04-S009）。evidence: [T04-S009, T06-S025]"
  "用 DOE / pathfinding 扫参数找工艺窗口中心，不 OFAT、不全因子穷举（靠经验先砍主因子）。案例：单元工艺配方开发用 DOE 找 selectivity / profile 窗口（T03-S008）。evidence: [T03-S008, T03-S004]"
  "先 split lot 验证有提升且无副作用，再固化进 SPC/APC 并写成 BKM 复制到同类产线，否则复发或本地发散。案例：Intel Copy Exactly! + virtual factory + BKM 抑制跨厂漂移（T03-S007）。evidence: [T03-S007, T06-S021]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
