#!/usr/bin/env bash
# sop-lb-t-054-2025-t-cats-002.sh — 选研学基地 / 营地 SOP（对标 LB/T 054-2025 + T/CATS 002） SOP walkthrough for 研学营地教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="研学营地教育"
WORKFLOW="选研学基地 / 营地 SOP（对标 LB/T 054-2025 + T/CATS 002）"

usage() {
  cat <<EOF
sop-lb-t-054-2025-t-cats-002.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./sop-lb-t-054-2025-t-cats-002.sh             # interactive
  ./sop-lb-t-054-2025-t-cats-002.sh --dry-run
  ./sop-lb-t-054-2025-t-cats-002.sh --json
  ./sop-lb-t-054-2025-t-cats-002.sh --explain
  ./sop-lb-t-054-2025-t-cats-002.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "选研学基地 / 营地 SOP（对标 LB/T 054-2025 + T/CATS 002）" 工作流。

一句话: 从「立项后需要为主题找落脚的基地/营地」走到「资源匹配主题、通过安全与容量验收、签约可用」的状态——研学/营地体验质量与安全的物理基础。

入门 SOP 共 6 步, 失败模式自检 3 项。

相关心智模型:
  • 「研学是课程不是行程」——教育属性优先: 研学/营地的本体是**课程**（有学习目标—实施—评价闭环），不是**行程**（景点+讲解词）；从业者用「教育本质」作为对抗旅游化、获客化、速成化的立场锚与对客叙事。
  • 体验—反思闭环（Kolb 圈）——「经验无反思即旅游」: 学习不是「去过/动手过」就发生，而要走完「具体经验→反思观察→抽象概念化→主动实践」的圈；**「反思/复盘」环节的有无，是研学区别于旅游的命门工序**。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**对标标准筛选**：按 LB/T 054-2025（服务）+ T/CATS 002（基地营地设施与服务、合格认定）建候选清单，优先有等级认定的。跳过后果：选到「自封研学基地」，设施/安全/容量名不副实。 evidence: [W-S008, W-S009]"
  "**资源匹配主题**：核基地资源能否支撑课程学习目标（自然/红色/科技/人文对口）。跳过后果：主题与资源错配，课程在现场落不了地。 evidence: [W-S002]"
  "**安全设施核查**：流量监控、应急照明/工具/设备、疏散通道与标识、出入口及主要通道全天候 CCTV 监控、周边 200m 内无重大安全隐患建筑。跳过后果：现场安全设施缺失，突发无兜底。 evidence: [W-S008]"
  "**容量+食宿核查**：独立经营场所、宜围闭式管理；餐厅选址合理宜营养配餐；住宿便于集中管理、男女分室、有沐浴/床品/储物。跳过后果：超容量挤兑、食宿不达标，行中崩盘。 evidence: [W-S008]"
  "**实地踩点**：按真实行程动线走一遍，核对图册与现场差异、应急通道、就近医疗。跳过后果：凭图册/招商话术选基地，现场货不对板。 evidence: [W-S006]"
  "**签约**：与基地/地接签服务+安全责任协议。跳过后果：责任不清，出事互相推诿。 evidence: [W-S006]"
)
declare -a FAILURE_MODES=(
  "**图册选基地、现场货不对板**：凭招商图册/话术签约，现场食宿/安全/容量缩水。→ 新基地必实地踩点+标准核查清单逐项核。 evidence: [W-S006, W-S008]"
  "**超容量挤兑**：旺季为冲量塞满，食宿/集合/如厕动线崩，安全与体验双输。→ 按 T/CATS 002 容量与满员峰值核算上限，宁可控流。 evidence: [W-S008]"
  "**自封「研学基地」当国家级**：把机构自封或低级别基地当国家级宣传，被核查打脸。→ 核验命名层级（国家级仅 2017/2018 两批），不轻信牌子。 evidence: [W-S008]（Track 06）"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "sop-lb-t-054-2025-t-cats-002-walkthrough"
fi
