#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 个人投资理财.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="个人投资理财"
DIM_COUNT=6

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (6 个):
  9.1 目标 / 风险承受度 / 时间轴定位（脊椎）
  9.2 账户结构 / 税优容器（先于选产品）
  9.3 资产配置（股 / 债 / 现金 / 国际比）
  9.4 选品取向判定（被动默认 vs 主动 edge 检验 → 四派分叉）
  9.5 成本与税效率审计
  9.6 行为 / 纪律预案

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "目标 / 风险承受度 / 时间轴定位（脊椎）"
  "账户结构 / 税优容器（先于选产品）"
  "资产配置（股 / 债 / 现金 / 国际比）"
  "选品取向判定（被动默认 vs 主动 edge 检验 → 四派分叉）"
  "成本与税效率审计"
  "行为 / 纪律预案"
)
declare -a DIM_QUESTIONS=(
  "钱什么时候要用（时间轴）、跌 30% 会不会半夜割肉（意愿）、收入稳定性与现有缓冲（能力）、目标缺口（需求）；应急金 3-6 月、高息债是否已清。"
  "地域（US/CN）决定税优顺序；雇主匹配有没有拿满、Roth vs Traditional 选对没、个人养老金 Y 账户开没开。"
  "由 9.1 的风险画像翻译成大类权重（如 80/20、60/40）+ 国际比例；长期回报主要由配置而非选股/择时决定。"
  "默认低成本宽基指数；想主动选股/择时则先检验「你的 edge 是什么、为什么价格还没反映、在不在能力圈内」。"
  "跨账户加权费率、asset location（税低效资产是否藏税优账户）、TLH 机会、robo/直接指数化是否双重收费。"
  "是否有成文 IPS、熊市行动清单、自动定投与再平衡规则；最大的失败点是情绪驱动的择时/恐慌清仓。"
)
declare -a DIM_SOURCES=(
  "问用户本人；风险承受度 = 意愿×能力×需求三维交叉（investor.gov 入门 + Bogleheads asset allocation 框架）。"
  "US—Bogleheads「Prioritizing investments」+ IRS 当年限额（Notice）；CN—证监会个人养老金名录 + gov.cn 通知。"
  "Bogleheads asset allocation + lazy portfolios；用 Portfolio Visualizer 回测配置的历史回撤/波动。"
  "SPIVA（主动跑赢难度）+ 成本论；价值派看 GuruFocus/理杏仁/Damodaran data，技术/趋势派看 TradingView/PV 战术模块。"
  "Morningstar/Empower Fee Analyzer（费率穿透）；Bogleheads tax-efficient fund placement + tax loss harvesting（wash-sale 30 天）。"
  "Bogleheads 投资哲学（stay the course）+ Rational Reminder（行为教练）；把决策自动化到「设了就忘」。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话风险画像 + 时间轴 + 「跌 X% 我也不卖」的明确底线（写进 IPS）。"
  "按顺序排好的「先填哪个容器」清单 + 当年限额数字（标地域+年份）。"
  "目标配置 % + 再平衡带宽（5/25 或日历）+ 一句话风险预期（最大历史回撤量级）。"
  "选定「被动宽基 / 主动价值 / 技术 / 趋势」分支 + 若主动则写下 edge 理由（答不出=回被动）。"
  "加权 ER 数字 + 可省的成本/税清单（asset location 调整、TLH 标的、该不该上 robo）。"
  "成文 IPS 要点 + 「跌 X% 我继续投/再平衡」预案 + 已自动化的步骤清单（把意志力省给「管住手」）。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
