#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 德州扑克策略.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="德州扑克策略"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 赛制与筹码价值定位(cash vs MTT/SNG → ICM 是否适用)
  9.2 spot 求解与范围构建(solver 输入四要素 → 范围/频率/heuristic)
  9.3 对手 / 人群漏洞识别(是否有足够样本支撑剥削偏离)
  9.4 选场与 rake 经济(game/table/seat selection + rake/rakeback)
  9.5 资金与方差(bankroll buy-in 倍数 + 级别决策 + Kelly)
  9.6 心态 / tilt 状态(A-game/C-game + 止损 routine)
  9.7 牌房政策与工具合规(禁 HUD / 匿名桌 / RTA 红线)

背后的心智模型:
  • GTO 基线 ⇄ 剥削偏离(equilibrium baseline ⇄ exploitative deviation): 先建一条**不可剥削的均衡基线 (GTO)**,再针对具体对手/人群的可观察漏洞**偏离 (exploit)** 去最大化 EV;GTO 是回得去的**锚点**,不是终点。
  • Range-first(先想范围,再想这手牌): 扑克决策的**原子单位是范围(对手在某节点所有可能持牌的概率分布)**,不是单张牌;高手把对手 put on a *range* 再随每条街的行动收窄。
  • 决策与结果分离(EV > 单局结果;方差是噪音,tilt 是污染): 决策质量的**唯一标尺是 EV(长期期望)**,单局输赢是高方差噪音;tilt = 任何让情绪/结果污染 EV 决策的偏离。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "赛制与筹码价值定位(cash vs MTT/SNG → ICM 是否适用)"
  "spot 求解与范围构建(solver 输入四要素 → 范围/频率/heuristic)"
  "对手 / 人群漏洞识别(是否有足够样本支撑剥削偏离)"
  "选场与 rake 经济(game/table/seat selection + rake/rakeback)"
  "资金与方差(bankroll buy-in 倍数 + 级别决策 + Kelly)"
  "心态 / tilt 状态(A-game/C-game + 止损 routine)"
  "牌房政策与工具合规(禁 HUD / 匿名桌 / RTA 红线)"
)
declare -a DIM_QUESTIONS=(
  "这是现金局(筹码=现金,线性)还是锦标赛/SNG(ICM,筹码边际价值递减)?是否处于泡沫/名次跳?有效码量(SPR)多深?"
  "位置 / 翻前线 / 有效码量 / rake 四要素;该牌面双方 range 形态(极化 vs 浓缩)、range/nut advantage 归谁、indifference 点在哪。"
  "对手/这桌人群有无可观察的持续偏离(弃牌过多/跟注过松/诈唬不够)?样本量是否足够支撑(而非几十手噪音)?是强场(打 GTO baseline)还是弱场(打 population baseline)?"
  "这桌/这房弱玩家多不多?rake 结构(pot rake %+cap / time rake)与 rakeback 力度?能否坐在「钱的左边」?牌房是否匿名桌(削弱选桌杠杆)?"
  "当前 bankroll 够打哪个级别(cash 约 35-65 / MTT 约 75-125 buy-in)?该升/降/shot-take?winrate 置信度与是否职业(收入依赖)如何调缓冲?"
  "当前是 A-game 还是 C-game 状态?有无 tilt 触发(bad beat/连败/疲劳)?是否到了预设 stop-loss?tilt profile 属哪类(injustice/revenge/winner's/怕输)?"
  "目标牌房是否禁外置 HUD、是否匿名桌、rake/RTA 稽查政策?哪些工具在此牌房可用(数据库 HUD vs 纯 solver 学习)?"
)
declare -a DIM_SOURCES=(
  "问题描述里的赛制关键词 + 码量;MTT 后期查 ICMIZER/HRC 或 GTO Wizard ICM FT sims。"
  "GTO Wizard 预解树(秒查)或本地 Pio/GTO+ 自建 bet tree;范围直觉用 Flopzilla/Equilab。"
  "HUD 统计(HM3/PT4,注意牌房是否禁 HUD)、自动 leak 报告(GTO Reports/Leak Buster)、live 现场 sizing tells / population tendencies。"
  "牌房 lobby / table-finder、HUD 标签、各房 rake 政策页。"
  "数据库 winrate / bankroll 跟踪表;MTT 方差用 ICMIZER/HRC 估;底层 Kelly 准则(实战取 half/quarter-Kelly)。"
  "赛前状态自检 + 赛中身体/情绪信号 + 赛后情绪复盘(非牌技);心态派框架(Tendler inchworm / Angelo quitting 哲学)。"
  "各牌房规则页 / 社区共识(GGPoker 禁外置 HUD、partypoker/Ignition 匿名桌);RTA=实时辅助一律禁(作弊红线)。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "1 句定性「本问题属 {cash / MTT 泡沫 / MTT 深筹},{用 / 不用} ICM,MDF {适用 / 应主动偏低}」。"
  "1-2 句「均衡基线 = {频率/尺度},关键 heuristic = {一句可记忆规则},例外条件 = {…}」。"
  "1 句「{有 / 无}足够样本支撑偏离;若有,用 node-lock/population baseline 朝 {方向} 剥削;若无,打 GTO 基线」。"
  "1 句「换桌/选房收益 {高 / 低};建议 {坐哪 / 换房 / 拿 rakeback};rake 对本级别边际赢率影响 {大 / 小}」。"
  "1 句「当前应打 {级别};{升级线/降级 stop-loss};{是否 shot-take};缓冲按 {职业/业余 + winrate 置信度} 调」。"
  "1 句「状态 {A/C-game};{继续 / 降级减桌 / 止损离场};tilt 处置 = {在阈值前注入逻辑 / 已过阈值应离场}」。"
  "1 句「本牌房 {允许/禁} HUD、{匿名/非匿名};复盘/leak 重心放 {数据库 / 纯 solver};合规红线 = 离线 solver 学习 OK、实时 RTA 禁」。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
