#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 产品营销 (PMM, Product Marketing) — 拥有「产品如何被定位 / 表达 / 发布 / 卖进市场」的从业者认知操作系统: 是产品 / 销售 / 市场 / 客户之间的连接组织, 负责把产品能力翻译成市场价值, 并把市场声音带回产品。覆盖 (a) 定位与差异化 (April Dunford 「刻意选择语境」框架 + 竞争性替代方案 + 卖价值不卖功能 + 选择「让你优势成立的市场参照系」, 对照 Ries & Trout 经典「定位是占领心智」), (b) 信息传递与叙事 (messaging 层级 / 信息屋 + 价值主张 + 收益导向 vs 战略叙事「换框架」Andy Raskin + 表达清晰度 Emma Stratton / Punchy + 初创 homepage 定位 FletchPMM), (c) 进入市场 (GTM) 策略与产品发布 (发布分级 T1/T2/T3 + 发布流程与跨职能编排 + GTM 打法 PLG vs SLG vs 混合 + 滩头细分选择), (d) 市场与竞争情报 (竞品分析 + battlecard 战卡 + 输赢分析 win/loss + 竞争赋能 Klue/Crayon/Clozd), (e) 买家与客户研究 (ICP 理想客户画像 + 买家 / 用户 persona + Jobs-to-be-Done 任务理论 Christensen/Moesta/Ulwick ODI + 客户之声 VoC + 用真实买家测信息 Wynter/Peep Laja), (f) 销售赋能 (战卡 + pitch / 销售 deck + 一页纸 + demo 叙事 + 异议处理 + 销售培训 + 内容采用率 — 你的产出只值销售实际用到的那部分), (g) 定价与打包 (价值定价 + 打包分层 + 《Monetizing Innovation》Ramanujam/Simon-Kucher + PLG 定价 — 常与产品 / 财务共担), (h) 细分与品类 (市场细分 + TAM/SAM/SOM + 技术采用生命周期与跨越鸿沟 Geoffrey Moore + 品类设计与叙事 Play Bigger / Christopher Lochhead — 稀有且昂贵, 不是默认选项), (i) 需求生成与内容协同 (campaign 信息 + 思想领导力 + 漏斗内容 TOFU/MOFU/BOFU + ABM 基于客户营销), (j) 分析师与影响者关系 (Gartner 魔力象限 + Forrester Wave + 分析师 briefing — To B 场景, 对 pay-to-play 影响诚实标注), (k) 客户营销与倡导 (参考客户 + case study + 评测站 G2/TrustRadius/Capterra 运营 + 社区), (l) PMM 运营与度量 (影响管道 + 赢率 + 发布采用率 + 信息穿透率 + 角色汇报线「向产品还是向市场」之争 + PMM 作为战略职能 vs 接单工具人陷阱); 跨 B2B SaaS (该学科重心) / B2C 消费 / 开发者 PLG / 平台产品。不含 产品管理 (PM 造产品 / 拥有 roadmap, PMM 拥有市场 — 相邻且极易混淆) / 增长 / 效果营销 / 付费投放 (平行学科) / 品牌 / 企业传播 / 公关为终点 / 需求生成为终点 (PMM 与之协同但不等同) / 平面设计 /「做 slide 和周边的团队」(PMM 抗争的接单工具人窄化) / 泛泛「市场营销」。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="产品营销 (PMM, Product Marketing) — 拥有「产品如何被定位 / 表达 / 发布 / 卖进市场」的从业者认知操作系统: 是产品 / 销售 / 市场 / 客户之间的连接组织, 负责把产品能力翻译成市场价值, 并把市场声音带回产品。覆盖 (a) 定位与差异化 (April Dunford 「刻意选择语境」框架 + 竞争性替代方案 + 卖价值不卖功能 + 选择「让你优势成立的市场参照系」, 对照 Ries & Trout 经典「定位是占领心智」), (b) 信息传递与叙事 (messaging 层级 / 信息屋 + 价值主张 + 收益导向 vs 战略叙事「换框架」Andy Raskin + 表达清晰度 Emma Stratton / Punchy + 初创 homepage 定位 FletchPMM), (c) 进入市场 (GTM) 策略与产品发布 (发布分级 T1/T2/T3 + 发布流程与跨职能编排 + GTM 打法 PLG vs SLG vs 混合 + 滩头细分选择), (d) 市场与竞争情报 (竞品分析 + battlecard 战卡 + 输赢分析 win/loss + 竞争赋能 Klue/Crayon/Clozd), (e) 买家与客户研究 (ICP 理想客户画像 + 买家 / 用户 persona + Jobs-to-be-Done 任务理论 Christensen/Moesta/Ulwick ODI + 客户之声 VoC + 用真实买家测信息 Wynter/Peep Laja), (f) 销售赋能 (战卡 + pitch / 销售 deck + 一页纸 + demo 叙事 + 异议处理 + 销售培训 + 内容采用率 — 你的产出只值销售实际用到的那部分), (g) 定价与打包 (价值定价 + 打包分层 + 《Monetizing Innovation》Ramanujam/Simon-Kucher + PLG 定价 — 常与产品 / 财务共担), (h) 细分与品类 (市场细分 + TAM/SAM/SOM + 技术采用生命周期与跨越鸿沟 Geoffrey Moore + 品类设计与叙事 Play Bigger / Christopher Lochhead — 稀有且昂贵, 不是默认选项), (i) 需求生成与内容协同 (campaign 信息 + 思想领导力 + 漏斗内容 TOFU/MOFU/BOFU + ABM 基于客户营销), (j) 分析师与影响者关系 (Gartner 魔力象限 + Forrester Wave + 分析师 briefing — To B 场景, 对 pay-to-play 影响诚实标注), (k) 客户营销与倡导 (参考客户 + case study + 评测站 G2/TrustRadius/Capterra 运营 + 社区), (l) PMM 运营与度量 (影响管道 + 赢率 + 发布采用率 + 信息穿透率 + 角色汇报线「向产品还是向市场」之争 + PMM 作为战略职能 vs 接单工具人陷阱); 跨 B2B SaaS (该学科重心) / B2C 消费 / 开发者 PLG / 平台产品。不含 产品管理 (PM 造产品 / 拥有 roadmap, PMM 拥有市场 — 相邻且极易混淆) / 增长 / 效果营销 / 付费投放 (平行学科) / 品牌 / 企业传播 / 公关为终点 / 需求生成为终点 (PMM 与之协同但不等同) / 平面设计 /「做 slide 和周边的团队」(PMM 抗争的接单工具人窄化) / 泛泛「市场营销」。"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 定位与竞争性替代
  9.2 买家 job 与 ICP
  9.3 messaging 与叙事
  9.4 launch 分级与 GTM motion
  9.5 竞争情报与赋能
  9.6 定价与打包
  9.7 角色边界与度量

背后的心智模型:
  • 定位是刻意选择的「参照系」, 不是描述你有什么: 定位的本质是**选择「让你的优势成立的市场参照系」**——先问「客户不买你, 会拿什么替代 (competitive alternatives)」, 从那个参照系反推你的独特价值; 经典派 (Ries
  • 客户「雇用」产品完成一个 job — 卖结果, 不卖功能: 客户不是「买产品」, 而是**「雇用 (hire)」一个产品来完成生活/工作里的某个 job** (Christensen 奶昔例); 所以 messaging 要讲「能帮你完成什么 + 取得什么 p
  • PMM 是连接组织的战略职能, 不是「做物料的接单团队」: 产品营销由 **4 大职责**支撑 (Lauchengco《LOVED》:ambassador 带客户视角进每个决策 / strategist 决定产品如何到达市场 / storyteller 把能力

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "定位与竞争性替代"
  "买家 job 与 ICP"
  "messaging 与叙事"
  "launch 分级与 GTM motion"
  "竞争情报与赋能"
  "定价与打包"
  "角色边界与度量"
)
declare -a DIM_QUESTIONS=(
  "客户不买你时的真实替代集合 (含「自己搭/Excel/什么都不做」) + 你相对它们的独特价值 + 当前定位是否只是 slogan。"
  "客户雇这产品完成什么 job + struggling moment/switch 触发 + ICP 是否来自赢单数据而非臆测。"
  "价值主张/信息屋是否清晰可复述 + 是否有 jargon + 是否经真实买家验证 + 需不需要战略叙事换框架。"
  "这次发布的市场影响 (定 tier) + GTM motion (PLG/SLG/混合) + 跨职能依赖 + 发布后采用怎么量。"
  "真实赢输场景 + 战卡是否诚实 (无 FUD)、是否更新、销售是否真用 + trap question。"
  "真实支付意愿 (WTP) + value metric 选择 + good-better-best 分层 + 「怎么收费」是否比「收多少」更该改。"
  "这是不是 PMM 该接的活 (vs PM/demand gen/品牌) + 服务什么 GTM 目标 + 用什么度量证明价值 (非物料数量)。"
)
declare -a DIM_SOURCES=(
  "win/loss 访谈 + 销售对话 (Gong) + 竞品定价/能力页 + April Dunford 定位 5 要素 (aprildunford.com)。"
  "closed-won 共性 + JTBD switch 访谈 (Moesta) / ODI outcome (Ulwick) + 客户访谈 (User Interviews)。"
  "Wynter 买家测 + Gong 买家原话 + Emma Stratton clarity 准则 (punchy.co) + Andy Raskin 战略叙事 (andyraskin.com)。"
  "Lauchengco《LOVED》launch craft (svpg.com) + PMA launch 模板 (productmarketingalliance.com) + Pendo/Amplitude 采用度。"
  "Klue/Crayon (battlecard+监测) + Clozd win/loss + Gong (deal 竞争提及) + Wynter 战卡时效调查。"
  "Ramanujam《Monetizing Innovation》/Simon-Kucher 方法 + ProfitWell 指标 + Wynter WTP 测试 + Kyle Poyar SaaS 基准 (growthunhinged.com)。"
  "Lauchengco 4 职责框架 (svpg.com) + PMA 能力模型 (productmarketingalliance.com) + influenced pipeline/win rate/launch adoption/message pull-through 定义。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "「替代集合 X → 独特属性 Y → 客户价值 Z → 目标客户 + 市场类别选择 (反事实: 换类别强项还成立吗)」。"
  "「核心 job X → switch 触发 → ICP (证据来源) + buyer vs user persona + 服务该 job 的价值映射」。"
  "「信息屋 (主张/支柱/证据) + 买家可复述度测试结论 + (如需) 世界观转变叙事框架」。"
  "「launch tier (T1/T2/T3) + 渠道与赋能矩阵 (按 tier) + motion 适配 + 采用度量指标」。"
  "「按『我们在 X 场景赢』组织的 battlecard + 诚实对手强项应对 + trap question + 复审节奏」。"
  "「WTP 区间 + value metric + 分层方案 + (如重打包) 迁移沟通 + 风险 (营收/感知)」。"
  "「该活归属判断 (PMM/PM/demand gen) + 关联 GTM 目标 + 度量指标 + 上游战略问题 (而非直接产物)」。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
