#!/usr/bin/env bash
# topic-2.sh — 链上 决策助手 for 加密链上交易.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="加密链上交易"
TOPIC="链上"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 链上 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 在链上下单 → 则 三件套缺一不裸奔：扫合约（honeypot/权限）+ 设滑点上限 + 开 MEV 保护 RPC。案例：不设滑点裸冲新池被
  • 如果 MVRV / NUPL 进入历史极端区 → 则 （顶部贪婪或底部投降），则反情绪逐步减/加仓，而非追随群体情绪。案例：链上成本基础显示全市场深度未实现亏损（投降）时，历

相关心智模型:
  • 流动性是母潮，价格是浪（先读流动性，再读叙事）: 加密资产长期是「全球美元流动性的温度计」——价格的大方向由央行/财政释放的流动性母潮决定，单个币的叙事只是骑在母潮上的浪；资深人先判断「现在流动性在扩张还是收缩」，再谈选币。
  • 先定能亏多少，再谈能赚多少（仓位/风控 > 入场与预测）: 交易的 edge 不在「预测对方向」，而在「每笔先定义 1R 风险（在哪证明自己错）+ 用 R 倍数记录复盘」——把每笔交易当一次概率抽样，活下来的人靠期望值而非单次暴击赚钱。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "在链上下单"
  "MVRV / NUPL 进入历史极端区"
)
declare -a RULE_ACTIONS=(
  "三件套缺一不裸奔：扫合约（honeypot/权限）+ 设滑点上限 + 开 MEV 保护 RPC。案例：不设滑点裸冲新池被三明治夹走、被貔貅盘锁仓卖不出 (evidence: [T02-S035])"
  "（顶部贪婪或底部投降），则反情绪逐步减/加仓，而非追随群体情绪。案例：链上成本基础显示全市场深度未实现亏损（投降）时，历史上是分批建仓区间而非恐慌区（业内估计，非择时保证）(evidence: [T04-S025])"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
