#!/usr/bin/env bash
# topic-3.sh — 引擎 决策助手 for 数据工程 — 数据平台从业者的认知操作系统, 覆盖把数据从源系统搬运成可靠 / 可查询 / 可信赖形态供分析 / ML / 数据产品消费的全生命周期 (生成 → 摄取 → 存储 → 转换 → 服务 + 安全/数据管理/DataOps/数据架构/编排/软件工程 六条暗流, Reis & Housley 框架): 摄取与集成 (批 + CDC 变更数据捕获 Debezium + EL 工具 Fivetran/Airbyte/Meltano/dlt + Kafka Connect + schema drift) / 存储与文件表格式 (对象存储数据湖 + 列存 Parquet/ORC/Arrow/Avro + 开放表格式 Apache Iceberg/Delta Lake/Apache Hudi + lakehouse + 分区/compaction) / 转换与建模 (ELT dbt/SQLMesh + Spark + 维度建模 Kimball + Inmon + Data Vault + 大宽表 OBT + 渐变维 SCD + 增量模型 + 语义/指标层) / 编排与工作流 (Apache Airflow/Dagster/Prefect/Mage/Kestra/Apache DolphinScheduler + DAG + 幂等 + 回填 backfill + 数据资产调度) / 批流与实时 (Apache Kafka/Apache Flink/Spark Structured Streaming/Kinesis/Pulsar/Redpanda + Lambda vs Kappa + watermark/窗口/exactly-once + 流式 SQL Materialize/RisingWave + 实时 OLAP ClickHouse/Apache Druid/Apache Pinot/StarRocks/Apache Doris) / 数仓与查询引擎 (Snowflake/BigQuery/Redshift/Databricks SQL/Trino/Presto/DuckDB/Polars + 存算分离 + MPP) / 数据质量测试与可观测性 (dbt tests/Great Expectations/Soda + 数据契约 + Monte Carlo data downtime + 新鲜度/量/schema 异常检测) / 数据治理编目与血缘 (DataHub/Amundsen/OpenMetadata/Unity Catalog + 列级血缘 + PII 分类 + 访问控制 + GDPR) / DataOps 与可靠性 (数据 CI/CD + 转换版本控制 + 环境隔离 + 幂等重处理 + 数据 SLA/SLO + 计算存储 FinOps) / 数据架构范式 (现代数据栈 + lakehouse + data mesh + data fabric + 去中心化 vs 中心化所有权) / 分析工程角色 (dbt 时代连接数据工程与分析的桥) — 不含 数据科学/ML 建模本身 (是下游消费者) / BI 仪表盘制作 (serving 下游) / 数据分析报表为终点 / 'data engineer = 跑 Hadoop 的' 过时窄化 / 通用后端应用开发 (平行学科).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="数据工程 — 数据平台从业者的认知操作系统, 覆盖把数据从源系统搬运成可靠 / 可查询 / 可信赖形态供分析 / ML / 数据产品消费的全生命周期 (生成 → 摄取 → 存储 → 转换 → 服务 + 安全/数据管理/DataOps/数据架构/编排/软件工程 六条暗流, Reis & Housley 框架): 摄取与集成 (批 + CDC 变更数据捕获 Debezium + EL 工具 Fivetran/Airbyte/Meltano/dlt + Kafka Connect + schema drift) / 存储与文件表格式 (对象存储数据湖 + 列存 Parquet/ORC/Arrow/Avro + 开放表格式 Apache Iceberg/Delta Lake/Apache Hudi + lakehouse + 分区/compaction) / 转换与建模 (ELT dbt/SQLMesh + Spark + 维度建模 Kimball + Inmon + Data Vault + 大宽表 OBT + 渐变维 SCD + 增量模型 + 语义/指标层) / 编排与工作流 (Apache Airflow/Dagster/Prefect/Mage/Kestra/Apache DolphinScheduler + DAG + 幂等 + 回填 backfill + 数据资产调度) / 批流与实时 (Apache Kafka/Apache Flink/Spark Structured Streaming/Kinesis/Pulsar/Redpanda + Lambda vs Kappa + watermark/窗口/exactly-once + 流式 SQL Materialize/RisingWave + 实时 OLAP ClickHouse/Apache Druid/Apache Pinot/StarRocks/Apache Doris) / 数仓与查询引擎 (Snowflake/BigQuery/Redshift/Databricks SQL/Trino/Presto/DuckDB/Polars + 存算分离 + MPP) / 数据质量测试与可观测性 (dbt tests/Great Expectations/Soda + 数据契约 + Monte Carlo data downtime + 新鲜度/量/schema 异常检测) / 数据治理编目与血缘 (DataHub/Amundsen/OpenMetadata/Unity Catalog + 列级血缘 + PII 分类 + 访问控制 + GDPR) / DataOps 与可靠性 (数据 CI/CD + 转换版本控制 + 环境隔离 + 幂等重处理 + 数据 SLA/SLO + 计算存储 FinOps) / 数据架构范式 (现代数据栈 + lakehouse + data mesh + data fabric + 去中心化 vs 中心化所有权) / 分析工程角色 (dbt 时代连接数据工程与分析的桥) — 不含 数据科学/ML 建模本身 (是下游消费者) / BI 仪表盘制作 (serving 下游) / 数据分析报表为终点 / 'data engineer = 跑 Hadoop 的' 过时窄化 / 通用后端应用开发 (平行学科)"
TOPIC="引擎"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 引擎 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 业务说"要实时" → 则 : 则 先问"能消费的真实延迟是多少" — 非亚秒需求 (风控/实时推荐/监控) 则批/微批足够, 不上流; 真要流优先
  • 如果 选开放表格式 (Iceberg/Delta/Hudi) → 则 : 则 看现有引擎兼容 + 读写模式 (中立生态选 Iceberg / Databricks 生态选 Delta / 重

相关心智模型:
  • 幂等 + 可重跑 + 不可变分区是第一公民 — pipeline 是纯函数, 不是脚本: 一个任务的输出应只由它的输入参数决定 (纯函数), 用同一分区同一输入重跑必须覆盖而非追加、结果一致 — Maxime「Functional Data Engineering」把不可变分区 + 幂等 
  • 反过早分布式 / 单机复兴 — "Big Data is Dead", 先量化数据再选引擎: 多数公司的数据量服从幂律分布、中位数 modest, "big compute 对 99% 的 workload 已不再相关" (Tigani 业内观察); 默认 DuckDB / Polars / 

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "业务说\"要实时\""
  "选开放表格式 (Iceberg/Delta/Hudi)"
)
declare -a RULE_ACTIONS=(
  ": 则 先问\"能消费的真实延迟是多少\" — 非亚秒需求 (风控/实时推荐/监控) 则批/微批足够, 不上流; 真要流优先统一引擎/streaming SQL 而非 Lambda 双链路"
  ": 则 看现有引擎兼容 + 读写模式 (中立生态选 Iceberg / Databricks 生态选 Delta / 重 upsert+CDC 选 Hudi) + 可迁移性, 不站队\"哪个最火\""
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
