#!/usr/bin/env bash
# ai-tutoring-system-deployment.sh — AI Tutoring System Deployment SOP walkthrough for AI自适应学习.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AI自适应学习"
WORKFLOW="AI Tutoring System Deployment"

usage() {
  cat <<EOF
ai-tutoring-system-deployment.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./ai-tutoring-system-deployment.sh             # interactive
  ./ai-tutoring-system-deployment.sh --dry-run
  ./ai-tutoring-system-deployment.sh --json
  ./ai-tutoring-system-deployment.sh --explain
  ./ai-tutoring-system-deployment.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "AI Tutoring System Deployment" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 追踪-适应闭环 (Trace-then-Adapt Loop): 自适应学习的核心运作模式是「持续估计学生的潜在知识状态 → 基于估计选择最优下一步教学动作」的概率闭环, 而非简单的分数累加-推荐
  • 粒度决定效果 (Granularity Determines Effectiveness): 自适应的粒度越细 (从课程级→单元级→步骤级→子步骤级), 效果越接近人类一对一辅导 — VanLehn (2011) meta-review 证实步骤级 ITS 效果量约 d=0.76 (业内估),

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "Define pedagogical approach: Socratic method (ask guiding questions, never give direct answers — Khanmigo model), direct instruction (explain then practice), or hybrid. Encode this in the system prompt. 2. Build the knowledge base: prepare course content as a RAG corpus — chunk textbook chapters, lecture notes, and solution manuals into retrievable segments. Use embeddings (text-embedding-3-large or equivalent) and a vector store (Pinecone, pgvector, Chroma). 3. Design the prompt architecture: system prompt (role definition, pedagogical rules, safety constraints) + RAG context (retrieved content) + conversation history + student model state (current KC mastery levels). 4. Implement safety guardrails — three layers: (a) input filters (block prompt injection, off-topic requests, inappropriate content); (b) output filters (block harmful content, check factual accuracy against RAG corpus, enforce pedagogical rules like \"don't give direct answers\"); (c) conversation monitoring (log all conversations, flag anomalies for human review). 5. Implement anti-cheating measures: detect and refuse to complete homework assignments directly; instead guide student through the reasoning process. 6. Build a feedback loop: domain experts review sampled conversations for factual accuracy, pedagogical correctness, tone, and safety compliance. 7. Pilot with a controlled cohort (e.g., one classroom) and measure learning outcomes vs. control group (no AI tutor). 8. Iterate on prompts, guardrails, and RAG retrieval based on pilot data. 9. Deploy to production with monitoring: track conversation length, student satisfaction, escalation rate to human teachers, and factual accuracy rate."
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "ai-tutoring-system-deployment-walkthrough"
fi
