#!/usr/bin/env bash
# lms-and-platform-integration-lti.sh — LMS and Platform Integration (LTI/xAPI) SOP walkthrough for AI自适应学习.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AI自适应学习"
WORKFLOW="LMS and Platform Integration (LTI/xAPI)"

usage() {
  cat <<EOF
lms-and-platform-integration-lti.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./lms-and-platform-integration-lti.sh             # interactive
  ./lms-and-platform-integration-lti.sh --dry-run
  ./lms-and-platform-integration-lti.sh --json
  ./lms-and-platform-integration-lti.sh --explain
  ./lms-and-platform-integration-lti.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "LMS and Platform Integration (LTI/xAPI)" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 追踪-适应闭环 (Trace-then-Adapt Loop): 自适应学习的核心运作模式是「持续估计学生的潜在知识状态 → 基于估计选择最优下一步教学动作」的概率闭环, 而非简单的分数累加-推荐
  • 粒度决定效果 (Granularity Determines Effectiveness): 自适应的粒度越细 (从课程级→单元级→步骤级→子步骤级), 效果越接近人类一对一辅导 — VanLehn (2011) meta-review 证实步骤级 ITS 效果量约 d=0.76 (业内估),

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "Register as an LTI 1.3 Tool Provider: generate RSA key pair, configure OIDC login initiation URL, and tool launch URL. 2. Implement the LTI 1.3 launch flow: OIDC third-party login → platform returns id_token (JWT) with user identity, course context, and roles. 3. Implement LTI Advantage services as needed: Deep Linking (for content selection), Assignment and Grade Services (AGS — for grade passback), Names and Role Provisioning Services (NRPS — for roster sync). 4. Map LTI user identifiers to internal student IDs in the adaptive system — handle the case where a student accesses from multiple LMS instances. 5. Implement xAPI statement emission: on each learning event, send xAPI statement to the institutional LRS or your own LRS, including the LTI context (course_id, section) as xAPI context extensions. 6. Test integration against the 1EdTech LTI Reference Implementation — run conformance test suite. 7. Fix conformance failures, then submit for 1EdTech certification (optional but strongly recommended for institutional sales). 8. Document integration guide for LMS admins: key exchange process, launch URL configuration, grade passback setup, and troubleshooting."
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "lms-and-platform-integration-lti-walkthrough"
fi
