#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for K12 体育培训.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="K12 体育培训"
DIM_COUNT=6

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (6 个):
  9.1 政策与考纲维度（对应 §1.3 政策是需求引擎）
  9.2 业态与单店模型维度（对应 §1.6 业态决定一切 + §1.2 续费命门）
  9.3 师资与合规资质维度（对应 §1.1 能打≠能教≠能运营）
  9.4 工具与 AI 体测维度（对应 §1.6 业态 + §3 工具栈）
  9.5 流派定位维度（对应 §1.4 教育 vs 应试 + §7 智识谱系）
  9.6 时效与近期变化维度（对应 §8 诚实边界 decay）

背后的心智模型:
  • 能打 ≠ 能教 ≠ 能运营（师资三层断层）: 会打球、会教学、会运营是**三套互不蕴含的能力**——招到退役运动员只解决了第一层，教学法+持证是第二层，单店模型/续费/合规是第三层；这一行最深的坑是用第一层冒充后两层。
  • 续费率才是命门（不是满班，不是获客）: 单店生死线是**续费率 + 转介绍**，不是满班率或获客量——满班且高获客的店也会因续费塌方而死；「收钱 ≠ 课消 ≠ 确认收入」，预收费是受监管负债不是利润。
  • 政策是确定性需求引擎（读懂文件 = 读懂生意）: 这一行的需求与红线由 gov 文件**直接生成**——双减把体育从兴趣班推成刚需、中考分值改革制造确定性提分需求、课标 2022 定义教学口径、《行为规范》划合规边界；从业者必须把政策当一手情报源，不

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "政策与考纲维度（对应 §1.3 政策是需求引擎）"
  "业态与单店模型维度（对应 §1.6 业态决定一切 + §1.2 续费命门）"
  "师资与合规资质维度（对应 §1.1 能打≠能教≠能运营）"
  "工具与 AI 体测维度（对应 §1.6 业态 + §3 工具栈）"
  "流派定位维度（对应 §1.4 教育 vs 应试 + §7 智识谱系）"
  "时效与近期变化维度（对应 §8 诚实边界 decay）"
)
declare -a DIM_QUESTIONS=(
  "当地最新中考体育考纲（考项/分值/分段/过程性考核占比）+ 双减/非学科类/《行为规范》合规要求（持证/师生比/预收费/办学许可主管部门）+ 近 12 月新政（如「每天体育活动≥2 小时」三年行动 T05-S019）。"
  "目标业态（社区店/Mall/进校/中考/上门）的单店模型基准（坪效/师生比/客单价/续费率/出勤率警戒线/盈亏平衡所需学员数）+ 该业态可复制性。"
  "目标项目的法定持证要求（是否准入类——游泳/滑雪/潜水/攀岩 4 高危项目需国家资格，其余行业等级）+ 教练带教认证体系（教案/说课/损伤防护科目）+ 背景审查要求。"
  "匹配业态的教务 SaaS/获客平台/测评工具选型 + AI 体测一体机是否对齐当地考场评分引擎（哪家厂商引擎=当地多省考场同款）+ 新兴工具渗透阶段（decay risk）。"
  "目标机构/创始人/家长属哪一派（应试提分 vs 长期素养 / 体适能通识 vs 专项 / 直营 vs 加盟 / 进校 vs 校外 / 引进 vs 自研）——从其用语层判断（张口体测分数=应试派，用 physical literacy=素养派）。"
  "近 12 月该业态/工作流的变化（上门模式冲击获客·留存·开店·师资？AI 体测重塑备考？师资合规收紧？各省考纲调整？）+ 哪些假设已过时。"
)
declare -a DIM_SOURCES=(
  "国家体育总局青少年体育司 sport.gov.cn/qss/（T05-S015）+ 教育部 moe.gov.cn（T05-S016）+ 目标城市政府门户/教育考试院（如 beijing.gov.cn T05-S018）+ 华奥星空政策解读 sports.cn（T05-S019）。不写「网上搜」。"
  "懒熊体育公众号单店硬数据长文（T01-S012/T03-S020，单校区月均收入/出勤率/客单价）+ 中国体育用品业联合会行业观察 cn.csgf.org.cn（T01-S023）+ 多鲸素质教育趋势报告（CR3/参培率 T01-S025）。"
  "体育行业国家职业资格报考指南 sport.gov.cn/rlzx/（T06-S017）+ 国家职业资格目录 osta.org.cn（T06-S018）+ 退役运动员转型教练员岗前培训 sport.gov.cn（T03-S006）+ 单项协会（篮协/游泳协会）技能等级体系。"
  "vendor content-path（校宝 xiaobaoonline.com、爱耕云、三体云动 styd.cn、讯飞 edu.iflytek.com、有道 zhihui.youdao.com、恒鸿达 hengonda.com）+ 国家体育总局智能体育典型案例名单（T02-S017）+ 第三方教培 SaaS 横评（DOIT/36 氪企服点评 T02-S023）。"
  "Track 01 figures 流派对照（季浏素养/李春伟应试/张涛专项/动因直营）+ Track 06 术语层硬分裂（physical literacy vs 体测分数 T06-S022/T06-S010）+ 机构官网/课程话术的 register。"
  "懒熊体育/多鲸近期长文 + 各省政府门户中考季更新（T05-S018）+ 国家中小学/总局新政（T05-S022）+ 36 氪/中新网上门体育报道（T03-S015/T03-S016/T03-S021）。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "1 段「当地考纲 = X 项 Y 分（过程性 a/现场 b），失分大户项 = Z；合规闸 = 主管部门+持证要求+预收费上限」，直接喂 §2 playbook 4 和 playbook 8。"
  "1 段「该业态单店基准：客单约¥X、出勤率警戒线 55%、续费率目标 Y%、盈亏平衡需 Z 学员；可复制性=高/低（专项 vs 通识）」，喂 §2 playbook 5/6。"
  "1 段「该项目持证=准入类/行业等级（具体证名）；带教需补 X 科目；背景审查=是」，喂 §2 playbook 3 和 §4.6。"
  "1 段「该业态工具栈=教务[X]+获客[Y]+测评[Z]；中考则 AI 体测对齐厂商=W（当地考场同款）；新兴工具[V] decay=high 慎重资产采购」，喂 §3 决策树。"
  "1 段「该对象定位=[流派 A]，核心主张=X，与之冲突的流派=B；据此选课程逻辑+评估工具+沟通话术（素养用发展性测评，应试用考纲引擎，不混用）」，喂 §1.4 应用方式。"
  "1 段「近 12 月最大变量=[上门/AI 体测/合规/考纲]，影响 workflow=X，已过时假设=Y，建议刷新本 OS 的[§3/§4/§8]段」，回写 §8 时效。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
