#!/usr/bin/env bash
# topic-5.sh — 竞争 决策助手 for 产品营销 (PMM, Product Marketing) — 拥有「产品如何被定位 / 表达 / 发布 / 卖进市场」的从业者认知操作系统: 是产品 / 销售 / 市场 / 客户之间的连接组织, 负责把产品能力翻译成市场价值, 并把市场声音带回产品。覆盖 (a) 定位与差异化 (April Dunford 「刻意选择语境」框架 + 竞争性替代方案 + 卖价值不卖功能 + 选择「让你优势成立的市场参照系」, 对照 Ries & Trout 经典「定位是占领心智」), (b) 信息传递与叙事 (messaging 层级 / 信息屋 + 价值主张 + 收益导向 vs 战略叙事「换框架」Andy Raskin + 表达清晰度 Emma Stratton / Punchy + 初创 homepage 定位 FletchPMM), (c) 进入市场 (GTM) 策略与产品发布 (发布分级 T1/T2/T3 + 发布流程与跨职能编排 + GTM 打法 PLG vs SLG vs 混合 + 滩头细分选择), (d) 市场与竞争情报 (竞品分析 + battlecard 战卡 + 输赢分析 win/loss + 竞争赋能 Klue/Crayon/Clozd), (e) 买家与客户研究 (ICP 理想客户画像 + 买家 / 用户 persona + Jobs-to-be-Done 任务理论 Christensen/Moesta/Ulwick ODI + 客户之声 VoC + 用真实买家测信息 Wynter/Peep Laja), (f) 销售赋能 (战卡 + pitch / 销售 deck + 一页纸 + demo 叙事 + 异议处理 + 销售培训 + 内容采用率 — 你的产出只值销售实际用到的那部分), (g) 定价与打包 (价值定价 + 打包分层 + 《Monetizing Innovation》Ramanujam/Simon-Kucher + PLG 定价 — 常与产品 / 财务共担), (h) 细分与品类 (市场细分 + TAM/SAM/SOM + 技术采用生命周期与跨越鸿沟 Geoffrey Moore + 品类设计与叙事 Play Bigger / Christopher Lochhead — 稀有且昂贵, 不是默认选项), (i) 需求生成与内容协同 (campaign 信息 + 思想领导力 + 漏斗内容 TOFU/MOFU/BOFU + ABM 基于客户营销), (j) 分析师与影响者关系 (Gartner 魔力象限 + Forrester Wave + 分析师 briefing — To B 场景, 对 pay-to-play 影响诚实标注), (k) 客户营销与倡导 (参考客户 + case study + 评测站 G2/TrustRadius/Capterra 运营 + 社区), (l) PMM 运营与度量 (影响管道 + 赢率 + 发布采用率 + 信息穿透率 + 角色汇报线「向产品还是向市场」之争 + PMM 作为战略职能 vs 接单工具人陷阱); 跨 B2B SaaS (该学科重心) / B2C 消费 / 开发者 PLG / 平台产品。不含 产品管理 (PM 造产品 / 拥有 roadmap, PMM 拥有市场 — 相邻且极易混淆) / 增长 / 效果营销 / 付费投放 (平行学科) / 品牌 / 企业传播 / 公关为终点 / 需求生成为终点 (PMM 与之协同但不等同) / 平面设计 /「做 slide 和周边的团队」(PMM 抗争的接单工具人窄化) / 泛泛「市场营销」。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="产品营销 (PMM, Product Marketing) — 拥有「产品如何被定位 / 表达 / 发布 / 卖进市场」的从业者认知操作系统: 是产品 / 销售 / 市场 / 客户之间的连接组织, 负责把产品能力翻译成市场价值, 并把市场声音带回产品。覆盖 (a) 定位与差异化 (April Dunford 「刻意选择语境」框架 + 竞争性替代方案 + 卖价值不卖功能 + 选择「让你优势成立的市场参照系」, 对照 Ries & Trout 经典「定位是占领心智」), (b) 信息传递与叙事 (messaging 层级 / 信息屋 + 价值主张 + 收益导向 vs 战略叙事「换框架」Andy Raskin + 表达清晰度 Emma Stratton / Punchy + 初创 homepage 定位 FletchPMM), (c) 进入市场 (GTM) 策略与产品发布 (发布分级 T1/T2/T3 + 发布流程与跨职能编排 + GTM 打法 PLG vs SLG vs 混合 + 滩头细分选择), (d) 市场与竞争情报 (竞品分析 + battlecard 战卡 + 输赢分析 win/loss + 竞争赋能 Klue/Crayon/Clozd), (e) 买家与客户研究 (ICP 理想客户画像 + 买家 / 用户 persona + Jobs-to-be-Done 任务理论 Christensen/Moesta/Ulwick ODI + 客户之声 VoC + 用真实买家测信息 Wynter/Peep Laja), (f) 销售赋能 (战卡 + pitch / 销售 deck + 一页纸 + demo 叙事 + 异议处理 + 销售培训 + 内容采用率 — 你的产出只值销售实际用到的那部分), (g) 定价与打包 (价值定价 + 打包分层 + 《Monetizing Innovation》Ramanujam/Simon-Kucher + PLG 定价 — 常与产品 / 财务共担), (h) 细分与品类 (市场细分 + TAM/SAM/SOM + 技术采用生命周期与跨越鸿沟 Geoffrey Moore + 品类设计与叙事 Play Bigger / Christopher Lochhead — 稀有且昂贵, 不是默认选项), (i) 需求生成与内容协同 (campaign 信息 + 思想领导力 + 漏斗内容 TOFU/MOFU/BOFU + ABM 基于客户营销), (j) 分析师与影响者关系 (Gartner 魔力象限 + Forrester Wave + 分析师 briefing — To B 场景, 对 pay-to-play 影响诚实标注), (k) 客户营销与倡导 (参考客户 + case study + 评测站 G2/TrustRadius/Capterra 运营 + 社区), (l) PMM 运营与度量 (影响管道 + 赢率 + 发布采用率 + 信息穿透率 + 角色汇报线「向产品还是向市场」之争 + PMM 作为战略职能 vs 接单工具人陷阱); 跨 B2B SaaS (该学科重心) / B2C 消费 / 开发者 PLG / 平台产品。不含 产品管理 (PM 造产品 / 拥有 roadmap, PMM 拥有市场 — 相邻且极易混淆) / 增长 / 效果营销 / 付费投放 (平行学科) / 品牌 / 企业传播 / 公关为终点 / 需求生成为终点 (PMM 与之协同但不等同) / 平面设计 /「做 slide 和周边的团队」(PMM 抗争的接单工具人窄化) / 泛泛「市场营销」。"
TOPIC="竞争"

usage() {
  cat <<EOF
topic-5.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-5.sh             # interactive
  ./topic-5.sh --dry-run   # walk through but no file
  ./topic-5.sh --json      # JSON to stdout
  ./topic-5.sh --explain   # show backing playbook rules + mental models
  ./topic-5.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 竞争 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 要帮销售赢竞争性 deal → 则 : 则 出 battlecard 按「我们在什么场景下赢」组织 + 诚实承认对手强项 + trap question, 

相关心智模型:
  • 定位是刻意选择的「参照系」, 不是描述你有什么: 定位的本质是**选择「让你的优势成立的市场参照系」**——先问「客户不买你, 会拿什么替代 (competitive alternatives)」, 从那个参照系反推你的独特价值; 经典派 (Ries
  • 客户「雇用」产品完成一个 job — 卖结果, 不卖功能: 客户不是「买产品」, 而是**「雇用 (hire)」一个产品来完成生活/工作里的某个 job** (Christensen 奶昔例); 所以 messaging 要讲「能帮你完成什么 + 取得什么 p

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "要帮销售赢竞争性 deal"
)
declare -a RULE_ACTIONS=(
  ": 则 出 battlecard 按「我们在什么场景下赢」组织 + 诚实承认对手强项 + trap question, 绝不堆 FUD; 并定期用 win/loss 刷新"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-5-decision"
fi
