#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for K12 体育培训.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="K12 体育培训"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 招教练 → 则 按「能不能教会一个 6 岁孩子+能不能跟家长沟通」筛，而非按运动履历/能不能打，并核验六类持证至少持一。案例：新机构爱招
  • 如果 做中考体育备考 → 则 先拆当地考纲（各地考项/分值/分段差异巨大）+ 做基线体测定位强弱项，再按单项 ROI 排序训练，绝不用外地考纲或盲目堆
  • 如果 决定课程是引进还是自研 → 则 按「可复制性 + 本土适配（对齐课标 2022/中考考纲）+ 护城河」权衡，专项壁垒高的优先自研、要快速加盟扩张的可引进

相关心智模型:
  • 能打 ≠ 能教 ≠ 能运营（师资三层断层）: 会打球、会教学、会运营是**三套互不蕴含的能力**——招到退役运动员只解决了第一层，教学法+持证是第二层，单店模型/续费/合规是第三层；这一行最深的坑是用第一层冒充后两层。
  • 续费率才是命门（不是满班，不是获客）: 单店生死线是**续费率 + 转介绍**，不是满班率或获客量——满班且高获客的店也会因续费塌方而死；「收钱 ≠ 课消 ≠ 确认收入」，预收费是受监管负债不是利润。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "招教练"
  "做中考体育备考"
  "决定课程是引进还是自研"
)
declare -a RULE_ACTIONS=(
  "按「能不能教会一个 6 岁孩子+能不能跟家长沟通」筛，而非按运动履历/能不能打，并核验六类持证至少持一。案例：新机构爱招前职业球员撑门面，资深机构跳过明星运动员光环看教学潜质 (T03-S006)；YBDL 全外教/签艾弗森造势但教学交付跟不上爆雷，是「能打盖过能教」的反面锚 (T01-S010)"
  "先拆当地考纲（各地考项/分值/分段差异巨大）+ 做基线体测定位强弱项，再按单项 ROI 排序训练，绝不用外地考纲或盲目堆量。案例：云南体育与语数英并列 100 分、北京 70 分（22 选 4），考纲不本地化等于白练 (T04-S013, T04-S014)；资深教练对已达满分线项目停投（满分封顶 ROI 为零），把时间砸在「不及格→及格」的边际项目 (T03-S009)"
  "按「可复制性 + 本土适配（对齐课标 2022/中考考纲）+ 护城河」权衡，专项壁垒高的优先自研、要快速加盟扩张的可引进通用体系。案例：SPARK 等引进课程被质疑水土不服、不对齐中考考纲 (T04-S036, T06-S008)；张涛「教曲棍球的没法教击剑」说明专项支撑系统不可通用、自研才是真护城河 (T01-S003)"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
