#!/usr/bin/env bash
# topic-1.sh — 医疗 决策助手 for 医疗美容.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="医疗美容"
TOPIC="医疗"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 医疗 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 要落地任何项目/产品/获客 → 则 先验「机构《医疗机构执业许可证》+ 主诊医师备案 + NMPA 械字号（国械注准）正品」三件套，合规是入场券、前置于一切
  • 如果 做任何医疗操作 → 则 全程留痕——术前照、知情同意书、病历同步留档，既为医疗连续性也为法律举证。案例：投诉/纠纷时病历与术前照是举证关键；of
  • 如果 做机构经营 → 则 把合规风控前置于获客、把劝退当长期口碑投资，用医疗信任 + 私域复购替代低价引流 + 焦虑升单。案例：广告「八不准」下制

相关心智模型:
  • 医美的第一性是医疗，不是消费: 医疗美容首先是外科与皮肤科的**医疗行为**（可致盲、致残、致死），不是快消品；任何决策的第一约束是安全与合规，不是美学最大化或转化率。
  • 先安全后审美：风险分层判断: 资深人的核心能力不是「打得漂亮」，而是**在安全处提效、在危险处零妥协**——知道哪一步能省、哪一步一步都不能省。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "要落地任何项目/产品/获客"
  "做任何医疗操作"
  "做机构经营"
)
declare -a RULE_ACTIONS=(
  "先验「机构《医疗机构执业许可证》+ 主诊医师备案 + NMPA 械字号（国械注准）正品」三件套，合规是入场券、前置于一切。案例：选填充剂先查国械注准编号与分类，再谈品牌；机构获客前先取得《医疗广告审查证明》。evidence: [T03-S001, T06-S004]"
  "全程留痕——术前照、知情同意书、病历同步留档，既为医疗连续性也为法律举证。案例：投诉/纠纷时病历与术前照是举证关键；off-label 用药（瘦肩针/颈部肉毒）须单独书面告知。evidence: [T03-S001, T06-S002]"
  "把合规风控前置于获客、把劝退当长期口碑投资，用医疗信任 + 私域复购替代低价引流 + 焦虑升单。案例：广告「八不准」下制造容貌焦虑、用对比图、变相软文均违规。evidence: [T03-S011, T06-S004]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
