#!/usr/bin/env bash
# topic-3.sh — 战略 决策助手 for 管理咨询.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="管理咨询"
TOPIC="战略"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 战略 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 要判断一个「战略」是真是假 → 则 用 Rumelt kernel 三问自检（有诊断吗？有指导方针吗？有连贯行动吗？）+ Collis&Rukstad「35
  • 如果 要衡量项目/战略的价值 → 则 别停在 deck 厚度，问「客户影响是什么、谁负责落地」——results not reports，建议里带 owner
  • 如果 听到「套个框架就交差 / 用 SWOT 当深度战略 / 满嘴 synergy·paradigm shift·low-ha → 则 识别为 frameworks-as-theater 与 buzzword bingo——推不出 so-what 的框架是

相关心智模型:
  • 假设驱动是地图不是答案：先射箭再画靶 ⇄ 随时 kill 假设（第一性张力）: 面对模糊大问题，资深咨询人不从穷举数据出发，而是 Day-1 就基于经验立一个**可证伪**的初步答案（hypothesis / initial hypothesis）当地图，再只做能 kill 或 
  • 战略 = 做选择 / 做不同，不是运营效率、不是愿望清单: 这行顶级战略 figure 跨流派一致——战略的本质是**逼自己做取舍**（Martin：where-to-play × how-to-win 两个不可分割的选择；Rumelt：kernel = 诊断

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "要判断一个「战略」是真是假"
  "要衡量项目/战略的价值"
  "听到「套个框架就交差 / 用 SWOT 当深度战略 / 满嘴 synergy·paradigm shift·low-hanging fruit」"
)
declare -a RULE_ACTIONS=(
  "用 Rumelt kernel 三问自检（有诊断吗？有指导方针吗？有连贯行动吗？）+ Collis&Rukstad「35 字说不清=没战略」测试——没有取舍的目标清单是 bad strategy"
  "别停在 deck 厚度，问「客户影响是什么、谁负责落地」——results not reports，建议里带 owner + timeline + 预期影响"
  "识别为 frameworks-as-theater 与 buzzword bingo——推不出 so-what 的框架是表演道具，资深人用真术语、嘲空心装饰词"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
