#!/usr/bin/env bash
# workflow-6.sh — 机构合规获客 → 面诊转化 → 复购（机构经营链） SOP walkthrough for 医疗美容.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="医疗美容"
WORKFLOW="机构合规获客 → 面诊转化 → 复购（机构经营链）"

usage() {
  cat <<EOF
workflow-6.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-6.sh             # interactive
  ./workflow-6.sh --dry-run
  ./workflow-6.sh --json
  ./workflow-6.sh --explain
  ./workflow-6.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "机构合规获客 → 面诊转化 → 复购（机构经营链）" 工作流。

一句话: 从「机构需要持续获客并合规活下去」到「合规获客 → 咨询面诊转化 → 履约复购」的经营闭环——本行「医疗本质 ⇄ 消费营销」张力最集中的 workflow。

入门 SOP 共 4 步, 失败模式自检 4 项。

相关心智模型:
  • 医美的第一性是医疗，不是消费: 医疗美容首先是外科与皮肤科的**医疗行为**（可致盲、致残、致死），不是快消品；任何决策的第一约束是安全与合规，不是美学最大化或转化率。
  • 先安全后审美：风险分层判断: 资深人的核心能力不是「打得漂亮」，而是**在安全处提效、在危险处零妥协**——知道哪一步能省、哪一步一步都不能省。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**获客渠道布局**：线上垂直平台（新氧/美团医美/更美）+ 内容种草（抖音/小红书）+ 私域/转介绍，多渠道组合。 evidence: [T03-S015]"
  "**内容合规生产**：科普/案例内容须合规——不得制造容貌焦虑、不得用诊疗前后对比图、不得疗效保证、不得以科普/新闻形式变相发布广告、不得把无资质者包装成「医生/专家」。 evidence: [T03-S002]"
  "**咨询面诊转化**：线上到店后由医生主导面诊（见 workflow 1），把诉求转成有适应证的方案——医疗诊断框架而非纯销售话术。 evidence: [T03-S001]"
  "**履约与复购**：规范履约（合规操作+术后随访）沉淀信任，自然带动复购/转介绍/客单提升。 evidence: [T03-S001]"
)
declare -a FAILURE_MODES=(
  "**对比图/焦虑式种草**：actionable—不要发诊疗前后对比图或「五分钟变美/一针逆龄」文案，直接违广告执法指南，平台封号+罚款。"
  "**包装无资质者为「专家」**：actionable—只让有主诊备案的医生出镜科普，MCN 批量孵化「网红医生」是监管重点打击对象。"
  "**纯低价引流到店强升单**：体验价钓鱼+渠道返佣推高价=口碑反噬+投诉激增。"
  "**AI 模拟图当「效果保证」**：违广告法，仅作预期沟通不可承诺。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-6-walkthrough"
fi
