#!/usr/bin/env bash
# workflow-5.sh — 术后医嘱与随访 SOP walkthrough for 医疗美容.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="医疗美容"
WORKFLOW="术后医嘱与随访"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "术后医嘱与随访" 工作流。

一句话: 从「操作结束、求美者离院」到「护理依从 + 按期复查 + 早期并发症监测 + 效果维持/补打 + 留客复购」的闭环。

入门 SOP 共 4 步, 失败模式自检 3 项。

相关心智模型:
  • 医美的第一性是医疗，不是消费: 医疗美容首先是外科与皮肤科的**医疗行为**（可致盲、致残、致死），不是快消品；任何决策的第一约束是安全与合规，不是美学最大化或转化率。
  • 先安全后审美：风险分层判断: 资深人的核心能力不是「打得漂亮」，而是**在安全处提效、在危险处零妥协**——知道哪一步能省、哪一步一步都不能省。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**即刻术后处置**：冷敷/压迫止血、观察 15–30 分钟（即刻过敏/血管事件窗）再离院。 evidence: [T03-S009]"
  "**术后医嘱**：护理要点（清洁/防晒/忌烟酒辛辣/特定项目忌按压/防感染）、肿胀淤青预期、何时复查、出现哪些征象立即返院（剧痛/苍白/视力异常/发热）。 evidence: [T03-S009]"
  "**复查与补打**：按项目周期复查（玻尿酸 2–4 周看吸收补量、肉毒 2 周看效果调整、再生类按月看胶原起效），评估效果与并发症。"
  "**病历与随访记录**：复查/补打/不良反应入病历，维护求美者档案。 evidence: [T03-S001]"
)
declare -a FAILURE_MODES=(
  "**离院前不留观/不交代危险信号**：求美者迟报栓塞。actionable—术后留观 15–30 分钟 + 明确告知「剧痛/苍白/视力异常立即返院」。"
  "**再生类未到起效期被催加打**：actionable—术前+术后双重告知缓释起效曲线，避免「无效」误判致过量。"
  "**随访沦为焦虑式升单**：踩广告合规红线。avoid：随访以医疗关怀+并发症监测为主，复购自然发生。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
