#!/usr/bin/env bash
# workflow-1.sh — 审美设计与方案规划（全脸结构化设计） SOP walkthrough for 医疗美容.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="医疗美容"
WORKFLOW="审美设计与方案规划（全脸结构化设计）"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "审美设计与方案规划（全脸结构化设计）" 工作流。

一句话: 从「求美者指着某一处说想改」到「一份基于面部分区/比例/动态/老化机制的全脸结构化方案——注射 vs 手术 vs 联合、单项 vs 联合、分次 vs 一次」。

入门 SOP 共 5 步, 失败模式自检 3 项。

相关心智模型:
  • 医美的第一性是医疗，不是消费: 医疗美容首先是外科与皮肤科的**医疗行为**（可致盲、致残、致死），不是快消品；任何决策的第一约束是安全与合规，不是美学最大化或转化率。
  • 先安全后审美：风险分层判断: 资深人的核心能力不是「打得漂亮」，而是**在安全处提效、在危险处零妥协**——知道哪一步能省、哪一步一步都不能省。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**面部三维评估**：按三庭五眼/黄金比例 + 容积缺失（中面部老化核心）+ 动态（表情肌）+ 支撑（骨吸收/SMAS 松弛）分层评估，而非「头痛医头」。 evidence: [T03-S005]"
  "**机制→术式分流**：容积缺失→填充；动态皱纹/肌肥大→肉毒；肤质问题→光电；松弛按层次（浅射频/深超声/线雕/手术）。 evidence: [T03-S005]"
  "**注射 vs 手术 vs 联合判断**：轻中度→微创注射/光电；重度松弛/结构问题→手术；多数复杂面容→联合方案。"
  "**分次与预算规划**：把全脸方案拆成分次（先打地基支撑后做精细，留量观察），匹配求美者预算与恢复期。"
  "**可视化与方案确认**：用 VISIA/3D 模拟把方案讲给求美者，对齐预期，记录方案。 evidence: [T03-S014]"
)
declare -a FAILURE_MODES=(
  "**单点思维/头痛医头**：只处理求美者指的部位，整体失衡。避免：永远做全脸结构评估再下针。"
  "**机械套编码忽视个体**：actionable—不要把 MD Codes 当填空模板逐码套，先核对该求美者的真实解剖（血管走行/骨量/皮肤厚度）。"
  "**一次过量/不可逆设计**：actionable—不要一次打满全脸，分次留量观察，尤其再生类（不可溶解，过量难修）。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
