#!/usr/bin/env bash
# scratch.sh — 设计一堂 Scratch 启蒙课 SOP walkthrough for 青少年编程教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="青少年编程教育"
WORKFLOW="设计一堂 Scratch 启蒙课"

usage() {
  cat <<EOF
scratch.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./scratch.sh             # interactive
  ./scratch.sh --dry-run
  ./scratch.sh --json
  ./scratch.sh --explain
  ./scratch.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "设计一堂 Scratch 启蒙课" 工作流。

一句话: 为6-9岁儿童设计一节60分钟 Scratch 项目式编程课，产出课件+学生项目模板。

入门 SOP 共 6 步, 失败模式自检 0 项。

相关心智模型:
  • 制作即学习 (Making Is Learning): 编程教育的核心不是教「编程语言语法」, 而是让学生通过创造可分享的外部作品来建构内部知识 — Papert 的建构主义 (constructionism) 是整个领域的哲学根基
  • 低地板、高天花板、宽墙壁 (Low Floor, High Ceiling, Wide Walls): 好的编程教育工具必须同时满足三个维度 — 入门门槛低 (low floor, 6 岁能开始)、能力上限高 (high ceiling, 能做复杂项目)、创作方向广 (wide walls, 不限于一种

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "确定教学主题与目标: 选一个与孩子兴趣相关的场景（动物游戏、节日故事、迷宫），确定1-2个核心知识点（如事件+循环），写出\"学生能做到…\"的可观察目标；inputs: 课程大纲/年级、outputs: 教学目标陈述。"
  "拆解知识点与认知阶梯: 参照 CSTA K-12 标准 (evidence: [T03-S004]) 将目标分解为「看懂→模仿→改动→创作」四阶，每阶设计对应活动；inputs: 教学目标，outputs: 活动序列草稿。"
  "设计 Scratch 项目载体: 在 scratch.mit.edu (evidence: [T03-S001]) 制作 starter 项目，留出3-5个关键空白让学生填写；inputs: 主题，outputs: starter .sb3 文件。"
  "准备教学素材: 录制或收集演示视频（MIT Learning Library evidence: [T03-S002]）、准备问题卡、打印\"调试检查表\"；inputs: starter项目，outputs: 课堂素材包。"
  "撰写60分钟课堂脚本: 按「5min导入→10min演示→25min实践→10min展示→10min总结反思」分配时间，写出每段的教师话术要点和预期学生反应；inputs: 素材包，outputs: 教案文档。"
  "制定评价标准: 设计3维度量规（功能完成度/创意度/代码可读性），每维度3级描述；inputs: 教学目标，outputs: 评价量规表。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "scratch-walkthrough"
fi
