#!/usr/bin/env bash
# workflow-3.sh — 招生与转化流程 SOP walkthrough for 青少年编程教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="青少年编程教育"
WORKFLOW="招生与转化流程"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "招生与转化流程" 工作流。

一句话: 在新学期/寒暑假前8-12周，通过公开课→体验课→正课的漏斗将潜在家庭转化为付费学员。

入门 SOP 共 6 步, 失败模式自检 0 项。

相关心智模型:
  • 制作即学习 (Making Is Learning): 编程教育的核心不是教「编程语言语法」, 而是让学生通过创造可分享的外部作品来建构内部知识 — Papert 的建构主义 (constructionism) 是整个领域的哲学根基
  • 低地板、高天花板、宽墙壁 (Low Floor, High Ceiling, Wide Walls): 好的编程教育工具必须同时满足三个维度 — 入门门槛低 (low floor, 6 岁能开始)、能力上限高 (high ceiling, 能做复杂项目)、创作方向广 (wide walls, 不限于一种

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "制定招生目标与漏斗预期: 设定目标学员数（如30人/班×2班=60人），逆推漏斗各层——付费学员60人需体验课120人需公开课进场300人；inputs: 机构容量，outputs: 招生目标表。"
  "设计引流活动（公开课/线上直播): 设计30-45分钟免费公开课（如\"孩子用Scratch做会动的生日贺卡\"），海报/短视频在微信/抖音/小红书投放，目标触达500-1000人；inputs: 招生目标，outputs: 活动策划书+物料。"
  "线索收集与初步筛选: 公开课后收集家长微信/手机，24小时内跟进添加，发送课程介绍+体验课预约链接；inputs: 公开课出席名单，outputs: 线索数据库。"
  "体验课设计与交付: 设计60-90分钟付费或免费体验课（强调\"孩子现场做出作品\"），课中家长旁听，课后销售顾问主动沟通；对应教育招生漏斗最关键节点 (evidence: [T03-S004])；inputs: 线索，outputs: 体验课出席学生+家长意向记录。"
  "家长决策沟通与异议处理: 整理常见家长疑虑（孩子坐不住/价格/学了有用吗），准备标准话术；1对1沟通优于群发；inputs: 家长意向记录，outputs: 意向家长跟进列表。"
  "正式转化与入学手续: 签协议/缴费/排班，同时邀请家长加入专属微信群，建立后续粘性；inputs: 意向确认，outputs: 学员花名册+缴费凭证。"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
