#!/usr/bin/env bash
# chinese-long-form-tv-drama.sh — 中国长剧集编剧流程 (Chinese Long-Form TV Drama) SOP walkthrough for 影视编剧 (Scriptwriting / Screenwriting) — 为电影 / 电视 / 流媒体剧集写戏剧蓝本的从业者认知操作系统: 决定「讲什么故事、人物是谁为何转变、场景如何被戏剧化、主题为何重要」的学科 —— 区别于导演 (调度 / 视觉实现)、制片 (融资 / 排期)、小说 (无格式 / 场景 / 视觉动作约束)。覆盖 (a) 故事与结构理论 (亚里士多德《诗学》情节 / 人物 / 思想 + 突转 peripeteia / 发现 anagnorisis + 净化 catharsis; Syd Field 范式 / 三幕 / 情节点; Freytag 金字塔; Egri 前提; McKee《故事》掌控性理念 / 鸿沟 / 价值正负转变 / 激励事件 / 渐进式复杂化; Truby《故事剖析》22 步 + 道德论证; Vogler/Campbell 英雄之旅; Blake Snyder《救猫咪》15 拍节拍表; Dan Harmon 故事环; John Yorke 五幕《进入森林》; Frank Daniel 八序列法; 起承转合东亚戏剧结构), (b) 人物 (想要 vs 需要 / 外在目标 vs 内在缺失, 人物弧光 正 / 负 / 平, flaw-wound-ghost 创伤背景, 主动 vs 被动主角的能动性, Egri 三维人物 生理 / 社会 / 心理, 反派是主角的镜子, 群像与关系网, 人物在压力下的选择中显形), (c) 对白 (潜台词 subtext, 对白即动作与冲突而非信息, 避免太直白 on the nose, 人物独特声口, 信息植入 exposition, Mamet/Sorkin 意图-阻碍式对白, 展示而非告知, 中文剧台词工艺), (d) 场景与序列工艺 (场景是有目标 / 冲突 / 转折的微型故事, 场景价值充能与转折点, 晚进早出, 八序列法, set piece, 转场, 场景头 / 动作行 / 括号提示 格式工艺), (e) 主题与前提 (掌控性理念 / 前提, 主题是被戏剧化的论证而非说教, 道德论证 Truby, 主题统一性, 这到底在讲什么), (f) 类型 (类型惯例是对观众的承诺, Snyder 10 类故事, 颠覆 vs 尊重套路, 类型片 vs 文艺片, 中国类型 主旋律 / 古装 / 年代 / 悬疑 / 甜宠 / 都市 / 军旅 / 历史正剧), (g) 格式与工业流程 (好莱坞剧本格式与 Final Draft, logline 一句话故事, treatment 故事大纲, 节拍表, 分场 / 分集大纲, spec 原创剧本 vs 委托, pitch, coverage, 美剧编剧室与 showrunner 制; 中国 大纲→人物小传→分集大纲→剧本, 长剧集 40 集结构, 网络电影 / 网大, 分账剧, 平台定制剧, 微短剧竖屏短剧), (h) 改稿与开发 (写作就是改写, 改稿 / 润色 / 推倒重写, 处理意见 / 改稿意见, 片方与平台 notes, 杀死你的宝贝, 围读, 开发地狱), (i) 改编 (IP改编 小说 / 漫画 / 游戏改编, 忠于精神而非字句, 压缩, 中国网文 IP 热), (j) 中国影视编剧产业现实 (审查 / 广电总局约束, 备案 / 立项, 平台定制剧 爱优腾芒, 分账, 编剧维权 署名权 / 欠薪 / 枪手, 注水剧, 流量 + 大IP 资本逻辑 vs 原创工艺, 导演中心制 vs 编剧话语权), (k) 编剧职业与工艺生涯 (spec vs 委托, 编剧 vs 编审 / 策划, 单兵 vs 编剧室, 在开发链条中的位置, WGA 与署名仲裁规范, 入行, 中国编剧地位与权益)。跨 电影 / 美剧流媒体 / 中国电影与长剧集。不含 导演 / 摄影 / 制片 / 融资 / 表演 / 电影理论批评为终点 / 泛小说写作 / 纪录片 / 新闻 —— 本 skill 是「戏剧化编剧」工艺: 故事 / 人物 / 场景 / 对白 / 主题 / 结构 / 格式 与围绕它们的产业流程。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="影视编剧 (Scriptwriting / Screenwriting) — 为电影 / 电视 / 流媒体剧集写戏剧蓝本的从业者认知操作系统: 决定「讲什么故事、人物是谁为何转变、场景如何被戏剧化、主题为何重要」的学科 —— 区别于导演 (调度 / 视觉实现)、制片 (融资 / 排期)、小说 (无格式 / 场景 / 视觉动作约束)。覆盖 (a) 故事与结构理论 (亚里士多德《诗学》情节 / 人物 / 思想 + 突转 peripeteia / 发现 anagnorisis + 净化 catharsis; Syd Field 范式 / 三幕 / 情节点; Freytag 金字塔; Egri 前提; McKee《故事》掌控性理念 / 鸿沟 / 价值正负转变 / 激励事件 / 渐进式复杂化; Truby《故事剖析》22 步 + 道德论证; Vogler/Campbell 英雄之旅; Blake Snyder《救猫咪》15 拍节拍表; Dan Harmon 故事环; John Yorke 五幕《进入森林》; Frank Daniel 八序列法; 起承转合东亚戏剧结构), (b) 人物 (想要 vs 需要 / 外在目标 vs 内在缺失, 人物弧光 正 / 负 / 平, flaw-wound-ghost 创伤背景, 主动 vs 被动主角的能动性, Egri 三维人物 生理 / 社会 / 心理, 反派是主角的镜子, 群像与关系网, 人物在压力下的选择中显形), (c) 对白 (潜台词 subtext, 对白即动作与冲突而非信息, 避免太直白 on the nose, 人物独特声口, 信息植入 exposition, Mamet/Sorkin 意图-阻碍式对白, 展示而非告知, 中文剧台词工艺), (d) 场景与序列工艺 (场景是有目标 / 冲突 / 转折的微型故事, 场景价值充能与转折点, 晚进早出, 八序列法, set piece, 转场, 场景头 / 动作行 / 括号提示 格式工艺), (e) 主题与前提 (掌控性理念 / 前提, 主题是被戏剧化的论证而非说教, 道德论证 Truby, 主题统一性, 这到底在讲什么), (f) 类型 (类型惯例是对观众的承诺, Snyder 10 类故事, 颠覆 vs 尊重套路, 类型片 vs 文艺片, 中国类型 主旋律 / 古装 / 年代 / 悬疑 / 甜宠 / 都市 / 军旅 / 历史正剧), (g) 格式与工业流程 (好莱坞剧本格式与 Final Draft, logline 一句话故事, treatment 故事大纲, 节拍表, 分场 / 分集大纲, spec 原创剧本 vs 委托, pitch, coverage, 美剧编剧室与 showrunner 制; 中国 大纲→人物小传→分集大纲→剧本, 长剧集 40 集结构, 网络电影 / 网大, 分账剧, 平台定制剧, 微短剧竖屏短剧), (h) 改稿与开发 (写作就是改写, 改稿 / 润色 / 推倒重写, 处理意见 / 改稿意见, 片方与平台 notes, 杀死你的宝贝, 围读, 开发地狱), (i) 改编 (IP改编 小说 / 漫画 / 游戏改编, 忠于精神而非字句, 压缩, 中国网文 IP 热), (j) 中国影视编剧产业现实 (审查 / 广电总局约束, 备案 / 立项, 平台定制剧 爱优腾芒, 分账, 编剧维权 署名权 / 欠薪 / 枪手, 注水剧, 流量 + 大IP 资本逻辑 vs 原创工艺, 导演中心制 vs 编剧话语权), (k) 编剧职业与工艺生涯 (spec vs 委托, 编剧 vs 编审 / 策划, 单兵 vs 编剧室, 在开发链条中的位置, WGA 与署名仲裁规范, 入行, 中国编剧地位与权益)。跨 电影 / 美剧流媒体 / 中国电影与长剧集。不含 导演 / 摄影 / 制片 / 融资 / 表演 / 电影理论批评为终点 / 泛小说写作 / 纪录片 / 新闻 —— 本 skill 是「戏剧化编剧」工艺: 故事 / 人物 / 场景 / 对白 / 主题 / 结构 / 格式 与围绕它们的产业流程。"
WORKFLOW="中国长剧集编剧流程 (Chinese Long-Form TV Drama)"

usage() {
  cat <<EOF
chinese-long-form-tv-drama.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./chinese-long-form-tv-drama.sh             # interactive
  ./chinese-long-form-tv-drama.sh --dry-run
  ./chinese-long-form-tv-drama.sh --json
  ./chinese-long-form-tv-drama.sh --explain
  ./chinese-long-form-tv-drama.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "中国长剧集编剧流程 (Chinese Long-Form TV Drama)" 工作流。

一句话: 中国平台定制剧/电视剧从备案到交稿的工业化全流程, 在审查约束+平台 notes+长篇 (30-40集) 结构内创作

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 想要 vs 需要 (Want vs Need — 人物弧光的发动机): 主角的外在目标 (想要) 与内在缺失 (需要) 之间的鸿沟驱动一切戏剧张力 — 弧光不是角色变好,是角色认清自己真正需要什么
  • 每场戏必须转 (Scene Value Charge — 场景诊断的唯一标准): 一场戏读完,如果某个价值 (爱/恨、希望/绝望、自由/困境) 没有从正翻到负或从负翻到正,这场戏就没有存在理由 — 删或重写

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "立项/备案与题材合规前置 — 选题阶段先核审查约束 (广电总局/电影局备案是法定前置, 古装/涉案/年代/重大题材各有红线), 题材不过审写得再好也白写 → 2. 写故事大纲 — 全剧核心人物+主线+主要矛盾+主题+大致走向, 是平台/制片方决定立不立项的物料, 也是备案提交内容 → 3. 写人物小传 — 主要角色的出身/关系网/性格/弧光独立文档, 中国长剧尤重人物关系网 (群像/家庭/职场), 人物小传是中国流程的硬节点 (立项常要交) → 4. 写分集大纲 — 全剧拆成 30-40 集, 每集写出主要事件+集尾钩子, 确保每集有看点且整体 (起承转合/多线推进) 站得住, 分集大纲是平台付款节点 (交大纲→付第二笔款) → 5. 分集写剧本 — 按中文格式 (场号/内外景/人物/对白) 逐集写, 可多人分工 (主笔定调+分集编剧), 主笔统稿保证人物声口与节奏一致 → 6. 改稿/处理平台意见 — 接收平台/制片/导演多头 notes, 找 note behind the note, 按结构→人物→场景→对白分层改 evidence: [T03-S012, T03-S013, T03-S014, T03-S015]"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "chinese-long-form-tv-drama-walkthrough"
fi
