#!/usr/bin/env bash
# hand-history-review-solver-gto.sh — 牌局复盘 / hand history review（标记疑难手 → 数据库/solver 比对 → 找偏离 GTO 的漏洞） SOP walkthrough for 德州扑克策略.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="德州扑克策略"
WORKFLOW="牌局复盘 / hand history review（标记疑难手 → 数据库/solver 比对 → 找偏离 GTO 的漏洞）"

usage() {
  cat <<EOF
hand-history-review-solver-gto.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./hand-history-review-solver-gto.sh             # interactive
  ./hand-history-review-solver-gto.sh --dry-run
  ./hand-history-review-solver-gto.sh --json
  ./hand-history-review-solver-gto.sh --explain
  ./hand-history-review-solver-gto.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "牌局复盘 / hand history review（标记疑难手 → 数据库/solver 比对 → 找偏离 GTO 的漏洞）" 工作流。

一句话: 从「打完一堆牌但不知道哪儿打错」到「一份带对错判定 + 修补假设的疑难手清单」——把牌桌经验转成可学习的反馈。 (evidence: [T03-S003, T03-S010])

入门 SOP 共 4 步, 失败模式自检 3 项。

相关心智模型:
  • GTO 基线 ⇄ 剥削偏离(equilibrium baseline ⇄ exploitative deviation): 先建一条**不可剥削的均衡基线 (GTO)**,再针对具体对手/人群的可观察漏洞**偏离 (exploit)** 去最大化 EV;GTO 是回得去的**锚点**,不是终点。
  • Range-first(先想范围,再想这手牌): 扑克决策的**原子单位是范围(对手在某节点所有可能持牌的概率分布)**,不是单张牌;高手把对手 put on a *range* 再随每条街的行动收窄。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**打牌时标记疑难手**:实时给拿不准 / 输大底池的手打 tag(客户端 mark / note)。 (evidence: [T03-S003])"
  "**导出 / 上传到 solver 或数据库**:把标记手喂 GTO Wizard Analyze / HH Analyzer 或 HM3/PT4 重放。 (evidence: [T03-S010, T03-S012])"
  "**逐手对比 GTO / 自己的合理线**:看每个决策点自己的动作 vs 均衡动作的偏离方向与 EV 损失。 (evidence: [T03-S010, T03-S012])"
  "**写下 leak 假设**:把反复出现的偏离(如「3-bet 底池 OOP c-bet 过频」)记成待查假设。 (evidence: [T03-S004])"
)
declare -a FAILURE_MODES=(
  "**结果导向复盘**:只复盘输钱的手、用「输了所以打错」判定 → 强化错误结论(赢的烂打被当对的)。**避免**:实时标记疑难手而非事后挑,judged 只看 +EV/-EV 不看输赢。 (evidence: [T03-S019])"
  "**把方差当 leak**:在几十手样本上看到「这条线亏」就大改打法 → 改错方向。**避免**:改打法前确认样本量足够支撑结论(小样本存疑)。"
  "**复盘不闭环**:看完 solver 偏离但不记、不回灌 study → 下次同一 spot 再错。**避免**:每次复盘产出一份 leak 假设清单,喂给 workflow 1/3。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "hand-history-review-solver-gto-walkthrough"
fi
