#!/usr/bin/env bash
# leak-finding-via-hud-leak-filter.sh — Leak finding via HUD+数据库 / 自动 leak 报告（filter spot → 对比 GTO baseline → 定位高频亏损点 → 针对性修补） SOP walkthrough for 德州扑克策略.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="德州扑克策略"
WORKFLOW="Leak finding via HUD+数据库 / 自动 leak 报告（filter spot → 对比 GTO baseline → 定位高频亏损点 → 针对性修补）"

usage() {
  cat <<EOF
leak-finding-via-hud-leak-filter.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./leak-finding-via-hud-leak-filter.sh             # interactive
  ./leak-finding-via-hud-leak-filter.sh --dry-run
  ./leak-finding-via-hud-leak-filter.sh --json
  ./leak-finding-via-hud-leak-filter.sh --explain
  ./leak-finding-via-hud-leak-filter.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Leak finding via HUD+数据库 / 自动 leak 报告（filter spot → 对比 GTO baseline → 定位高频亏损点 → 针对性修补）" 工作流。

一句话: 从「整体 winrate 在跌但不知道哪漏」到「一张按金额排序的高频亏损点清单 + 修补优先级」——用大样本统计找系统性漏洞(而非单手)。 (evidence: [T03-S011, T03-S013])

入门 SOP 共 4 步, 失败模式自检 3 项。

相关心智模型:
  • GTO 基线 ⇄ 剥削偏离(equilibrium baseline ⇄ exploitative deviation): 先建一条**不可剥削的均衡基线 (GTO)**,再针对具体对手/人群的可观察漏洞**偏离 (exploit)** 去最大化 EV;GTO 是回得去的**锚点**,不是终点。
  • Range-first(先想范围,再想这手牌): 扑克决策的**原子单位是范围(对手在某节点所有可能持牌的概率分布)**,不是单张牌;高手把对手 put on a *range* 再随每条街的行动收窄。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**filter spot**:在数据库(PT4/HM3)按位置 / 街 / 线 filter 出某类 spot 的大样本统计(VPIP/PFR/3-bet/c-bet/fold-to-cbet 等)。 (evidence: [T03-S013])"
  "**对比 GTO / 赢家 baseline**:把自己的频率 vs GTO 频率(GTO Reports 色块)或 vs 赢家库(Leak Buster)比,标出 under-bluff / over-fold 等偏离。 (evidence: [T03-S011, T03-S013])"
  "**定位高频亏损点**:按出现频率 × 单次 EV 损失排序,锁定最烧钱的 leak(自动报告会直接排好)。 (evidence: [T03-S013, T03-S011])"
  "**针对性修补**:对头号 leak 跑 workflow 1(solver 研究)建正确打法 + heuristic,再回牌桌刻意执行。 (evidence: [T03-S014, T03-S002])"
)
declare -a FAILURE_MODES=(
  "**小样本下结论**:几十手的 3-bet% 是噪声不是 read → 把方差当 leak 乱改。**避免**:每个 leak 结论前看样本量,population read 要大样本。 (evidence: [T03-S013])"
  "**抓小放大**:修一堆低频边缘 leak,放过高频主 leak(如「翻前开太松」)→ winrate 没起色。**避免**:严格按「频率 × EV 损失」排序,先修前 3。"
  "**拿错 baseline**:对弱场也用纯 GTO 当标尺,把「偏离 GTO 去剥削」误判成 leak 改掉 → 反而打没了利润。**避免**:弱场用 population baseline,强场用 GTO baseline。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "leak-finding-via-hud-leak-filter-walkthrough"
fi
