#!/usr/bin/env bash
# sop-bankroll.sh — 资金管理 / 升降级 SOP（bankroll 规则、何时升降级、方差缓冲） SOP walkthrough for 德州扑克策略.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="德州扑克策略"
WORKFLOW="资金管理 / 升降级 SOP（bankroll 规则、何时升降级、方差缓冲）"

usage() {
  cat <<EOF
sop-bankroll.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./sop-bankroll.sh             # interactive
  ./sop-bankroll.sh --dry-run
  ./sop-bankroll.sh --json
  ./sop-bankroll.sh --explain
  ./sop-bankroll.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "资金管理 / 升降级 SOP（bankroll 规则、何时升降级、方差缓冲）" 工作流。

一句话: 从「我有 X 钱」到「我现在该打哪个级别、什么时候升、什么时候必须降」——用 buy-in 规则把高方差游戏控制在「不破产」边界内。 (evidence: [T03-S017, T03-S018])

入门 SOP 共 4 步, 失败模式自检 3 项。

相关心智模型:
  • GTO 基线 ⇄ 剥削偏离(equilibrium baseline ⇄ exploitative deviation): 先建一条**不可剥削的均衡基线 (GTO)**,再针对具体对手/人群的可观察漏洞**偏离 (exploit)** 去最大化 EV;GTO 是回得去的**锚点**,不是终点。
  • Range-first(先想范围,再想这手牌): 扑克决策的**原子单位是范围(对手在某节点所有可能持牌的概率分布)**,不是单张牌;高手把对手 put on a *range* 再随每条街的行动收窄。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定 buy-in 规则**:按游戏类型设最少 buy-in 数缓冲——**现金局 ~35-65 buy-in**(GTO Wizard,保守端可低至 20-40)、**MTT 因方差极高需 ~75-125 buy-in**(GTO Wizard;PokerCoaching *Bankroll Bible* 保守标准 100,职业常备 150-200)。底层逻辑是 **Kelly 准则**:押多少取决于 winrate 与方差。 (evidence: [T03-S017, T03-S018])"
  "**设升级触发线**:打到某 buy-in 数(如够新级别的 buy-in 门槛)才上移。 (evidence: [T03-S017])"
  "**设降级触发线(stop-loss for roll)**:跌破缓冲线立即降级,不硬撑。 (evidence: [T03-S017, T03-S018])"
  "**方差缓冲判断**:把单 session 输赢与「正常方差范围」对照,别因短期波动乱改级别或打法。 (evidence: [T03-S017])"
)
declare -a FAILURE_MODES=(
  "**roll 太薄 + 高方差游戏**:用现金局的 buy-in 数去打 MTT → 方差远超缓冲,正 ROI 也破产。**避免**:MTT 用 ~75-125+ buy-in(职业 150-200),现金 ~35-65,别混用。 (evidence: [T03-S017, T03-S018])"
  "**赢上头乱升级**:短期上风就跳级别,遇下风被打回。**避免**:只在达预设升级线 + winrate 有样本支撑时升,且用 shot-taking 试而非梭哈。"
  "**输不肯降级**:跌破缓冲线为面子硬撑原级别 → 归零。**避免**:把降级触发线当硬规则,跌破即降,不谈判。 (evidence: [T03-S018])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "sop-bankroll-walkthrough"
fi
