#!/usr/bin/env bash
# individual-student-counseling.sh — Individual Student Counseling (学生个案心理辅导) SOP walkthrough for 青少年心理健康教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="青少年心理健康教育"
WORKFLOW="Individual Student Counseling (学生个案心理辅导)"

usage() {
  cat <<EOF
individual-student-counseling.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./individual-student-counseling.sh             # interactive
  ./individual-student-counseling.sh --dry-run
  ./individual-student-counseling.sh --json
  ./individual-student-counseling.sh --explain
  ./individual-student-counseling.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Individual Student Counseling (学生个案心理辅导)" 工作流。

一句话: From a referred or screened student to a structured short-term counseling intervention with measurable progress and a clear endpoint or external referral.

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 发展适配优先 — 青春期不是成人的缩小版: 青少年的大脑、认知和情绪发展处于独特阶段——前额叶皮层 25 岁前未完全成熟、杏仁核反应性高、同伴影响权重超越成人直觉——任何干预方案必须以发展阶段为锚点设计,而非照搬成人模型。
  • 预防优于治疗 — MTSS 三级金字塔: 心理健康教育的核心逻辑是三级预防——Tier 1 全员预防(SEL/心理课)覆盖约 80% 的学生、Tier 2 小组干预(针对筛查出的 at-risk 群体)覆盖约 15%、Tier 3 个别临床干

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "Conduct intake: review screening data, gather developmental/family history, administer baseline measures (PHQ-A, GAD-7, or SDQ subscales), and obtain informed consent/assent -- skipping baseline means no way to measure progress or justify continued services 2. Develop intervention plan: identify 2-3 measurable goals, select evidence-based approach (CBT-A for anxiety/depression, MI for motivation/behavior change, solution-focused for brief school contexts), and set session frequency (typically weekly, 6-12 sessions) -- no plan means sessions drift without direction 3. Deliver structured sessions: follow manualized protocol where possible (e.g., Coping Cat for anxiety, FRIENDS for younger students) while maintaining therapeutic alliance -- abandoning structure reduces efficacy; rigid adherence without rapport loses the adolescent 4. Monitor progress every 3-4 sessions using brief measures (PHQ-A, session rating scales) and adjust approach if no improvement by session 4-6 -- failing to monitor leads to ineffective counseling continuing for months 5. Coordinate with teachers and parents: share relevant (non-confidential) strategies for classroom/home support -- isolated counseling without environmental support has limited generalization 6. Plan termination or referral: if goals met, transition to check-in schedule; if needs exceed school capacity (severe depression, active eating disorder, complex trauma), warm referral to community provider -- abrupt termination undoes therapeutic gains; holding cases beyond competence risks harm"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "individual-student-counseling-walkthrough"
fi
