#!/usr/bin/env bash
# parent-school-mh-communication.sh — Parent-School MH Communication (家校联动心理健康沟通) SOP walkthrough for 青少年心理健康教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="青少年心理健康教育"
WORKFLOW="Parent-School MH Communication (家校联动心理健康沟通)"

usage() {
  cat <<EOF
parent-school-mh-communication.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./parent-school-mh-communication.sh             # interactive
  ./parent-school-mh-communication.sh --dry-run
  ./parent-school-mh-communication.sh --json
  ./parent-school-mh-communication.sh --explain
  ./parent-school-mh-communication.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Parent-School MH Communication (家校联动心理健康沟通)" 工作流。

一句话: From an identified student concern or parent inquiry to a structured home-school collaboration plan that aligns family and school support strategies.

入门 SOP 共 1 步, 失败模式自检 0 项。

相关心智模型:
  • 发展适配优先 — 青春期不是成人的缩小版: 青少年的大脑、认知和情绪发展处于独特阶段——前额叶皮层 25 岁前未完全成熟、杏仁核反应性高、同伴影响权重超越成人直觉——任何干预方案必须以发展阶段为锚点设计,而非照搬成人模型。
  • 预防优于治疗 — MTSS 三级金字塔: 心理健康教育的核心逻辑是三级预防——Tier 1 全员预防(SEL/心理课)覆盖约 80% 的学生、Tier 2 小组干预(针对筛查出的 at-risk 群体)覆盖约 15%、Tier 3 个别临床干

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "Initiate contact within 48 hours of trigger: schedule face-to-face or video meeting (not email for sensitive topics) using strengths-first framing -- delayed or deficit-focused contact triggers parental defensiveness and disengagement 2. Prepare for meeting: review student data (screening results, behavioral observations, academic impact), prepare plain-language summary avoiding clinical jargon, and have referral resources ready -- unprepared meetings erode credibility and waste family time 3. Conduct collaborative meeting: share observations using \"I notice\" language, ask about home context, listen for cultural and family factors, and co-develop 2-3 action items with clear ownership (school does X, family does Y) -- one-directional lecturing alienates parents, especially across cultural divides 4. Provide psychoeducation materials: age-appropriate MH information, local resource guide, and crisis contact numbers -- families without context cannot support at home 5. Establish follow-up schedule (biweekly check-in for active concerns, monthly for monitoring) and preferred communication channel -- no follow-up plan means the collaboration dies after the first meeting 6. Document meeting outcomes, action items, and next steps in student file; share summary with parent -- undocumented agreements lead to conflicting recollections"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "parent-school-mh-communication-walkthrough"
fi
