#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 影视编剧 (Scriptwriting / Screenwriting) — 为电影 / 电视 / 流媒体剧集写戏剧蓝本的从业者认知操作系统: 决定「讲什么故事、人物是谁为何转变、场景如何被戏剧化、主题为何重要」的学科 —— 区别于导演 (调度 / 视觉实现)、制片 (融资 / 排期)、小说 (无格式 / 场景 / 视觉动作约束)。覆盖 (a) 故事与结构理论 (亚里士多德《诗学》情节 / 人物 / 思想 + 突转 peripeteia / 发现 anagnorisis + 净化 catharsis; Syd Field 范式 / 三幕 / 情节点; Freytag 金字塔; Egri 前提; McKee《故事》掌控性理念 / 鸿沟 / 价值正负转变 / 激励事件 / 渐进式复杂化; Truby《故事剖析》22 步 + 道德论证; Vogler/Campbell 英雄之旅; Blake Snyder《救猫咪》15 拍节拍表; Dan Harmon 故事环; John Yorke 五幕《进入森林》; Frank Daniel 八序列法; 起承转合东亚戏剧结构), (b) 人物 (想要 vs 需要 / 外在目标 vs 内在缺失, 人物弧光 正 / 负 / 平, flaw-wound-ghost 创伤背景, 主动 vs 被动主角的能动性, Egri 三维人物 生理 / 社会 / 心理, 反派是主角的镜子, 群像与关系网, 人物在压力下的选择中显形), (c) 对白 (潜台词 subtext, 对白即动作与冲突而非信息, 避免太直白 on the nose, 人物独特声口, 信息植入 exposition, Mamet/Sorkin 意图-阻碍式对白, 展示而非告知, 中文剧台词工艺), (d) 场景与序列工艺 (场景是有目标 / 冲突 / 转折的微型故事, 场景价值充能与转折点, 晚进早出, 八序列法, set piece, 转场, 场景头 / 动作行 / 括号提示 格式工艺), (e) 主题与前提 (掌控性理念 / 前提, 主题是被戏剧化的论证而非说教, 道德论证 Truby, 主题统一性, 这到底在讲什么), (f) 类型 (类型惯例是对观众的承诺, Snyder 10 类故事, 颠覆 vs 尊重套路, 类型片 vs 文艺片, 中国类型 主旋律 / 古装 / 年代 / 悬疑 / 甜宠 / 都市 / 军旅 / 历史正剧), (g) 格式与工业流程 (好莱坞剧本格式与 Final Draft, logline 一句话故事, treatment 故事大纲, 节拍表, 分场 / 分集大纲, spec 原创剧本 vs 委托, pitch, coverage, 美剧编剧室与 showrunner 制; 中国 大纲→人物小传→分集大纲→剧本, 长剧集 40 集结构, 网络电影 / 网大, 分账剧, 平台定制剧, 微短剧竖屏短剧), (h) 改稿与开发 (写作就是改写, 改稿 / 润色 / 推倒重写, 处理意见 / 改稿意见, 片方与平台 notes, 杀死你的宝贝, 围读, 开发地狱), (i) 改编 (IP改编 小说 / 漫画 / 游戏改编, 忠于精神而非字句, 压缩, 中国网文 IP 热), (j) 中国影视编剧产业现实 (审查 / 广电总局约束, 备案 / 立项, 平台定制剧 爱优腾芒, 分账, 编剧维权 署名权 / 欠薪 / 枪手, 注水剧, 流量 + 大IP 资本逻辑 vs 原创工艺, 导演中心制 vs 编剧话语权), (k) 编剧职业与工艺生涯 (spec vs 委托, 编剧 vs 编审 / 策划, 单兵 vs 编剧室, 在开发链条中的位置, WGA 与署名仲裁规范, 入行, 中国编剧地位与权益)。跨 电影 / 美剧流媒体 / 中国电影与长剧集。不含 导演 / 摄影 / 制片 / 融资 / 表演 / 电影理论批评为终点 / 泛小说写作 / 纪录片 / 新闻 —— 本 skill 是「戏剧化编剧」工艺: 故事 / 人物 / 场景 / 对白 / 主题 / 结构 / 格式 与围绕它们的产业流程。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="影视编剧 (Scriptwriting / Screenwriting) — 为电影 / 电视 / 流媒体剧集写戏剧蓝本的从业者认知操作系统: 决定「讲什么故事、人物是谁为何转变、场景如何被戏剧化、主题为何重要」的学科 —— 区别于导演 (调度 / 视觉实现)、制片 (融资 / 排期)、小说 (无格式 / 场景 / 视觉动作约束)。覆盖 (a) 故事与结构理论 (亚里士多德《诗学》情节 / 人物 / 思想 + 突转 peripeteia / 发现 anagnorisis + 净化 catharsis; Syd Field 范式 / 三幕 / 情节点; Freytag 金字塔; Egri 前提; McKee《故事》掌控性理念 / 鸿沟 / 价值正负转变 / 激励事件 / 渐进式复杂化; Truby《故事剖析》22 步 + 道德论证; Vogler/Campbell 英雄之旅; Blake Snyder《救猫咪》15 拍节拍表; Dan Harmon 故事环; John Yorke 五幕《进入森林》; Frank Daniel 八序列法; 起承转合东亚戏剧结构), (b) 人物 (想要 vs 需要 / 外在目标 vs 内在缺失, 人物弧光 正 / 负 / 平, flaw-wound-ghost 创伤背景, 主动 vs 被动主角的能动性, Egri 三维人物 生理 / 社会 / 心理, 反派是主角的镜子, 群像与关系网, 人物在压力下的选择中显形), (c) 对白 (潜台词 subtext, 对白即动作与冲突而非信息, 避免太直白 on the nose, 人物独特声口, 信息植入 exposition, Mamet/Sorkin 意图-阻碍式对白, 展示而非告知, 中文剧台词工艺), (d) 场景与序列工艺 (场景是有目标 / 冲突 / 转折的微型故事, 场景价值充能与转折点, 晚进早出, 八序列法, set piece, 转场, 场景头 / 动作行 / 括号提示 格式工艺), (e) 主题与前提 (掌控性理念 / 前提, 主题是被戏剧化的论证而非说教, 道德论证 Truby, 主题统一性, 这到底在讲什么), (f) 类型 (类型惯例是对观众的承诺, Snyder 10 类故事, 颠覆 vs 尊重套路, 类型片 vs 文艺片, 中国类型 主旋律 / 古装 / 年代 / 悬疑 / 甜宠 / 都市 / 军旅 / 历史正剧), (g) 格式与工业流程 (好莱坞剧本格式与 Final Draft, logline 一句话故事, treatment 故事大纲, 节拍表, 分场 / 分集大纲, spec 原创剧本 vs 委托, pitch, coverage, 美剧编剧室与 showrunner 制; 中国 大纲→人物小传→分集大纲→剧本, 长剧集 40 集结构, 网络电影 / 网大, 分账剧, 平台定制剧, 微短剧竖屏短剧), (h) 改稿与开发 (写作就是改写, 改稿 / 润色 / 推倒重写, 处理意见 / 改稿意见, 片方与平台 notes, 杀死你的宝贝, 围读, 开发地狱), (i) 改编 (IP改编 小说 / 漫画 / 游戏改编, 忠于精神而非字句, 压缩, 中国网文 IP 热), (j) 中国影视编剧产业现实 (审查 / 广电总局约束, 备案 / 立项, 平台定制剧 爱优腾芒, 分账, 编剧维权 署名权 / 欠薪 / 枪手, 注水剧, 流量 + 大IP 资本逻辑 vs 原创工艺, 导演中心制 vs 编剧话语权), (k) 编剧职业与工艺生涯 (spec vs 委托, 编剧 vs 编审 / 策划, 单兵 vs 编剧室, 在开发链条中的位置, WGA 与署名仲裁规范, 入行, 中国编剧地位与权益)。跨 电影 / 美剧流媒体 / 中国电影与长剧集。不含 导演 / 摄影 / 制片 / 融资 / 表演 / 电影理论批评为终点 / 泛小说写作 / 纪录片 / 新闻 —— 本 skill 是「戏剧化编剧」工艺: 故事 / 人物 / 场景 / 对白 / 主题 / 结构 / 格式 与围绕它们的产业流程。"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 故事结构诊断
  9.2 人物弧光验证
  9.3 类型合约审查
  9.4 对白与潜台词审查
  9.5 中国影视合规前置
  9.6 改稿策略制定
  9.7 Spec 投递与职业策略

背后的心智模型:
  • 想要 vs 需要 (Want vs Need — 人物弧光的发动机): 主角的外在目标 (想要) 与内在缺失 (需要) 之间的鸿沟驱动一切戏剧张力 — 弧光不是角色变好,是角色认清自己真正需要什么
  • 每场戏必须转 (Scene Value Charge — 场景诊断的唯一标准): 一场戏读完,如果某个价值 (爱/恨、希望/绝望、自由/困境) 没有从正翻到负或从负翻到正,这场戏就没有存在理由 — 删或重写
  • 结构是工具不是紧身衣 (Structure as Diagnostic, Not Straitjacket): 节拍表/三幕结构/英雄之旅是诊断已完成作品问题的工具,不是从空白页开始填空的模板 — 用模板填出来的故事可预测、同质化,用原理长出来的故事才有机

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "故事结构诊断"
  "人物弧光验证"
  "类型合约审查"
  "对白与潜台词审查"
  "中国影视合规前置"
  "改稿策略制定"
  "Spec 投递与职业策略"
)
declare -a DIM_QUESTIONS=(
  "给定故事概念/剧本, 按三幕结构 + McKee 价值转变 + Truby 22 步 + Snyder 15 拍交叉诊断, 找结构薄弱点 (激励事件位置/中点/第二幕/高潮)"
  "给定角色, 检查 want/need 冲突、flaw-wound-ghost 三角、弧光类型 (正/负/平) 是否自洽; 反派是否有内在逻辑"
  "给定故事类型, 列出该类型的必备场景和观众期待, 检查是否都兑现; 是否有意识颠覆 (颠覆 vs 遗漏)"
  "给定对白段落, 检查是否有 on the nose (太直白), 是否每个角色有独特声口 (盲测), 是否有潜台词层"
  "给定中国影视项目, 评估题材红线 (广电总局题材引导/禁区)、备案立项可行性、平台偏好 (爱优腾芒)、审查风险点"
  "给定改稿 notes (片方/平台/导演), 诊断 note behind the note (真问题), 制定分层改稿计划 (结构→人物→场景→对白)"
  "给定编剧的作品/背景, 评估最优投递路径 (Black List/竞赛/agent), 职业阶段对应的策略 (入门 spec / 进阶 assignment / 资深 showrunner)"
)
declare -a DIM_SOURCES=(
  "SKILL.md §1 心智模型 (1.2 场景必须转 + 1.3 结构工具非紧身衣) + §2 Playbook (rules 2,7) + Track 04 canon 结构理论"
  "SKILL.md §1 心智模型 (1.1 want vs need) + §2 Playbook (rule 1) + Track 01 figures (Truby/Egri/McKee 的人物理论)"
  "SKILL.md §1 心智模型 (1.5 类型合约) + §2 Playbook (rules 5,10) + Track 04 canon (Snyder 10 类) + Track 06 glossary (类型术语)"
  "SKILL.md §1 心智模型 (1.4 对白即动作) + §2 Playbook (rule 6) + §5 表达 DNA (5.3 外行破绽) + Track 06 glossary (subtext/on the nose)"
  "SKILL.md §2 Playbook (rule 9) + §4 Workflow 3 (中国长剧集) + Workflow 8 (审查备案) + Track 06 glossary (中国产业术语)"
  "SKILL.md §1 心智模型 (1.6 写作就是改写) + §2 Playbook (rule 3) + §4 Workflow 4 (改稿流程)"
  "SKILL.md §4 Workflow 6 (Spec 投递) + §3 工具栈 (Black List/竞赛平台) + Track 05 sources (竞赛/平台生态)"
)
declare -a DIM_OUTPUT_FORMATS=(
  "「结构诊断报告: 3 个薄弱节拍 + 每个的修复方向 (引用具体心智模型)」"
  "「人物弧光卡: want=X / need=Y / flaw=Z / wound=W / 弧光类型=正/负/平 / 弧光完成时刻=场景 N」"
  "「类型合约清单: 类型=X / 必备场景 N 个 / 已兑现 M 个 / 缺失: [列出] / 有意颠覆: [列出]」"
  "「对白诊断: on the nose 场景 N 处 / 声口区分度: 高/中/低 / 潜台词最强场景: [场景号] / 建议改写: [具体段落]」"
  "「合规前置评估: 题材风险=高/中/低 / 红线触碰点: [列出] / 建议规避策略: [具体] / 目标平台: [推荐] / 备案可行性: 是/否+理由」"
  "「改稿诊断: 表面 notes N 条 / note behind the note M 个 / 改稿优先级: [结构级 X 处 > 人物级 Y 处 > 场景级 Z 处] / 建议: 接的 notes + 坚守的 notes + 理由」"
  "「投递策略: 目标=入行/进阶/转型 / 推荐路径: [ranked list] / 预期时间线: [阶段性目标] / 当前 spec 评估: logline 强度/格式/市场定位」"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
