#!/usr/bin/env bash
# workflow-5.sh — 学术诚信审查 SOP walkthrough for 教育SaaS.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="教育SaaS"
WORKFLOW="学术诚信审查"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "学术诚信审查" 工作流。

入门 SOP 共 7 步, 失败模式自检 3 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "提交设置: 教师在LMS作业中启用Turnitin（或PlagScan/iThenticate），配置排除规则（参考文献/引用块）[T03-S007]"
  "自动检测: 学生提交后，系统自动运行相似度检测（全球论文库/互联网/机构内部库）+ AI写作检测 [T03-S007]"
  "报告生成: 生成相似度百分比 + 来源高亮 + AI概率分（0-100%）[T03-S007]"
  "教师审查: 教师查看报告，结合上下文判断（合理引用 vs 抄袭；AI辅助 vs AI生成）[T03-S007]"
  "初步处置: 根据判断：①通过 ②要求修改重提 ③启动正式学术不端调查程序 [T03-S018]"
  "正式调查（如触发）: 通知学生→学生陈述→院系委员会→处理决定（警告/重修/开除）[T03-S018]"
  "记录存档: 所有判定和通信记录入学术诚信数据库，供未来参考 [T03-S018]"
)
declare -a FAILURE_MODES=(
  "教师过度依赖相似度分数（如\">20%就违规\"），忽视上下文导致误判"
  "AI检测误报导致学生投诉风暴（ESL/非母语写作风格与AI相近）"
  "调查流程不透明，学生不了解申诉权利，造成信任危机"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
