#!/usr/bin/env bash
# workflow-4.sh — 签约与上架 + 日更连载（签约后的连载工程闭环） SOP walkthrough for 网文写作.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="网文写作"
WORKFLOW="签约与上架 + 日更连载（签约后的连载工程闭环）"

usage() {
  cat <<EOF
workflow-4.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-4.sh             # interactive
  ./workflow-4.sh --dry-run
  ./workflow-4.sh --json
  ./workflow-4.sh --explain
  ./workflow-4.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "签约与上架 + 日更连载（签约后的连载工程闭环）" 工作流。

一句话: 从「三章/三万字达标」到「签约→新书期推荐→上架→稳定日更+存稿+断章」的连载长跑——这是影视编剧完全没有的**日更体力战 + 存稿纪律 + 断章留人**工程。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 黄金三章定生死：为留人而非为铺垫写开局: 网文开局不是慢热铺垫，是前三章/万字内必须抛出金手指 + 制造冲突 + 埋钩子 + 建立代入，否则签约率与追读直接塌——「最惨/最爽不过三章」。
  • 爽点是可理性设计的工程对象，不是灵感: 愤怒的香蕉「一开始是欲望，到后来是情绪，最后变成需求」——爽点能被作者主动观察、拆解、设计，心理描写可把爽感挖到极致，而非等灵感降临。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**达标投稿/签约**：作品达平台字数线（起点约 3 万字）由网编审核签约；选定平台决定收益模式（起点付费均订 vs 番茄免费完读率/广告分成）。 (evidence: [T02-S006, T02-S008])"
  "**走新书期/盯追读**：新书期靠推荐位+追读率 PK 资源（起点追读率是新书生死线；番茄看完读率/试读期）。 (evidence: [T03-S007, T03-S010])"
  "**上架+爆更**：上架当天至少发 3 章（合格线）、10 章见诚意；推荐期/上升期立即加更接流量。 (evidence: [T03-S013])"
  "**建日更+存稿纪律**：按平台节奏稳定日更（起点要稳定、晋江要质量、飞卢要速度、番茄要完读率），发书前攒 3-10 万字存稿。 (evidence: [T03-S004, T03-S013])"
  "**断章**：每章在悬念最高处收尾（卡剧情不卡字数），逼读者追更/付费。 (evidence: [T04-S002, T03-S013])"
)
declare -a FAILURE_MODES=(
  "**零存稿发书**：没存稿就发书，遇卡文直接断更，读者流失不回头 → 发书前按手速攒 3-10 万字缓冲。"
  "**盲目跟风日更过量**：手速不够却硬日更 6000+ 字，导致卡文断更 → 按自身产能定日更量，稳定 > 爆量。"
  "**断章卡字数不卡剧情**：为凑字数硬断在情节平淡处 → 断在悬念/钩子最高处。"
  "**错过加更窗口**：拿到推荐却不加更，流量空转 → 上升期立即加更接流量。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-4-walkthrough"
fi
