#!/usr/bin/env bash
# workflow-2.sh — 人物与关系设计 + 大纲制作（可执行蓝图） SOP walkthrough for 网文写作.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="网文写作"
WORKFLOW="人物与关系设计 + 大纲制作（可执行蓝图）"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "人物与关系设计 + 大纲制作（可执行蓝图）" 工作流。

一句话: 从「立意/设定已定」到「一份能支撑数百万字连载的人物卡 + 分层大纲（总纲/卷纲/细纲/章纲）」——男频重设定线推进，女频重情感线/CP 推进。

入门 SOP 共 4 步, 失败模式自检 3 项。

相关心智模型:
  • 黄金三章定生死：为留人而非为铺垫写开局: 网文开局不是慢热铺垫，是前三章/万字内必须抛出金手指 + 制造冲突 + 埋钩子 + 建立代入，否则签约率与追读直接塌——「最惨/最爽不过三章」。
  • 爽点是可理性设计的工程对象，不是灵感: 愤怒的香蕉「一开始是欲望，到后来是情绪，最后变成需求」——爽点能被作者主动观察、拆解、设计，心理描写可把爽感挖到极致，而非等灵感降临。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**设计主角+成长弧**：主角金手指如何随剧情升级，成长主题（如「莫欺少年穷」）。 (evidence: [T04-S002])"
  "**配置反派/配角/（女频）CP**：反派提供强矛盾，配角承接支线，女频 CP 承接情感线。 (evidence: [T03-S001, T03-S006])"
  "**写总大纲+卷纲**：主线+支线、分卷目标。男频按力量/势力线分卷，女频按情感阶段分卷。 (evidence: [T04-S002])"
  "**写近期细纲/章纲**：把当前卷拆成可日更的章节单元，每章定爽点与断章位。 (evidence: [T03-S003, T04-S002])"
)
declare -a FAILURE_MODES=(
  "**细纲写太死又写太满**：花一个月写完全书细纲，结果连载 50 章后读者数据要求转向，细纲全废 → 细纲只做近 1-2 卷，远期留弹性。"
  "**反派/CP 立不住**：男频反派工具化没威胁、女频 CP 没张力 → 反派要能持续给主角制造强矛盾，CP 要有情绪拉扯。"
  "**多线叙事乱**：群像/多势力线记不住、写串 → 用思维导图/无上限设定卡管理人物关系与时间线。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
