#!/usr/bin/env bash
# accessibility-wcag.sh — 无障碍合规（accessibility / WCAG） SOP walkthrough for 产品设计 / UX 设计.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="产品设计 / UX 设计"
WORKFLOW="无障碍合规（accessibility / WCAG）"

usage() {
  cat <<EOF
accessibility-wcag.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./accessibility-wcag.sh             # interactive
  ./accessibility-wcag.sh --dry-run
  ./accessibility-wcag.sh --json
  ./accessibility-wcag.sh --explain
  ./accessibility-wcag.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "无障碍合规（accessibility / WCAG）" 工作流。

一句话: 从「设计默认只服务健全用户」到「符合 WCAG 2.2 AA、对障碍用户可用、满足法规（如欧盟 EAA）」，把无障碍从事后补救变设计内建。

入门 SOP 共 5 步, 失败模式自检 3 项。

相关心智模型:
  • 行为 > 自陈（You are not the user）: 设计决策必须基于**观察到的真实行为**，而非设计师/利益相关者的意见、也不是用户口头说的偏好——"你不是用户"，"opinions are not data"。 (figures: Krug / H
  • 认知负荷最小化（Don't Make Me Think）: 好设计让"正确操作显而易见"，把思考成本从用户身上移走——识别（recognition）优于回忆（recall），扫读优于阅读，满意即止（satisficing）。 (figures: Krug / 

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定标准 + 范围**: 确定目标等级（通常 WCAG 2.x AA）与适用法规（EAA 等），划定要合规的页面/流程。跳过→做了一堆无障碍工作却不满足实际法规等级。 (evidence: [T03-S015, T03-S017])"
  "**设计阶段内建**: 配色对比度达标、不靠纯色传信息、可聚焦/键盘可达、文本可缩放、表单有标签。跳过→把无障碍推给开发末期补救，成本翻倍且补不全。 (evidence: [T03-S015])"
  "**自动扫描**: 用工具扫对比度/缺 alt/语义等机器可查项。跳过→明显问题漏网。 (evidence: [T03-S016])"
  "**人工审查 + 辅助技术测试**: 自动扫描只覆盖一部分，需人工 + 屏幕阅读器/键盘实测。跳过→以为合规其实大量体验问题（自动工具查不到）残留。 (evidence: [T03-S016])"
  "**出报告 + 修复 + 复测**: 记录不符合项、修复、回归测试。跳过→审计发现问题但不闭环，合规失败。 (evidence: [T03-S016])"
)
declare -a FAILURE_MODES=(
  "末期补救: 上线前才想起无障碍，对比度/结构性问题已无法低成本修。**在设计阶段就查对比度/键盘/语义，并把规则下沉到设计系统组件。** (evidence: [T03-S015])"
  "只跑自动扫描就声称合规: 自动工具只覆盖部分准则。**自动扫描后必须做人工 + 屏幕阅读器/键盘实测，否则合规是假的。** (evidence: [T03-S016])"
  "不让障碍用户参与: 健全人代测漏掉真实痛点。**安排真实辅助技术用户测关键流程。** (evidence: [T03-S016])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "accessibility-wcag-walkthrough"
fi
