#!/usr/bin/env bash
# handoff.sh — handoff / 设计 → 开发交付 SOP walkthrough for 产品设计 / UX 设计.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="产品设计 / UX 设计"
WORKFLOW="handoff / 设计 → 开发交付"

usage() {
  cat <<EOF
handoff.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./handoff.sh             # interactive
  ./handoff.sh --dry-run
  ./handoff.sh --json
  ./handoff.sh --explain
  ./handoff.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "handoff / 设计 → 开发交付" 工作流。

一句话: 从「设计在 Figma 里 ready」到「工程拿到精确规格（尺寸/token/状态/交互）并实现得一致」，让「设计的」与「建出来的」尽量重合。

入门 SOP 共 5 步, 失败模式自检 3 项。

相关心智模型:
  • 行为 > 自陈（You are not the user）: 设计决策必须基于**观察到的真实行为**，而非设计师/利益相关者的意见、也不是用户口头说的偏好——"你不是用户"，"opinions are not data"。 (figures: Krug / H
  • 认知负荷最小化（Don't Make Me Think）: 好设计让"正确操作显而易见"，把思考成本从用户身上移走——识别（recognition）优于回忆（recall），扫读优于阅读，满意即止（satisficing）。 (figures: Krug / 

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**整理设计文件**: 命名规范、用 auto-layout、组件化、把变量/token 接好，标 ready-for-dev。跳过→工程看不懂哪版是终稿，靠猜，返工。 (evidence: [T03-S011])"
  "**标注规格 + 边界状态**: 在 Dev Mode 标注交互、空/错/加载态、响应式断点、可访问性要求。跳过→工程只实现 happy path，边界态各写各的。 (evidence: [T03-S010])"
  "**绑定 token / 变量**: 让间距/颜色/字号引用变量而非硬编码值，工程映射到代码 token。跳过→工程手抄魔法数字，设计系统失效。 (evidence: [T03-S011, T03-S013])"
  "**交付会 + 关联工单**: 与工程过一遍，把设计关联到 Jira 等工单。跳过→「扔过墙」，问题攒到上线前爆发。 (evidence: [T03-S010])"
  "**实现后 QA（design review）**: 设计师对照检查实现一致性。跳过→产品上线与设计有可见偏差，体验打折。 (evidence: [T03-S010])"
)
declare -a FAILURE_MODES=(
  "「扔过墙」式交付: 设计完丢链接给工程就不管。**从早期就拉工程进设计评审，把 handoff 变成确认而非移交。** (evidence: [T03-S010])"
  "硬编码值不用 token: 工程手抄间距/颜色数字，下次改 token 全乱。**设计端先把变量/token 接好，让工程映射而非手抄。** (evidence: [T03-S013, T03-S011])"
  "没标边界状态: 只给 happy path，空/错/加载态工程乱猜。**交付前补齐空/错/加载/响应式四类状态。** (evidence: [T03-S010])"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "handoff-walkthrough"
fi
